// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    time::{SystemTime, UNIX_EPOCH},
};

use super::exclusions::{Exclusions, glob_matches};
use super::*;

const HEADER: &str = "// SPDX-License-Identifier: MPL-2.0\n\
// This Source Code Form is subject to the terms of the Mozilla Public\n\
// License, v. 2.0. If a copy of the MPL was not distributed with this\n\
// file, You can obtain one at https://mozilla.org/MPL/2.0/.\n\n";

#[test]
fn classifies_notice_generated_other_and_missing() {
    assert_eq!(classify(&format!("{HEADER}fn f() {{}}\n")), Notice::Present);
    assert_eq!(
        classify(&format!("#!/usr/bin/env rust-script\n{HEADER}")),
        Notice::Present
    );
    assert_eq!(classify("// @generated by build.rs\n"), Notice::Generated);
    assert_eq!(
        classify("// SPDX-License-Identifier: MIT OR Apache-2.0\n"),
        Notice::OtherLicense
    );
    assert_eq!(classify("//! Crate docs.\nfn f() {}\n"), Notice::Missing);
}

#[test]
fn a_dual_license_expression_naming_mpl_is_not_the_pure_mpl_notice() {
    // The exact notice text is a prefix of this line; a plain substring
    // match would wrongly accept a different, dual-license expression as
    // the pure single-license notice this gate requires.
    assert_eq!(
        classify("// SPDX-License-Identifier: MPL-2.0 OR MIT\n"),
        Notice::OtherLicense
    );
}

#[test]
fn the_notice_text_quoted_mid_line_is_not_a_notice() {
    assert_eq!(
        classify("let x = \"SPDX-License-Identifier: MPL-2.0\";\n"),
        Notice::Missing
    );
    assert_eq!(
        classify("// see @generated markers in the sibling module\n"),
        Notice::Missing
    );
    // A line that IS the exact notice text is still not a real declaration
    // when it isn't itself a `//` comment -- e.g. one line of a multi-line
    // raw string literal that happens to hold that exact text.
    assert_eq!(
        classify("let s = r#\"\nSPDX-License-Identifier: MPL-2.0\n\"#;\n"),
        Notice::Missing
    );
    // The same, but the embedded line ALSO happens to start with `//` after
    // trimming (a fixture that itself contains comment-shaped text) --
    // still inside the raw string, so still not a real declaration.
    assert_eq!(
        classify("let s = r#\"\n// SPDX-License-Identifier: MPL-2.0\n\"#;\n"),
        Notice::Missing
    );
    assert_eq!(
        classify("let s = r#\"\n// @generated by nothing real\n\"#;\nfn f() {}\n"),
        Notice::Missing
    );
    // A raw string that opens and closes matters for hash-count matching:
    // an inner `"#` with the wrong hash count must not be treated as the
    // close, and a real notice AFTER the string genuinely closes is still
    // found.
    assert_eq!(
        classify(&format!(
            "let s = r##\"\n// {NOTICE}\n\"#\nstill inside\n\"##;\n{HEADER}"
        )),
        Notice::Present
    );
    // A raw string that opens AND closes on the SAME line must not leave
    // the tracker stuck "open" for the rest of the file -- a real notice
    // on a later line must still be found.
    assert_eq!(
        classify(&format!("let _ = r\"x\";\n{HEADER}")),
        Notice::Present
    );
    // A close immediately followed by another open on the same line must
    // pick up the second opener, not lose it.
    assert_eq!(
        classify("let _ = r\"a\"; let _ = r#\"\n// SPDX-License-Identifier: MPL-2.0\n\"#;\n"),
        Notice::Missing
    );
    // Byte and C raw-string prefix forms are recognized too, not just the
    // plain `r` form -- content-shaped text inside either must not count.
    assert_eq!(
        classify("let s = br#\"\n// SPDX-License-Identifier: MPL-2.0\n\"#;\n"),
        Notice::Missing
    );
    assert_eq!(
        classify("let s = cr#\"\n// SPDX-License-Identifier: MPL-2.0\n\"#;\n"),
        Notice::Missing
    );
    // A `//` line comment consumes the rest of ITS OWN line in real Rust,
    // so text after it that merely LOOKS like a raw-string opener (e.g.
    // documentation mentioning the syntax) must not be mistaken for a real
    // one -- doing so would make the tracker think a raw string is open
    // and hide a genuine notice on a later line, an ordinary false
    // negative on honest, well-commented code, not adversarial input.
    assert_eq!(
        classify(&format!("//! The raw-string opener is `r#\"`.\n{HEADER}")),
        Notice::Present
    );
    assert_eq!(
        classify("// see br#\"...\"# for byte raw strings\nfn f() {}\n"),
        Notice::Missing
    );
}

#[test]
fn notice_below_the_head_window_is_missing() {
    let text = format!("{}{HEADER}", "\n".repeat(HEAD_LINES));
    assert_eq!(classify(&text), Notice::Missing);
}

#[test]
fn globs_respect_segments() {
    assert!(glob_matches(
        "src/*_generated.rs",
        "src/opcode_generated.rs"
    ));
    assert!(!glob_matches(
        "src/*_generated.rs",
        "src/nested/opcode_generated.rs"
    ));
    assert!(glob_matches(
        "**/fixtures/**",
        "crates/a/tests/fixtures/x/y.rs"
    ));
    assert!(glob_matches("**/*.rs", "top.rs"));
    assert!(glob_matches("src/?.rs", "src/a.rs"));
    assert!(!glob_matches("src/?.rs", "src/ab.rs"));
}

#[test]
fn exclusion_manifest_requires_known_kind_and_reason() {
    let ok =
        "[[exclude]]\nglob = \"src/*_generated.rs\"\nkind = \"generated\"\nreason = \"build.rs\"\n";
    assert!(Exclusions::parse(ok).unwrap().matches("src/a_generated.rs"));

    let bad_kind = ok.replace("\"generated\"", "\"vendored\"");
    assert!(
        Exclusions::parse(&bad_kind)
            .unwrap_err()
            .contains("kind must be one of")
    );

    let empty_reason = ok.replace("\"build.rs\"", "\" \"");
    assert!(
        Exclusions::parse(&empty_reason)
            .unwrap_err()
            .contains("reason is empty")
    );

    let unknown_key = format!("{ok}owner = \"x\"\n");
    assert!(Exclusions::parse(&unknown_key).is_err());
}

#[test]
fn license_must_be_the_canonical_text() {
    let root = fixture("license");
    assert_eq!(
        license_problem(&root).as_deref(),
        Some("LICENSE is missing")
    );
    fs::write(root.join("LICENSE"), "Mozilla Public License Version 2.0\n").unwrap();
    assert_eq!(
        license_problem(&root).as_deref(),
        Some("LICENSE is not the canonical MPL-2.0 text")
    );
}

#[test]
fn package_license_file_must_be_canonical_text_not_merely_present() {
    let root = git_fixture("package-license");
    let canonical =
        fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/LICENSE")).expect("repo LICENSE exists");

    // A declared `license-file` key naming a missing target does not count.
    write(
        &root,
        "crates/declared-missing/Cargo.toml",
        "[package]\nname = \"declared-missing\"\nversion = \"0.1.0\"\nlicense-file = \"LICENSE\"\n",
    );

    // A declared `license-file` key naming a real but non-canonical file
    // does not count either -- the key existing is not the same as the
    // license text actually being there.
    write(
        &root,
        "crates/declared-wrong/Cargo.toml",
        "[package]\nname = \"declared-wrong\"\nversion = \"0.1.0\"\nlicense-file = \"LICENSE\"\n",
    );
    write(&root, "crates/declared-wrong/LICENSE", "not the MPL text\n");

    // A `LICENSE`-prefixed directory entry with the wrong content does not
    // satisfy the convention-based (no `license-file` key) path either.
    write(
        &root,
        "crates/conventional-wrong/Cargo.toml",
        "[package]\nname = \"conventional-wrong\"\nversion = \"0.1.0\"\n",
    );
    write(
        &root,
        "crates/conventional-wrong/LICENSE",
        "not the MPL text\n",
    );

    // The real, canonical byte-identical text satisfies both paths.
    write(
        &root,
        "crates/declared-real/Cargo.toml",
        "[package]\nname = \"declared-real\"\nversion = \"0.1.0\"\nlicense-file = \"LICENSE\"\n",
    );
    fs::write(root.join("crates/declared-real/LICENSE"), &canonical).unwrap();
    write(
        &root,
        "crates/conventional-real/Cargo.toml",
        "[package]\nname = \"conventional-real\"\nversion = \"0.1.0\"\n",
    );
    fs::write(root.join("crates/conventional-real/LICENSE"), &canonical).unwrap();

    let mut missing = packages_without_license(&root).unwrap();
    missing.sort();
    assert_eq!(
        missing,
        [
            "crates/conventional-wrong/Cargo.toml",
            "crates/declared-missing/Cargo.toml",
            "crates/declared-wrong/Cargo.toml",
        ]
    );
}

#[test]
fn publish_and_license_file_resolve_through_workspace_inheritance() {
    let root = git_fixture("workspace-inheritance");
    let canonical =
        fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/LICENSE")).expect("repo LICENSE exists");

    write(
        &root,
        "Cargo.toml",
        "[workspace]\nmembers = []\n\n\
         [workspace.package]\n\
         license-file = \"LICENSE\"\n\
         publish = false\n",
    );
    fs::write(root.join("LICENSE"), &canonical).unwrap();

    // `publish.workspace = true` inheriting `false` must be skipped exactly
    // like a direct `publish = false` -- not silently treated as publishable
    // because the value isn't a plain boolean in this package's own table.
    // This crate has no license text at all, so if inheritance were not
    // resolved it would wrongly appear as missing.
    write(
        &root,
        "crates/inherits-unpublished/Cargo.toml",
        "[package]\nname = \"inherits-unpublished\"\nversion = \"0.1.0\"\npublish.workspace = true\n",
    );

    // `license-file.workspace = true` resolves the workspace's declared
    // path relative to the WORKSPACE root, not this package's own
    // directory -- this crate carries no local LICENSE file at all, and is
    // itself publishable (default), so it must resolve through inheritance
    // to be recognized as carrying a license.
    write(
        &root,
        "crates/inherits-license/Cargo.toml",
        "[package]\nname = \"inherits-license\"\nversion = \"0.1.0\"\nlicense-file.workspace = true\n",
    );

    let missing = packages_without_license(&root).unwrap();
    assert_eq!(missing, Vec::<String>::new());
}

#[test]
fn license_file_workspace_inheritance_resolves_through_the_nearest_enclosing_workspace() {
    let root = git_fixture("nested-workspace");
    let canonical =
        fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/LICENSE")).expect("repo LICENSE exists");

    // The checkout root's own workspace declares an inherited path that
    // does NOT exist -- if this were (wrongly) used for a package under
    // crates/, it would be rejected.
    write(
        &root,
        "Cargo.toml",
        "[workspace]\nmembers = []\n\n[workspace.package]\nlicense-file = \"NOWHERE\"\n",
    );

    // A SEPARATE, real, nested workspace at crates/Cargo.toml (matching
    // this repository's own actual structure) declares its own inherited
    // path, which DOES exist relative to ITS root (crates/LICENSE, not the
    // checkout root's LICENSE).
    write(
        &root,
        "crates/Cargo.toml",
        "[workspace]\nmembers = [\"member\"]\n\n[workspace.package]\nlicense-file = \"LICENSE\"\n",
    );
    fs::write(root.join("crates/LICENSE"), &canonical).unwrap();
    write(
        &root,
        "crates/member/Cargo.toml",
        "[package]\nname = \"member\"\nversion = \"0.1.0\"\nlicense-file.workspace = true\n",
    );

    let missing = packages_without_license(&root).unwrap();
    assert_eq!(missing, Vec::<String>::new());
}

#[test]
fn an_explicit_package_workspace_override_takes_precedence_over_ancestor_discovery() {
    let root = git_fixture("workspace-override");
    let canonical =
        fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/LICENSE")).expect("repo LICENSE exists");

    // The nearest ANCESTOR workspace (what plain directory-walking would
    // find) declares an inherited path that does NOT exist -- if this were
    // used instead of the explicit override below, it would be rejected.
    write(
        &root,
        "crates/Cargo.toml",
        "[workspace]\nmembers = []\n\n[workspace.package]\nlicense-file = \"NOWHERE\"\n",
    );

    // The package explicitly names a DIFFERENT real workspace via
    // `workspace = "path"` (relative to the package's own directory),
    // matching Cargo's own override precedence -- this one's inherited
    // path does exist, relative to ITS root.
    write(
        &root,
        "elsewhere/Cargo.toml",
        "[workspace]\nmembers = []\n\n[workspace.package]\nlicense-file = \"LICENSE\"\n",
    );
    fs::write(root.join("elsewhere/LICENSE"), &canonical).unwrap();
    write(
        &root,
        "crates/member/Cargo.toml",
        "[package]\nname = \"member\"\nversion = \"0.1.0\"\nworkspace = \"../../elsewhere\"\nlicense-file.workspace = true\n",
    );

    let missing = packages_without_license(&root).unwrap();
    assert_eq!(missing, Vec::<String>::new());
}

#[test]
fn publish_array_and_missing_version_are_treated_as_unpublishable() {
    let root = git_fixture("publish-shapes");

    // No `version` at all: Cargo cannot publish this regardless of
    // `publish`'s value, so it is not checked -- carries no license and
    // must not appear as missing.
    write(
        &root,
        "crates/no-version/Cargo.toml",
        "[package]\nname = \"no-version\"\n",
    );

    // `publish = []` (no registries) is Cargo's other spelling of
    // unpublishable, distinct from the plain boolean form.
    write(
        &root,
        "crates/empty-registries/Cargo.toml",
        "[package]\nname = \"empty-registries\"\nversion = \"0.1.0\"\npublish = []\n",
    );

    // A non-empty registry list IS publishable (to that registry), so a
    // missing license here must still be reported.
    write(
        &root,
        "crates/named-registry/Cargo.toml",
        "[package]\nname = \"named-registry\"\nversion = \"0.1.0\"\npublish = [\"internal\"]\n",
    );

    let missing = packages_without_license(&root).unwrap();
    assert_eq!(missing, ["crates/named-registry/Cargo.toml"]);
}

#[test]
fn only_touched_files_fail_until_strict() {
    let root = git_fixture("touched");
    write(&root, "src/old.rs", "fn old() {}\n");
    write(
        &root,
        "src/headed.rs",
        &format!("{HEADER}fn headed() {{}}\n"),
    );
    commit(&root, "base");
    git(&root, &["branch", "base"]);

    write(&root, "src/new.rs", "fn new() {}\n");
    write(&root, "src/edited_generated.rs", "fn g() {}\n");
    write(
        &root,
        crate::license_gate::exclusions::MANIFEST,
        "[[exclude]]\nglob = \"src/*_generated.rs\"\nkind = \"generated\"\nreason = \"test\"\n",
    );
    write(
        &root,
        "crates/a/Cargo.toml",
        "[package]\nname = \"a\"\nversion = \"0.1.0\"\n",
    );
    write(
        &root,
        "crates/b/Cargo.toml",
        "[package]\nname = \"b\"\nversion = \"0.1.0\"\npublish = false\n",
    );

    let mut options = Options {
        root: root.clone(),
        base: "base".to_owned(),
        strict: false,
    };
    let report = check_license(&options).unwrap();
    assert_eq!(report.touched_missing, ["src/new.rs"]);
    assert_eq!(report.untouched_missing, ["src/old.rs"]);
    assert_eq!(report.excluded, 1);
    assert_eq!(report.packages_without_license, ["crates/a/Cargo.toml"]);
    // The fixture has no LICENSE, so layer 1 fails alongside the touched file.
    assert_eq!(report.failures(&options).len(), 2);

    options.strict = true;
    assert_eq!(report.failures(&options).len(), 4);
}

#[test]
fn unresolvable_base_is_an_error() {
    let root = git_fixture("base");
    write(&root, "src/lib.rs", "fn f() {}\n");
    commit(&root, "base");
    let options = Options {
        root,
        base: "no-such-ref".to_owned(),
        strict: false,
    };
    assert!(
        check_license(&options)
            .unwrap_err()
            .contains("cannot resolve --base")
    );
}

fn fixture(name: &str) -> PathBuf {
    let millis = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let root = std::env::temp_dir().join(format!(
        "sim-tooling-license-{name}-{}-{millis}",
        std::process::id()
    ));
    fs::create_dir_all(&root).unwrap();
    root
}

fn git_fixture(name: &str) -> PathBuf {
    let root = fixture(name);
    git(&root, &["init", "-q", "-b", "main"]);
    root
}

fn write(root: &Path, rel: &str, text: &str) {
    let path = root.join(rel);
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, text).unwrap();
}

fn commit(root: &Path, message: &str) {
    git(root, &["add", "-A"]);
    git(
        root,
        &[
            "-c",
            "user.name=fixture",
            "-c",
            "user.email=fixture@invalid",
            "commit",
            "-q",
            "-m",
            message,
        ],
    );
}

fn git(root: &Path, args: &[&str]) {
    let status = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(args)
        .status()
        .unwrap();
    assert!(status.success(), "git {args:?}");
}
