// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! What provenance records about execution and regeneration.
//!
//! `execution` records what actually produced the artifacts: the contract
//! operation, the encoder executable (package, version, a content digest of
//! its source tree and lock, and the lock digest, all fixed at build time),
//! the rustc and cargo that built it, and the validated shared resolver input
//! if one was used. Every field is a digest, a version, or a path relative to
//! the repository, so the record is identical on every machine.
//!
//! `regeneration_command` and `validation_commands` are the repository's
//! supported commands for the future, never guessed. A repository states them
//! in its root manifest:
//!
//! ```toml
//! [workspace.metadata.sim]
//! docs-command = "cargo run -p xtask -- simdoc"
//! validation-commands = ["cargo test", "cargo run -p xtask -- simdoc --check"]
//! ```
//!
//! Without `docs-command`, the regeneration command is the direct encoder
//! invocation from the repository root; without `validation-commands`, the
//! only validation command is that command with `--check`.

use std::{
    collections::BTreeSet,
    path::{Path, PathBuf},
};

use serde_json::{Value, json};

use crate::{
    content_digest::content_digest,
    resolver_input::{relative_path, resolver_projection},
};

const DOCS_COMMAND_KEY: &str = "docs-command";
const VALIDATION_COMMANDS_KEY: &str = "validation-commands";

/// The lock this encoder executable was built from; its digest names the
/// exact dependency identity that produced every generated byte.
const ENCODER_LOCK: &[u8] = include_bytes!("../../Cargo.lock");

/// The contract operation every route runs. The write, `--check`, and
/// `--emit` modes of every route produce identical bytes, so the mode is not
/// part of the record; otherwise `--check` could never match.
pub(crate) const CONTRACT_OPERATION: &str = "repo-contract --repo .";

/// The regeneration facts recorded in provenance.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct Regeneration {
    pub(crate) regeneration_command: String,
    pub(crate) validation_commands: Vec<String>,
}

/// Identity of the encoder executable, fixed when it was built.
pub(crate) fn executable_identity() -> Value {
    json!({
        "package": env!("CARGO_PKG_NAME"),
        "version": env!("CARGO_PKG_VERSION"),
        "source_sha256": env!("SIMDOC_SOURCE_SHA256"),
        "lock_sha256": content_digest(ENCODER_LOCK),
    })
}

/// The rustc and cargo that built the encoder (the pinned toolchain; the
/// build refuses any other).
pub(crate) fn toolchain_identity() -> Value {
    json!({
        "rustc": {
            "release": env!("SIMDOC_RUSTC_RELEASE"),
            "commit_hash": env!("SIMDOC_RUSTC_COMMIT"),
        },
        "cargo": {
            "release": env!("SIMDOC_CARGO_RELEASE"),
            "commit_hash": env!("SIMDOC_CARGO_COMMIT"),
        },
    })
}

/// What produced the artifacts for `repo`.
pub(crate) fn execution(repo: &Path) -> Result<Value, String> {
    Ok(json!({
        "operation": CONTRACT_OPERATION,
        "executable": executable_identity(),
        "toolchain": toolchain_identity(),
        "resolver": resolver_projection(repo)?,
    }))
}

/// Reads the repository's declared regeneration commands from the root
/// workspace metadata, falling back to the direct encoder invocation.
pub(crate) fn regeneration(repo: &Path, metadata: &Value) -> Result<Regeneration, String> {
    let declared = &metadata["metadata"]["sim"];
    let regeneration_command = match declared.get(DOCS_COMMAND_KEY) {
        Some(value) => command(value, DOCS_COMMAND_KEY)?,
        None => direct_encoder_command(repo, &encoder_manifest())?,
    };
    let validation_commands = match declared.get(VALIDATION_COMMANDS_KEY) {
        Some(value) => {
            let entries = value.as_array().ok_or_else(|| {
                format!("workspace.metadata.sim.{VALIDATION_COMMANDS_KEY} must be an array")
            })?;
            if entries.is_empty() {
                return Err(format!(
                    "workspace.metadata.sim.{VALIDATION_COMMANDS_KEY} must not be empty"
                ));
            }
            let mut seen = BTreeSet::new();
            let mut commands = Vec::new();
            for entry in entries {
                let command = command(entry, VALIDATION_COMMANDS_KEY)?;
                if !seen.insert(command.clone()) {
                    return Err(format!("validation command {command:?} is declared twice"));
                }
                commands.push(command);
            }
            commands
        }
        None => vec![format!("{regeneration_command} --check")],
    };
    Ok(Regeneration {
        regeneration_command,
        validation_commands,
    })
}

fn command(value: &Value, key: &str) -> Result<String, String> {
    let text = value
        .as_str()
        .ok_or_else(|| format!("workspace.metadata.sim.{key} entries must be strings"))?;
    if text.trim().is_empty()
        || text.trim() != text
        || !text.bytes().all(|byte| (b' '..=b'~').contains(&byte))
    {
        return Err(format!(
            "workspace.metadata.sim.{key} command {text:?} must be one trimmed line of printable ASCII"
        ));
    }
    Ok(text.to_owned())
}

fn encoder_manifest() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml")
}

/// The direct invocation of this encoder from `repo`'s root, naming the
/// encoder manifest by its path relative to that root.
pub(crate) fn direct_encoder_command(repo: &Path, manifest: &Path) -> Result<String, String> {
    let repo = repo
        .canonicalize()
        .map_err(|err| format!("{}: {err}", repo.display()))?;
    let manifest = manifest
        .canonicalize()
        .map_err(|err| format!("encoder manifest {}: {err}", manifest.display()))?;
    let relative = relative_path(&repo, &manifest)?;
    if !relative
        .bytes()
        .all(|byte| byte.is_ascii_graphic() && byte != b'\\')
    {
        return Err(format!(
            "encoder manifest path {relative:?} cannot be recorded as a command argument"
        ));
    }
    Ok(format!(
        "cargo run --locked --manifest-path {relative} -- simdoc"
    ))
}

#[cfg(test)]
#[path = "regeneration_tests.rs"]
mod tests;
