// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! What provenance records about the generator and about regeneration: the
//! exact encoder identity, the command that regenerates the documentation, and
//! the validation commands the repository itself supports.
//!
//! Commands are never guessed. A repository states them in its root manifest:
//!
//! ```toml
//! [workspace.metadata.sim]
//! docs-command = "cargo run -p xtask -- simdoc"
//! validation-commands = ["cargo test", "cargo run -p xtask -- simdoc --check"]
//! ```
//!
//! Without `docs-command`, the recorded command is the direct encoder
//! invocation from the repository root; without `validation-commands`, the
//! only recorded validation command is that command with `--check`.

use std::{
    collections::BTreeSet,
    path::{Component, Path, PathBuf},
};

use serde_json::{Value, json};

use crate::content_digest::content_digest;

const DOCS_COMMAND_KEY: &str = "docs-command";
const VALIDATION_COMMANDS_KEY: &str = "validation-commands";

/// The lock this encoder executable was built from; its digest names the
/// exact dependency identity that produced every generated byte.
const ENCODER_LOCK: &[u8] = include_bytes!("../../Cargo.lock");

/// The regeneration facts recorded in provenance.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct Regeneration {
    pub(crate) docs_command: String,
    pub(crate) validation_commands: Vec<String>,
}

/// Identity of the encoder that produced the artifacts: package, version, and
/// the SHA-256 of the lock it was built from.
pub(crate) fn encoder_identity() -> Value {
    json!({
        "package": env!("CARGO_PKG_NAME"),
        "version": env!("CARGO_PKG_VERSION"),
        "lock_sha256": content_digest(ENCODER_LOCK),
    })
}

/// Reads the repository's declared regeneration commands from the root
/// workspace metadata, falling back to the direct encoder invocation.
pub(crate) fn regeneration(repo: &Path, metadata: &Value) -> Result<Regeneration, String> {
    let declared = &metadata["metadata"]["sim"];
    let docs_command = match declared.get(DOCS_COMMAND_KEY) {
        Some(value) => command(value, DOCS_COMMAND_KEY)?,
        None => direct_encoder_command(repo, &encoder_manifest())?,
    };
    let validation_commands = match declared.get(VALIDATION_COMMANDS_KEY) {
        Some(value) => {
            let entries = value.as_array().ok_or_else(|| {
                format!("workspace.metadata.sim.{VALIDATION_COMMANDS_KEY} must be an array")
            })?;
            if entries.is_empty() {
                return Err(format!(
                    "workspace.metadata.sim.{VALIDATION_COMMANDS_KEY} must not be empty"
                ));
            }
            let mut seen = BTreeSet::new();
            let mut commands = Vec::new();
            for entry in entries {
                let command = command(entry, VALIDATION_COMMANDS_KEY)?;
                if !seen.insert(command.clone()) {
                    return Err(format!("validation command {command:?} is declared twice"));
                }
                commands.push(command);
            }
            commands
        }
        None => vec![format!("{docs_command} --check")],
    };
    Ok(Regeneration {
        docs_command,
        validation_commands,
    })
}

fn command(value: &Value, key: &str) -> Result<String, String> {
    let text = value
        .as_str()
        .ok_or_else(|| format!("workspace.metadata.sim.{key} entries must be strings"))?;
    if text.trim().is_empty()
        || text.trim() != text
        || !text.bytes().all(|byte| (b' '..=b'~').contains(&byte))
    {
        return Err(format!(
            "workspace.metadata.sim.{key} command {text:?} must be one trimmed line of printable ASCII"
        ));
    }
    Ok(text.to_owned())
}

fn encoder_manifest() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml")
}

/// The direct invocation of this encoder from `repo`'s root, naming the
/// encoder manifest by its path relative to that root.
pub(crate) fn direct_encoder_command(repo: &Path, manifest: &Path) -> Result<String, String> {
    let repo = repo
        .canonicalize()
        .map_err(|err| format!("{}: {err}", repo.display()))?;
    let manifest = manifest
        .canonicalize()
        .map_err(|err| format!("encoder manifest {}: {err}", manifest.display()))?;
    let relative = relative_path(&repo, &manifest)?;
    if !relative
        .bytes()
        .all(|byte| byte.is_ascii_graphic() && byte != b'\\')
    {
        return Err(format!(
            "encoder manifest path {relative:?} cannot be recorded as a command argument"
        ));
    }
    Ok(format!(
        "cargo run --locked --manifest-path {relative} -- simdoc"
    ))
}

fn relative_path(from: &Path, to: &Path) -> Result<String, String> {
    let from = normal_components(from)?;
    let to = normal_components(to)?;
    let shared = from
        .iter()
        .zip(&to)
        .take_while(|(left, right)| left == right)
        .count();
    let mut parts = vec![".."; from.len() - shared];
    parts.extend(to[shared..].iter().map(String::as_str));
    Ok(parts.join("/"))
}

fn normal_components(path: &Path) -> Result<Vec<String>, String> {
    path.components()
        .filter(|component| !matches!(component, Component::RootDir))
        .map(|component| match component {
            Component::Normal(part) => part
                .to_str()
                .map(str::to_owned)
                .ok_or_else(|| format!("{} is not UTF-8", path.display())),
            _ => Err(format!("{} is not a canonical path", path.display())),
        })
        .collect()
}

#[cfg(test)]
#[path = "regeneration_tests.rs"]
mod tests;
