// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! The crate-catalog task: generate or check crate metadata, READMEs, and the
//! crate catalog for exactly the packages the repo contract covers. It runs
//! inside the locked contract engine; xtask's `crate-catalog` route runs this
//! executable.

use std::{
    collections::BTreeSet,
    io,
    path::{Path, PathBuf},
};

use serde_json::{Value, json};

use crate::crate_catalog_manifest::ensure_package_metadata;

const GENERATED_MARKER: &str = "<!-- GENERATED BY xtask crate-catalog; DO NOT EDIT. -->";
const GENERATOR: &str = "xtask crate-catalog v1";

/// Summary of a `crate-catalog` run.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(crate) struct CrateCatalogReport {
    /// Names of the catalogued packages, in catalog order.
    pub package_names: Vec<String>,
    /// Number of workspace packages inspected.
    pub packages: usize,
    /// Number of `Cargo.toml` manifests updated.
    pub manifests_changed: usize,
    /// Number of `README.md` files updated.
    pub readmes_changed: usize,
    /// Number of generated catalog files updated.
    pub catalogs_changed: usize,
}

#[derive(Debug)]
struct PackageEntry {
    name: String,
    manifest_rel: String,
    root_rel: String,
    description: String,
    publish: String,
    readme_rel: String,
    target_kinds: Vec<String>,
    docs_summary: String,
    generated_readme: bool,
}

/// Runs `crate-catalog [--check] [--repo <path>]`; `args[1]` is the
/// subcommand name.
pub(crate) fn run(args: &[String]) -> Result<(), String> {
    let options = crate::generator_options::parse_repo_tool_args(args, "crate-catalog")?;
    let report = crate_catalog(options.check, Some(options.repo))?;
    if options.check {
        println!("crate-catalog: metadata and generated files are current");
    } else {
        println!(
            "crate-catalog: {} package(s), {} manifest(s), {} readme(s), {} catalog file(s)",
            report.packages,
            report.manifests_changed,
            report.readmes_changed,
            report.catalogs_changed
        );
    }
    Ok(())
}

/// Generates crate metadata, READMEs, and the crate catalog for the current
/// repository; with `check` true it instead verifies they are current and
/// fails when they are stale. Returns the run summary.
pub(crate) fn crate_catalog(
    check: bool,
    repo_override: Option<PathBuf>,
) -> Result<CrateCatalogReport, String> {
    let repo = match repo_override {
        // An explicit repo root (used by the control-plane fleet gate to run
        // against a sibling public repo, which has no AGENTS.md of its own).
        Some(path) => path.canonicalize().map_err(display_io)?,
        None => find_repo_root(&std::env::current_dir().map_err(display_io)?)?,
    };
    let scope = crate::owned::enter(&repo)?;
    // The catalog covers exactly the repo contract's packages, discovered and
    // classified by the same engine that writes the contract.
    let metadata = crate::repo_contract::cargo_metadata(&repo)?;
    let mut entries = workspace_packages(&repo, &metadata)?;
    let mut report = CrateCatalogReport {
        packages: entries.len(),
        package_names: entries.iter().map(|entry| entry.name.clone()).collect(),
        ..CrateCatalogReport::default()
    };

    for entry in &mut entries {
        sync_manifest(&repo, entry, check, &mut report)?;
        sync_readme(&repo, entry, check, &mut report)?;
    }

    sync_catalogs(&repo, &entries, check, &mut report)?;
    scope.finish()?;
    Ok(report)
}

fn workspace_packages(repo: &Path, metadata: &Value) -> Result<Vec<PackageEntry>, String> {
    let member_ids = metadata["workspace_members"]
        .as_array()
        .ok_or("cargo metadata missing workspace_members")?
        .iter()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    let packages = metadata["packages"]
        .as_array()
        .ok_or("cargo metadata missing packages")?;
    let mut entries = Vec::new();

    for package in packages {
        let Some(id) = package["id"].as_str() else {
            continue;
        };
        if !member_ids.contains(id) {
            continue;
        }
        let name = package["name"]
            .as_str()
            .ok_or("cargo metadata package missing name")?
            .to_owned();
        let manifest = PathBuf::from(
            package["manifest_path"]
                .as_str()
                .ok_or("cargo metadata package missing manifest_path")?,
        );
        let root = manifest
            .parent()
            .ok_or_else(|| format!("manifest has no parent: {}", manifest.display()))?
            .to_path_buf();
        let target_kinds = target_kinds(package);
        let docs_summary = package_docs_summary(package).unwrap_or_else(|| generic_summary(&name));
        let description = package["description"]
            .as_str()
            .map(clean_summary)
            .filter(|summary| !summary.is_empty())
            .unwrap_or_else(|| docs_summary.clone());
        let publish = match &package["publish"] {
            Value::Array(registries) if registries.is_empty() => "false",
            Value::Array(_) => "restricted",
            Value::Null => "true",
            _ => "unknown",
        }
        .to_owned();
        let root_rel = rel_path(repo, &root)?;
        let readme_rel = if root_rel == "." {
            "README.md".to_owned()
        } else {
            format!("{root_rel}/README.md")
        };
        entries.push(PackageEntry {
            name,
            manifest_rel: rel_path(repo, &manifest)?,
            root_rel,
            description,
            publish,
            readme_rel,
            target_kinds,
            docs_summary,
            generated_readme: false,
        });
    }

    entries.sort_by(|left, right| left.manifest_rel.cmp(&right.manifest_rel));
    Ok(entries)
}

fn sync_manifest(
    repo: &Path,
    entry: &PackageEntry,
    check: bool,
    report: &mut CrateCatalogReport,
) -> Result<(), String> {
    let path = repo.join(&entry.manifest_rel);
    let text = crate::owned::read_to_string(&path).map_err(display_io)?;
    let expected = ensure_package_metadata(&text, &entry.description);
    crate::publication::guard(repo, &entry.manifest_rel, &expected)?;
    if expected == text {
        return Ok(());
    }
    if check {
        return Err(format!(
            "{} is missing generated package metadata; run `cargo run -p xtask -- crate-catalog`",
            entry.manifest_rel
        ));
    }
    crate::publication::write(repo, &path, &expected)?;
    report.manifests_changed += 1;
    Ok(())
}

fn sync_readme(
    repo: &Path,
    entry: &mut PackageEntry,
    check: bool,
    report: &mut CrateCatalogReport,
) -> Result<(), String> {
    let path = repo.join(&entry.readme_rel);
    if let Ok(existing) = crate::owned::read_to_string(&path) {
        if !existing.contains(GENERATED_MARKER) {
            entry.generated_readme = false;
            return Ok(());
        }
        entry.generated_readme = true;
        let expected = generated_readme(entry);
        crate::publication::guard(repo, &entry.readme_rel, &expected)?;
        if expected == existing {
            return Ok(());
        }
        if check {
            return Err(format!(
                "{} is stale; run `cargo run -p xtask -- crate-catalog`",
                entry.readme_rel
            ));
        }
        crate::publication::write(repo, &path, &expected)?;
        report.readmes_changed += 1;
        return Ok(());
    }

    if check {
        return Err(format!(
            "{} is missing; run `cargo run -p xtask -- crate-catalog`",
            entry.readme_rel
        ));
    }
    crate::publication::write(repo, &path, &generated_readme(entry))?;
    entry.generated_readme = true;
    report.readmes_changed += 1;
    Ok(())
}

fn sync_catalogs(
    repo: &Path,
    entries: &[PackageEntry],
    check: bool,
    report: &mut CrateCatalogReport,
) -> Result<(), String> {
    let generated_dir = repo.join("docs/generated");
    let json_path = generated_dir.join("crate-catalog.json");
    let md_path = generated_dir.join("crate-catalog.md");
    write_or_check(repo, &json_path, &catalog_json(entries)?, check, report)?;
    write_or_check(repo, &md_path, &catalog_markdown(entries), check, report)?;
    Ok(())
}

fn write_or_check(
    repo: &Path,
    path: &Path,
    expected: &str,
    check: bool,
    report: &mut CrateCatalogReport,
) -> Result<(), String> {
    let name = path
        .strip_prefix(repo)
        .unwrap_or(path)
        .display()
        .to_string();
    crate::publication::guard(repo, &name, expected)?;
    crate::publication::ensure_ordinary_target(repo, path)?;
    let current = crate::owned::read_to_string(path).unwrap_or_default();
    if current == expected {
        return Ok(());
    }
    if check {
        return Err(format!(
            "{} is stale; run `cargo run -p xtask -- crate-catalog`",
            path.display()
        ));
    }
    crate::publication::write(repo, path, expected)?;
    report.catalogs_changed += 1;
    Ok(())
}

fn target_kinds(package: &Value) -> Vec<String> {
    let mut kinds = BTreeSet::new();
    if let Some(targets) = package["targets"].as_array() {
        for target in targets {
            if let Some(target_kinds) = target["kind"].as_array() {
                for kind in target_kinds {
                    if let Some(kind) = kind.as_str() {
                        kinds.insert(kind.to_owned());
                    }
                }
            }
        }
    }
    kinds.into_iter().collect()
}

fn package_docs_summary(package: &Value) -> Option<String> {
    let target = preferred_doc_target(package)?;
    let path = PathBuf::from(target["src_path"].as_str()?);
    let text = crate::owned::read_to_string(path).ok()?;
    let docs = crate_docs(&text);
    let summary = summary_from_docs(&docs);
    (!summary.is_empty()).then_some(summary)
}

fn preferred_doc_target(package: &Value) -> Option<&Value> {
    let targets = package["targets"].as_array()?;
    targets
        .iter()
        .find(|target| target_kind_contains(target, "lib"))
        .or_else(|| {
            targets
                .iter()
                .find(|target| target_kind_contains(target, "bin"))
        })
        .or_else(|| targets.first())
}

fn target_kind_contains(target: &Value, needle: &str) -> bool {
    target["kind"]
        .as_array()
        .is_some_and(|kinds| kinds.iter().any(|kind| kind.as_str() == Some(needle)))
}

fn crate_docs(text: &str) -> String {
    let mut docs = Vec::new();
    let mut started = false;
    for line in text.lines() {
        let trimmed = line.trim_start();
        if let Some(doc) = trimmed.strip_prefix("//!") {
            started = true;
            docs.push(doc.trim_start().to_owned());
            continue;
        }
        if trimmed.starts_with("#!") || trimmed.is_empty() {
            if started && trimmed.is_empty() {
                docs.push(String::new());
            }
            continue;
        }
        if started {
            break;
        }
        if trimmed.starts_with("//") {
            continue;
        }
        break;
    }
    docs.join("\n")
}

fn summary_from_docs(docs: &str) -> String {
    let paragraph = docs
        .split("\n\n")
        .map(str::trim)
        .find(|paragraph| !paragraph.is_empty())
        .unwrap_or_default();
    clean_summary(paragraph)
}

fn clean_summary(input: &str) -> String {
    let mut text = input
        .lines()
        .map(str::trim)
        .filter(|line| !line.starts_with('#'))
        .collect::<Vec<_>>()
        .join(" ");
    for (from, to) in [("`", ""), ("**", ""), ("[", ""), ("]", "")] {
        text = text.replace(from, to);
    }
    text = text
        .chars()
        .map(|ch| if ch.is_ascii() { ch } else { ' ' })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ");
    if text.is_empty() {
        return String::new();
    }
    if text.len() > 180 {
        text.truncate(177);
        text.push_str("...");
    }
    text.trim_matches('.').to_owned() + "."
}

fn generic_summary(name: &str) -> String {
    format!("SIM workspace package for {}.", name.replace('-', " "))
}

fn generated_readme(entry: &PackageEntry) -> String {
    let targets = if entry.target_kinds.is_empty() {
        "none".to_owned()
    } else {
        entry.target_kinds.join(", ")
    };
    format!(
        "# {name}\n\n{marker}\n\n{description}\n\n## Package Metadata\n\n- Manifest: `{manifest}`\n- Publish: `{publish}`\n- Targets: `{targets}`\n\n## Crate Documentation\n\n{docs}\n",
        name = entry.name,
        marker = GENERATED_MARKER,
        description = entry.description,
        manifest = entry.manifest_rel,
        publish = entry.publish,
        targets = targets,
        docs = entry.docs_summary,
    )
}

fn catalog_json(entries: &[PackageEntry]) -> Result<String, String> {
    let packages = entries
        .iter()
        .map(|entry| {
            json!({
                "name": entry.name,
                "manifest": entry.manifest_rel,
                "root": entry.root_rel,
                "description": entry.description,
                "publish": entry.publish,
                "readme": entry.readme_rel,
                "generated_readme": entry.generated_readme,
                "target_kinds": entry.target_kinds,
            })
        })
        .collect::<Vec<_>>();
    let value = json!({
        "generator": GENERATOR,
        "package_count": entries.len(),
        "packages": packages,
    });
    crate::json_render::pretty(value, "crate catalog json")
}

fn catalog_markdown(entries: &[PackageEntry]) -> String {
    let mut out = format!(
        "# Crate Catalog\n\n{GENERATED_MARKER}\n\nGenerated from Cargo metadata by `{GENERATOR}`.\n\n| Package | Publish | Targets | Description |\n| --- | --- | --- | --- |\n"
    );
    for entry in entries {
        let targets = if entry.target_kinds.is_empty() {
            "none".to_owned()
        } else {
            entry.target_kinds.join(", ")
        };
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} |\n",
            entry.name,
            entry.publish,
            targets,
            markdown_cell(&entry.description)
        ));
    }
    out
}

fn markdown_cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn rel_path(repo: &Path, path: &Path) -> Result<String, String> {
    let rel = path
        .strip_prefix(repo)
        .map_err(|err| format!("make relative path for {}: {err}", path.display()))?;
    let text = rel
        .to_string_lossy()
        .replace(std::path::MAIN_SEPARATOR, "/");
    if text.is_empty() {
        Ok(".".to_owned())
    } else {
        Ok(text)
    }
}

fn find_repo_root(start: &Path) -> Result<PathBuf, String> {
    for dir in start.ancestors() {
        if dir.join("Cargo.toml").is_file() && dir.join("AGENTS.md").is_file() {
            return Ok(dir.to_path_buf());
        }
    }
    Err(format!("could not find repo root from {}", start.display()))
}

fn display_io(err: io::Error) -> String {
    err.to_string()
}

#[cfg(test)]
mod tests {
    use serde_json::Value;

    use super::*;
    use crate::test_fixture::FixtureRepo;

    #[test]
    fn nested_contract_packages_are_catalogued() {
        let repo = FixtureRepo::nested("catalog-nested");

        crate_catalog(false, Some(repo.path().to_path_buf())).unwrap();
        let catalog: Value =
            serde_json::from_str(&repo.read("docs/generated/crate-catalog.json")).unwrap();

        let manifests = catalog["packages"]
            .as_array()
            .unwrap()
            .iter()
            .map(|package| package["manifest"].as_str().unwrap().to_owned())
            .collect::<Vec<_>>();
        assert_eq!(manifests, ["Cargo.toml", "nested/tool/Cargo.toml"]);
        assert!(
            repo.read("nested/tool/README.md")
                .contains(GENERATED_MARKER)
        );
        assert!(crate_catalog(true, Some(repo.path().to_path_buf())).is_ok());
    }

    #[test]
    fn a_catalog_that_would_publish_an_outside_path_is_refused() {
        let repo = FixtureRepo::nested("catalog-outside-path");
        let local = repo.path().parent().unwrap().to_string_lossy().into_owned();
        repo.write(
            "nested/tool/Cargo.toml",
            &repo
                .read("nested/tool/Cargo.toml")
                .replace("Fixture tool.", &format!("Built in {local}.")),
        );
        repo.commit();

        let err = crate_catalog(false, Some(repo.path().to_path_buf())).unwrap_err();
        assert!(err.contains("refused to publish"), "{err}");
        assert!(
            !repo
                .path()
                .join("docs/generated/crate-catalog.json")
                .exists()
        );
    }
}
