// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use std::{
    os::unix::fs::symlink,
    process::{Command, Stdio},
    time::{SystemTime, UNIX_EPOCH},
};

use super::*;

// conformance: no generated byte records a location outside the repository.

fn repo_root(label: &str) -> std::path::PathBuf {
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let root = env::temp_dir()
        .join(format!("{label}-{}-{stamp}", std::process::id()))
        .join("sim-fixture");
    fs::create_dir_all(&root).unwrap();
    let status = Command::new("git")
        .args(["init", "--quiet"])
        .current_dir(&root)
        .stdout(Stdio::null())
        .status()
        .unwrap();
    assert!(status.success());
    root.canonicalize().unwrap()
}

#[test]
fn repository_relative_content_is_published() {
    let repo = Path::new("/work/constellation/sim-fixture");
    for (name, content) in [
        (
            "provenance.json",
            r#"{"api_docs":"target/doc/","manifest":"crates/a/Cargo.toml"}"#,
        ),
        (
            "repo-contract.md",
            "see `src/lib.rs` and https://github.com/sim-nest/sim-fixture/tree/main",
        ),
        ("README.md", "a / b and and/or, `//` comments, ratio 1/2"),
    ] {
        guard(repo, name, content).unwrap();
    }
}

#[test]
fn any_local_or_embedded_outside_path_is_refused() {
    let repo = Path::new("/work/constellation/sim-fixture");
    for (name, content) in [
        (
            "provenance.json",
            r#"{"manifest":"../sim-private/.meta-workspace/Cargo.toml"}"#,
        ),
        (
            "provenance.json",
            r#"{"resolver":{"manifest":"/opt/meta/Cargo.toml"}}"#,
        ),
        (
            "repo-contract.json",
            r#"{"packages":[{"src":"crates/../../x.rs"}]}"#,
        ),
        ("repo-contract.json", r#"{"home":"~/cache"}"#),
        (
            "repo-contract.md",
            "built in /work/constellation/sim-private",
        ),
        (
            "sim-index-fragment.sx",
            "(unit /work/constellation/sim-fixture/src)",
        ),
        ("crate-catalog.md", "Built from /srv/private/x."),
        ("README.md", "cache at ~/.cargo/registry"),
        ("README.md", "copied from C:\\Users\\bo\\sim"),
        ("README.md", "share \\\\build-host\\drop"),
        (
            "validation-matrix.md",
            "`cargo check --manifest-path /srv/x/Cargo.toml`",
        ),
    ] {
        let err = guard(repo, name, content).unwrap_err();
        assert!(err.contains(name), "{content}: {err}");
    }
}

#[test]
fn a_path_already_in_consumed_repository_content_may_be_quoted() {
    let repo = repo_root("publication-consumed");
    fs::write(
        repo.join("tests.rs"),
        "assert!(parse(\"/tmp/sim-demo\").is_err());\n",
    )
    .unwrap();
    let scope = crate::owned::enter(&repo).unwrap();
    assert!(guard(&repo, "README.md", "`/tmp/sim-demo`").is_err());
    crate::owned::read_to_string(repo.join("tests.rs")).unwrap();
    guard(&repo, "README.md", "`/tmp/sim-demo`").unwrap();
    assert!(guard(&repo, "README.md", "`/tmp/other`").is_err());
    scope.finish().unwrap();
    fs::remove_dir_all(repo.parent().unwrap()).unwrap();
}

#[test]
fn writes_never_follow_a_symlink() {
    let repo = repo_root("publication-write");
    let outside = repo.parent().unwrap().join("outside");
    fs::create_dir_all(&outside).unwrap();
    symlink(&outside, repo.join("docs")).unwrap();
    symlink(outside.join("x.md"), repo.join("linked.md")).unwrap();
    let scope = crate::owned::enter(&repo).unwrap();

    let err = write(&repo, &repo.join("docs/generated/a.md"), "ok").unwrap_err();
    assert!(err.contains("is a symlink"), "{err}");
    let err = write(&repo, &repo.join("linked.md"), "ok").unwrap_err();
    assert!(err.contains("is a symlink"), "{err}");
    write(&repo, &repo.join("plain/a.md"), "ok").unwrap();
    assert_eq!(fs::read_to_string(repo.join("plain/a.md")).unwrap(), "ok");
    assert!(!outside.join("generated").exists());
    scope.finish().unwrap();
    fs::remove_dir_all(repo.parent().unwrap()).unwrap();
}

#[test]
fn path_tokens_find_unix_windows_and_home_paths_but_not_urls() {
    assert_eq!(
        path_tokens("a /srv/x/y, `C:\\Users\\a` \"~/.cargo/x\" https://h/p/q (\\\\h\\s)"),
        ["/srv/x/y", "C:\\Users\\a", "~/.cargo/x", "\\\\h\\s"]
    );
    assert!(path_tokens("src/lib.rs a/b /single // x").is_empty());
}
