// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! The one publication guard (AGENTS.md R2): every generated byte passes it
//! before it is written, checked, or emitted.
//!
//! Generated files are published with the repository, so nothing local to the
//! machine that produced them may appear. Content is refused when it contains
//!
//! - a location of the machine that ran the generator: the repository, its
//!   parent, the home, working, temporary, Cargo, or rustup directory, or the
//!   shared resolver's directory, anywhere;
//! - an embedded absolute Unix path, Windows drive or UNC path, or
//!   home-relative path, unless the whole path is one of the exact reviewed
//!   values in [`PUBLIC_LITERALS`]. There are no permitted prefixes, roots, or
//!   patterns: `/tmp/anything`, `/var/anything`, `/etc/anything` are as
//!   refused as `/srv/anything`. A path that occurs in a file the run read is
//!   never permitted by that fact: permission comes from this table alone, so
//!   no repository content, tracked or not, can approve a path;
//! - a path with a `..` segment;
//! - in JSON, any string value that is itself a non-public absolute path, a
//!   home-relative path, or a parent-escaping path.
//!
//! Every write goes to an ordinary file inside the repository reached without
//! passing through a symlink.

use std::{
    collections::BTreeMap,
    env, fs,
    path::{Component, Path},
};

use serde_json::Value;

/// Reviewed exact public paths: documented values that name no machine (a
/// sandbox or test-filesystem location, a vendor library path, a documented
/// Windows example). Adding an entry is a reviewed code change; a path that is
/// not listed is refused, whatever its first segment.
pub(crate) const PUBLIC_LITERALS: &[&str] = &[
    "/bin/sh",
    "/bin/sleep",
    "/dev/urandom",
    "/etc/os-release",
    "/opt/viture/libviture_sdk.so",
    "/proc/cpuinfo",
    "/proc/meminfo",
    "/scratch/home",
    "/scratch/target",
    "/scratch/tmp",
    "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor",
    "/target/x86_64-unknown-linux-gnu/debug/",
    "/target/x86_64-unknown-linux-gnu/debug/{filename}",
    "/toolchain/bin",
    "/toolchain/bin:/usr/bin:/bin",
    "/toolchain/bin/rustc",
    "/toolchain/bin/rustdoc",
    "/usr/bin/bwrap",
    "/usr/bin/gcc",
    "/usr/bin/prlimit",
    "file:///source",
    "file:///etc/passwd",
    "C:/SIM-Index",
    "C:\\SIM\\Workspace",
    "D:\\escape",
];

/// First segments that name a machine or a person, never publishable whatever
/// the table says (a test proves the table holds none).
#[cfg(test)]
pub(crate) const NEVER_PUBLIC_ROOTS: &[&str] = &[
    "home", "Users", "root", "srv", "mnt", "media", "private", "Volumes", "snap", "nix", "tmp",
    "var", "run",
];

/// Refuses `content`, to be published as `name`, when it would record
/// anything local to this machine.
pub(crate) fn guard(repo: &Path, name: &str, content: &str) -> Result<(), String> {
    for location in local_locations(repo) {
        if content.contains(location.as_str()) {
            return Err(format!(
                "refused to publish {name}: it records the local path {location}; nothing \
                 outside the repository may be recorded by path"
            ));
        }
    }
    if let Some(url) = file_urls(content)
        .into_iter()
        .find(|url| !PUBLIC_LITERALS.contains(&url.as_str()))
    {
        return Err(format!(
            "refused to publish {name}: it embeds the `file:` URL {url:?}, which names a \
             location on some machine and is not a reviewed public literal"
        ));
    }
    if let Some(token) = path_tokens(content)
        .into_iter()
        .find(|token| !is_public_path(token))
    {
        return Err(format!(
            "refused to publish {name}: it embeds the path {token:?}, which is not a reviewed \
             public path; nothing outside the repository may be recorded by path (a reviewed \
             exact literal is added in simdoc's publication.rs)"
        ));
    }
    if name.ends_with(".json") {
        let value: Value = serde_json::from_str(content)
            .map_err(|err| format!("parse generated {name}: {err}"))?;
        if let Some(path) = outside_json_path(&value) {
            return Err(format!(
                "refused to publish {name}: it records {path:?}, a path outside the repository"
            ));
        }
    }
    Ok(())
}

/// Every `file:` URL in `text`, from the scheme to the next delimiter.
fn file_urls(text: &str) -> Vec<String> {
    let lower = text.to_ascii_lowercase();
    let mut urls = Vec::new();
    let mut from = 0;
    while let Some(found) = lower[from..].find("file:/") {
        let start = from + found;
        let end = text[start..]
            .find(|ch: char| ch.is_whitespace() || "\"'`)|<>".contains(ch))
            .map_or(text.len(), |offset| start + offset);
        urls.push(text[start..end].to_owned());
        from = end.max(start + 1);
    }
    urls
}

/// Whether `token`, an absolute or home-relative path found in text, may be
/// published: it has no `..` segment and is exactly a reviewed literal.
pub(crate) fn is_public_path(token: &str) -> bool {
    if token.split(['/', '\\']).any(|segment| segment == "..") {
        return false;
    }
    PUBLIC_LITERALS.contains(&token)
}

/// Guards every artifact of a set.
pub(crate) fn guard_all(repo: &Path, files: &BTreeMap<&'static str, String>) -> Result<(), String> {
    files
        .iter()
        .try_for_each(|(name, content)| guard(repo, name, content))
}

/// Writes guarded `content` to `path` inside `repo`, creating parents, and
/// refusing a target or parent reached through a symlink.
pub(crate) fn write(repo: &Path, path: &Path, content: &str) -> Result<(), String> {
    let name = path
        .strip_prefix(repo)
        .unwrap_or(path)
        .display()
        .to_string();
    guard(repo, &name, content)?;
    ensure_ordinary_target(repo, path)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|err| format!("create {}: {err}", parent.display()))?;
    }
    ensure_ordinary_target(repo, path)?;
    fs::write(path, content).map_err(|err| format!("write {}: {err}", path.display()))
}

/// Requires `path` to lie lexically inside `repo` with no existing component
/// that is a symlink, and to be absent or an ordinary file.
pub(crate) fn ensure_ordinary_target(repo: &Path, path: &Path) -> Result<(), String> {
    let relative = path
        .strip_prefix(repo)
        .ok()
        .filter(|relative| {
            relative
                .components()
                .all(|component| matches!(component, Component::Normal(_)))
        })
        .ok_or_else(|| {
            format!(
                "refused to write {}: outside the repository",
                path.display()
            )
        })?;
    let mut current = repo.to_path_buf();
    for component in relative.components() {
        current.push(component);
        match fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(format!(
                    "refused to write {}: {} is a symlink",
                    path.display(),
                    current.display()
                ));
            }
            Ok(metadata) if current == path && !metadata.is_file() => {
                return Err(format!(
                    "refused to write {}: not an ordinary file",
                    path.display()
                ));
            }
            Ok(_) => {}
            Err(_) => break,
        }
    }
    Ok(())
}

fn local_locations(repo: &Path) -> Vec<String> {
    let mut locations = vec![repo.to_string_lossy().into_owned()];
    if let Some(parent) = repo.parent().filter(|parent| parent.parent().is_some()) {
        locations.push(parent.to_string_lossy().into_owned());
    }
    let mut named = vec![env::temp_dir()];
    named.extend(env::current_dir().ok());
    for variable in [
        "HOME",
        "CARGO_HOME",
        "RUSTUP_HOME",
        crate::resolver_input::RESOLVER_ENV,
    ] {
        if let Some(value) = env::var_os(variable) {
            let path = Path::new(&value);
            // The resolver variable names a manifest; its directory is local.
            named.push(if variable == crate::resolver_input::RESOLVER_ENV {
                path.parent().map(Path::to_path_buf).unwrap_or_default()
            } else {
                path.to_path_buf()
            });
        }
    }
    for path in named {
        // A location with a single segment (`/`, `/tmp`) names no machine.
        if path
            .components()
            .filter(|part| matches!(part, Component::Normal(_)))
            .count()
            >= 2
        {
            locations.push(path.to_string_lossy().into_owned());
        }
    }
    locations.sort();
    locations.dedup();
    locations
}

/// Path candidates in `text`, read conservatively: from a candidate start
/// (an absolute `/`, a home-relative `~/`, a shell variable path such as
/// `$HOME/x` or `${X}/y`, a Windows drive or UNC path) at a word boundary, to
/// the next whitespace or quote, closing bracket, `<`, `>`, `,`, `;` or `|`.
/// Everything between is part of the candidate, whatever it is: Unicode,
/// `$`, braces, `%`, `*`. A candidate is published only when it exactly equals
/// a reviewed literal, so a private name cannot hide behind a character the
/// scanner did not expect. An absolute candidate needs two segments
/// (`/single` and `and/or` are prose).
pub(crate) fn path_tokens(text: &str) -> Vec<&str> {
    let mut tokens = Vec::new();
    let mut previous: Option<char> = None;
    let mut chars = text.char_indices().peekable();
    while let Some((index, ch)) = chars.next() {
        let boundary = previous.is_none_or(is_boundary);
        previous = Some(ch);
        if !boundary {
            continue;
        }
        let rest = &text[index..];
        let mut next = rest.chars().skip(1);
        let second = next.next();
        let third = next.next();
        let candidate = match ch {
            '/' if second.is_some_and(|c| !is_delimiter(c) && c != '/') => Some(true),
            '~' if second == Some('/') => Some(true),
            '$' if second.is_some_and(|c| c == '{' || c == '_' || c.is_alphabetic()) => Some(false),
            '\\' if second == Some('\\') && third.is_some_and(char::is_alphanumeric) => Some(false),
            c if c.is_ascii_alphabetic()
                && second == Some(':')
                && third.is_some_and(|c| c == '\\' || c == '/') =>
            {
                Some(false)
            }
            _ => None,
        };
        let Some(needs_segments) = candidate else {
            continue;
        };
        let end = rest.find(is_delimiter).unwrap_or(rest.len());
        // Trailing sentence punctuation and the backslashes of an escaped
        // closing quote are not part of the path.
        let token = rest[..end].trim_end_matches(['.', ':', ';', '?', '!', '\\']);
        let segments = token
            .trim_start_matches('~')
            .split(['/', '\\'])
            .filter(|segment| !segment.is_empty())
            .count();
        let keep = if needs_segments {
            segments >= 2
        } else if ch == '$' {
            token.contains('/')
        } else {
            token.chars().nth(3).is_some()
        };
        if keep && !token.is_empty() {
            tokens.push(token);
            // Resume after the candidate so its interior is not rescanned.
            while chars.peek().is_some_and(|(at, _)| *at < index + end) {
                chars.next();
            }
            previous = Some('x');
        }
    }
    tokens
}

/// Whether `c` ends a path candidate.
fn is_delimiter(c: char) -> bool {
    c.is_whitespace() || "\"'`)]<>,;|".contains(c)
}

/// Whether a candidate may start right after `c`.
fn is_boundary(c: char) -> bool {
    c.is_whitespace() || "\"'([<=,`{>|".contains(c)
}

fn outside_json_path(value: &Value) -> Option<&str> {
    match value {
        Value::String(text) => is_outside_path(text).then_some(text.as_str()),
        Value::Array(items) => items.iter().find_map(outside_json_path),
        Value::Object(fields) => fields.values().find_map(outside_json_path),
        _ => None,
    }
}

fn is_outside_path(text: &str) -> bool {
    if text.starts_with('/') {
        return !is_public_path(text);
    }
    text.starts_with("~/")
        || text == ".."
        || text.starts_with("../")
        || text.contains("/../")
        || text.ends_with("/..")
        || text.starts_with("\\\\")
        || (text.len() > 2 && text.as_bytes()[1] == b':' && text.as_bytes()[2] == b'\\')
}

#[cfg(test)]
#[path = "publication_tests.rs"]
mod tests;
