// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use std::{
    os::unix::fs::symlink,
    process::{Command, Stdio},
    time::{SystemTime, UNIX_EPOCH},
};

use super::*;

// conformance: no generated byte records a location outside the repository.

fn git(dir: &Path, args: &[&str]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(dir)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .unwrap();
    assert!(status.success());
}

fn repo_root(label: &str) -> std::path::PathBuf {
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let root = env::temp_dir()
        .join(format!("{label}-{}-{stamp}", std::process::id()))
        .join("sim-fixture");
    fs::create_dir_all(&root).unwrap();
    let status = Command::new("git")
        .args(["init", "--quiet"])
        .current_dir(&root)
        .stdout(Stdio::null())
        .status()
        .unwrap();
    assert!(status.success());
    root.canonicalize().unwrap()
}

#[test]
fn repository_relative_content_is_published() {
    let repo = Path::new("/work/constellation/sim-fixture");
    for (name, content) in [
        (
            "provenance.json",
            r#"{"api_docs":"target/doc/","manifest":"crates/a/Cargo.toml"}"#,
        ),
        (
            "repo-contract.md",
            "see `src/lib.rs` and https://github.com/sim-nest/sim-fixture/tree/main",
        ),
        ("README.md", "a / b and and/or, `//` comments, ratio 1/2"),
    ] {
        guard(repo, name, content).unwrap();
    }
}

#[test]
fn any_local_or_embedded_outside_path_is_refused() {
    let repo = Path::new("/work/constellation/sim-fixture");
    for (name, content) in [
        (
            "provenance.json",
            r#"{"manifest":"../sim-private/.meta-workspace/Cargo.toml"}"#,
        ),
        (
            "provenance.json",
            r#"{"resolver":{"manifest":"/opt/meta/Cargo.toml"}}"#,
        ),
        (
            "repo-contract.json",
            r#"{"packages":[{"src":"crates/../../x.rs"}]}"#,
        ),
        ("repo-contract.json", r#"{"home":"~/cache"}"#),
        (
            "repo-contract.md",
            "built in /work/constellation/sim-private",
        ),
        (
            "sim-index-fragment.sx",
            "(unit /work/constellation/sim-fixture/src)",
        ),
        ("crate-catalog.md", "Built from /srv/private/x."),
        ("README.md", "cache at ~/.cargo/registry"),
        ("README.md", "copied from C:\\Users\\bo\\sim"),
        ("README.md", "share \\\\build-host\\drop"),
        (
            "validation-matrix.md",
            "`cargo check --manifest-path /srv/x/Cargo.toml`",
        ),
    ] {
        let err = guard(repo, name, content).unwrap_err();
        assert!(err.contains(name), "{content}: {err}");
    }
}

#[test]
fn no_repository_content_can_approve_a_path_it_contains() {
    // Neither a tracked nor an untracked file's text makes a path publishable:
    // permission comes only from the reviewed table.
    let repo = repo_root("publication-consumed");
    fs::write(
        repo.join("features.toml"),
        "summary = \"see /srv/private/customer for the data\"\n",
    )
    .unwrap();
    fs::write(
        repo.join("tests.rs"),
        "assert!(parse(\"/tmp/sim-demo\"));\n",
    )
    .unwrap();
    fs::write(repo.join("quote.md"), "in /srv/quoted/place\n").unwrap();
    git(&repo, &["add", "tests.rs", "quote.md"]);
    let scope = crate::owned::enter(&repo).unwrap();

    crate::owned::read_to_string(repo.join("tests.rs")).unwrap();
    assert!(crate::owned::read_to_string(repo.join("features.toml")).is_err());
    let err = guard(&repo, "README.md", "data lives in /srv/private/customer").unwrap_err();
    assert!(err.contains("/srv/private/customer"), "{err}");
    // A tracked file quoting a path outside the table is not enough either.
    crate::owned::read_to_string(repo.join("quote.md")).unwrap();
    assert!(guard(&repo, "README.md", "`/srv/quoted/place`").is_err());
    // Even a file's own quoted path stays refused; only the table admits.
    assert!(guard(&repo, "README.md", "`/tmp/sim-demo`").is_err());
    guard(&repo, "README.md", "`/scratch/tmp`").unwrap();

    assert!(scope.finish().is_err(), "the untracked read is refused");
    fs::remove_dir_all(repo.parent().unwrap()).unwrap();
}

#[test]
fn only_exact_reviewed_literals_are_public() {
    let repo = Path::new("/work/constellation/sim-fixture");
    for literal in PUBLIC_LITERALS {
        assert!(is_public_path(literal), "{literal}");
        guard(repo, "README.md", &format!("see `{literal}` here")).unwrap();
        // A literal is exact: never a prefix of something longer.
        if literal.starts_with('/') {
            assert!(!is_public_path(&format!("{literal}/x")), "{literal}");
            assert!(!is_public_path(&format!("{literal}-secret")), "{literal}");
        }
    }
    // No root, prefix, or pattern is public: every one of these is a
    // machine-local or free-form location.
    for path in [
        "/tmp/customer-secret",
        "/tmp/sim-demo",
        "/var/lib/private-job",
        "/var/runner-4711/work",
        "/etc/passwd",
        "/run/user/1000/bus",
        "/usr/local/private/tool",
        "/proc/self/environ",
        "/dev/null",
        "/v1/models",
        "/srv/private/customer",
        "/home/bo/x",
        "/Users/bo/x",
        "/opt/meta/Cargo.toml",
        "/opt/viture/other.so",
        "/unreviewed/route",
        "/scratch/tmp/../etc",
        "/tmp/../etc/passwd",
        "~/.cargo/registry",
        "C:/Users/bo/x",
    ] {
        assert!(!is_public_path(path), "{path}");
        assert!(
            guard(repo, "README.md", &format!("`{path}`")).is_err(),
            "{path}"
        );
    }
    for literal in PUBLIC_LITERALS {
        let root = literal.trim_start_matches('/').split('/').next().unwrap();
        assert!(
            !NEVER_PUBLIC_ROOTS.contains(&root),
            "{literal} names a machine"
        );
    }
}

#[test]
fn a_file_url_or_slash_drive_path_is_a_path_too() {
    let repo = Path::new("/work/constellation/sim-fixture");
    for content in [
        "see file:///srv/private/x",
        "at FILE:///tmp/customer-secret",
        "open file:/etc/passwd",
        "copied from C:/Users/bo/sim",
        "d:/private/x",
    ] {
        assert!(guard(repo, "README.md", content).is_err(), "{content}");
    }
    guard(
        repo,
        "README.md",
        "https://github.com/sim-nest/sim-tooling and a:b",
    )
    .unwrap();
}

#[test]
fn json_string_values_follow_the_same_table() {
    let repo = Path::new("/work/constellation/sim-fixture");
    guard(repo, "index.json", r#"{"probe":"/scratch/tmp"}"#).unwrap();
    for value in [
        "/srv/private/x",
        "/tmp/customer-secret",
        "/var/runner-1",
        "/single",
        "~/x",
        "../x",
        "a/../b",
    ] {
        let content = format!(r#"{{"path":"{value}"}}"#);
        assert!(guard(repo, "index.json", &content).is_err(), "{value}");
    }
}

#[test]
fn every_machine_local_location_is_refused_anywhere() {
    let repo = Path::new("/work/constellation/sim-fixture");
    let cwd = env::current_dir().unwrap();
    for location in [cwd.as_path(), Path::new("/work/constellation")] {
        let content = format!("built in {}", location.display());
        assert!(guard(repo, "README.md", &content).is_err(), "{content}");
    }
}

#[test]
fn writes_never_follow_a_symlink() {
    let repo = repo_root("publication-write");
    let outside = repo.parent().unwrap().join("outside");
    fs::create_dir_all(&outside).unwrap();
    symlink(&outside, repo.join("docs")).unwrap();
    symlink(outside.join("x.md"), repo.join("linked.md")).unwrap();
    let scope = crate::owned::enter(&repo).unwrap();

    let err = write(&repo, &repo.join("docs/generated/a.md"), "ok").unwrap_err();
    assert!(err.contains("is a symlink"), "{err}");
    let err = write(&repo, &repo.join("linked.md"), "ok").unwrap_err();
    assert!(err.contains("is a symlink"), "{err}");
    write(&repo, &repo.join("plain/a.md"), "ok").unwrap();
    assert_eq!(fs::read_to_string(repo.join("plain/a.md")).unwrap(), "ok");
    assert!(!outside.join("generated").exists());
    scope.finish().unwrap();
    fs::remove_dir_all(repo.parent().unwrap()).unwrap();
}

#[test]
fn path_tokens_find_unix_windows_and_home_paths_but_not_urls() {
    assert_eq!(
        path_tokens("a /srv/x/y, `C:\\Users\\a` \"~/.cargo/x\" https://h/p/q (\\\\h\\s)"),
        ["/srv/x/y", "C:\\Users\\a", "~/.cargo/x", "\\\\h\\s"]
    );
    assert!(path_tokens("src/lib.rs a/b /single // x").is_empty());
}

/// A candidate runs through every character up to a delimiter, so a private
/// path cannot hide behind Unicode, a shell variable, or punctuation, and it
/// is published only when the whole candidate is a reviewed literal.
#[test]
fn a_candidate_is_the_whole_run_through_unicode_and_shell_punctuation() {
    let repo = Path::new("/work/constellation/sim-fixture");
    for (text, whole) in [
        ("see /tmp/\u{79d8}\u{5bc6} here", "/tmp/\u{79d8}\u{5bc6}"),
        ("`/tmp/$SECRET`", "/tmp/$SECRET"),
        ("in /tmp/${SECRET}/x now", "/tmp/${SECRET}/x"),
        ("at /var/run/\u{1f512}/k.", "/var/run/\u{1f512}/k"),
        ("cd $HOME/secret/x", "$HOME/secret/x"),
        ("cd ${SECRET_DIR}/x", "${SECRET_DIR}/x"),
        ("at ~/\u{79d8}/x", "~/\u{79d8}/x"),
        ("at /\u{79d8}/x", "/\u{79d8}/x"),
        ("=/opt/caf\u{e9}/bin/x", "/opt/caf\u{e9}/bin/x"),
        ("/tmp/a%20b/c*d", "/tmp/a%20b/c*d"),
        ("C:\\Users\\\u{79d8}\\x", "C:\\Users\\\u{79d8}\\x"),
    ] {
        assert_eq!(path_tokens(text), [whole], "{text}");
        assert!(guard(repo, "README.md", text).is_err(), "{text}");
    }
    // A reviewed literal followed by more is a different, unreviewed path.
    for text in ["/proc/cpuinfo\u{79d8}", "/proc/cpuinfo$X", "/proc/cpuinfo*"] {
        assert!(guard(repo, "README.md", text).is_err(), "{text}");
    }
    guard(
        repo,
        "README.md",
        "reads `/proc/cpuinfo`, then /proc/meminfo.",
    )
    .unwrap();
    // The escaped quotes of a rendered string literal are not part of the path.
    guard(repo, "README.md", "(x \"\\\"/etc/os-release\\\"\")").unwrap();
    assert!(guard(repo, "README.md", "/proc/cpuinfo\\secret").is_err());
    guard(
        repo,
        "README.md",
        "plain prose, a/b, and/or, 50/50, https://x.io/a/b",
    )
    .unwrap();
}
