// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! The one publication guard (AGENTS.md R2): every generated byte passes it
//! before it is written, checked, or emitted.
//!
//! Generated files are published with the repository, so nothing local to the
//! machine that produced them may appear. Content is refused when it contains
//!
//! - the repository's absolute location, its parent directory, or the home
//!   directory, anywhere;
//! - an embedded absolute Unix path, Windows drive or UNC path, or
//!   home-relative path, unless that exact path already occurs in repository
//!   content the run consumed through [`crate::owned`] (so quoting committed
//!   source is fine, and nothing new is introduced);
//! - in JSON, any string value that is itself an absolute, home-relative, or
//!   parent-escaping path.
//!
//! Every write goes to an ordinary file inside the repository reached without
//! passing through a symlink.

use std::{
    collections::BTreeMap,
    env, fs,
    path::{Component, Path},
};

use serde_json::Value;

/// Refuses `content`, to be published as `name`, when it would record
/// anything local to this machine.
pub(crate) fn guard(repo: &Path, name: &str, content: &str) -> Result<(), String> {
    for location in local_locations(repo) {
        if content.contains(location.as_str()) {
            return Err(format!(
                "refused to publish {name}: it records the local path {location}; nothing \
                 outside the repository may be recorded by path"
            ));
        }
    }
    if let Some(token) = path_tokens(content)
        .into_iter()
        .find(|token| !crate::owned::consumed_path(token))
    {
        return Err(format!(
            "refused to publish {name}: it embeds the path {token:?}, which no consumed \
             repository file contains; nothing outside the repository may be recorded by path"
        ));
    }
    if name.ends_with(".json") {
        let value: Value = serde_json::from_str(content)
            .map_err(|err| format!("parse generated {name}: {err}"))?;
        if let Some(path) = outside_json_path(&value) {
            return Err(format!(
                "refused to publish {name}: it records {path:?}, a path outside the repository"
            ));
        }
    }
    Ok(())
}

/// Guards every artifact of a set.
pub(crate) fn guard_all(repo: &Path, files: &BTreeMap<&'static str, String>) -> Result<(), String> {
    files
        .iter()
        .try_for_each(|(name, content)| guard(repo, name, content))
}

/// Writes guarded `content` to `path` inside `repo`, creating parents, and
/// refusing a target or parent reached through a symlink.
pub(crate) fn write(repo: &Path, path: &Path, content: &str) -> Result<(), String> {
    let name = path
        .strip_prefix(repo)
        .unwrap_or(path)
        .display()
        .to_string();
    guard(repo, &name, content)?;
    ensure_ordinary_target(repo, path)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|err| format!("create {}: {err}", parent.display()))?;
    }
    ensure_ordinary_target(repo, path)?;
    fs::write(path, content).map_err(|err| format!("write {}: {err}", path.display()))
}

/// Requires `path` to lie lexically inside `repo` with no existing component
/// that is a symlink, and to be absent or an ordinary file.
pub(crate) fn ensure_ordinary_target(repo: &Path, path: &Path) -> Result<(), String> {
    let relative = path
        .strip_prefix(repo)
        .ok()
        .filter(|relative| {
            relative
                .components()
                .all(|component| matches!(component, Component::Normal(_)))
        })
        .ok_or_else(|| {
            format!(
                "refused to write {}: outside the repository",
                path.display()
            )
        })?;
    let mut current = repo.to_path_buf();
    for component in relative.components() {
        current.push(component);
        match fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(format!(
                    "refused to write {}: {} is a symlink",
                    path.display(),
                    current.display()
                ));
            }
            Ok(metadata) if current == path && !metadata.is_file() => {
                return Err(format!(
                    "refused to write {}: not an ordinary file",
                    path.display()
                ));
            }
            Ok(_) => {}
            Err(_) => break,
        }
    }
    Ok(())
}

fn local_locations(repo: &Path) -> Vec<String> {
    let mut locations = vec![repo.to_string_lossy().into_owned()];
    if let Some(parent) = repo.parent().filter(|parent| parent.parent().is_some()) {
        locations.push(parent.to_string_lossy().into_owned());
    }
    if let Some(home) = env::var_os("HOME").filter(|home| home.len() > 1) {
        locations.push(Path::new(&home).to_string_lossy().into_owned());
    }
    locations
}

/// Absolute Unix paths (two or more segments), Windows drive and UNC paths,
/// and home-relative paths embedded in `text`.
pub(crate) fn path_tokens(text: &str) -> Vec<&str> {
    let bytes = text.as_bytes();
    let mut tokens = Vec::new();
    let mut index = 0;
    while index < bytes.len() {
        let boundary = index == 0 || is_boundary(bytes[index - 1]);
        if !boundary {
            index += 1;
            continue;
        }
        let rest = &bytes[index..];
        let length = if rest.first() == Some(&b'/') && rest.get(1).is_some_and(|b| is_path_byte(*b))
        {
            unix_length(rest)
        } else if rest.starts_with(b"~/") {
            unix_length(&rest[1..]).map(|length| length + 1)
        } else if (rest.len() > 3
            && rest[0].is_ascii_alphabetic()
            && rest[1] == b':'
            && rest[2] == b'\\'
            && rest[3].is_ascii_alphanumeric())
            || (rest.starts_with(b"\\\\") && rest.get(2).is_some_and(u8::is_ascii_alphanumeric))
        {
            Some(windows_length(rest))
        } else {
            None
        };
        match length {
            Some(length) => {
                let token = text[index..index + length].trim_end_matches(['.', ':', ';']);
                if !token.is_empty() {
                    tokens.push(token);
                }
                index += length.max(1);
            }
            None => index += 1,
        }
    }
    tokens
}

/// Length of an absolute Unix path at the start of `bytes`, when it has at
/// least two non-empty segments.
fn unix_length(bytes: &[u8]) -> Option<usize> {
    let length = bytes
        .iter()
        .position(|byte| !(is_path_byte(*byte) || *byte == b'/'))
        .unwrap_or(bytes.len());
    let segments = bytes[..length]
        .split(|byte| *byte == b'/')
        .filter(|segment| !segment.is_empty())
        .count();
    (segments >= 2 && bytes.get(1) != Some(&b'/')).then_some(length)
}

fn windows_length(bytes: &[u8]) -> usize {
    bytes
        .iter()
        .position(|byte| byte.is_ascii_whitespace() || b"\"'`)|<>".contains(byte))
        .unwrap_or(bytes.len())
}

fn is_path_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || b"._-~+@%".contains(&byte)
}

fn is_boundary(byte: u8) -> bool {
    byte.is_ascii_whitespace() || b"\"'([<=,`{>|".contains(&byte)
}

fn outside_json_path(value: &Value) -> Option<&str> {
    match value {
        Value::String(text) => is_outside_path(text).then_some(text.as_str()),
        Value::Array(items) => items.iter().find_map(outside_json_path),
        Value::Object(fields) => fields.values().find_map(outside_json_path),
        _ => None,
    }
}

fn is_outside_path(text: &str) -> bool {
    text.starts_with('/')
        || text.starts_with("~/")
        || text == ".."
        || text.starts_with("../")
        || text.contains("/../")
        || text.ends_with("/..")
        || text.starts_with("\\\\")
        || (text.len() > 2 && text.as_bytes()[1] == b':' && text.as_bytes()[2] == b'\\')
}

#[cfg(test)]
#[path = "publication_tests.rs"]
mod tests;
