// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! The validation-matrix task: generate or check the validation matrix for
//! every package the repo contract covers. Packages of a declared nested
//! contract workspace are checked through that workspace's manifest. It runs
//! inside the locked contract engine; xtask's `validation-matrix` route runs
//! this executable.

use std::{collections::BTreeSet, io, path::Path};

use serde_json::Value;

use crate::{
    repo_contract::{ContractPackages, contract_packages, workspace_package_names},
    repo_contract_cut::{SplitCut, load_or_derive_split_cut},
};

const GENERATED_MARKER: &str = "<!-- GENERATED BY xtask validation-matrix; DO NOT EDIT. -->";
const GENERATOR: &str = "xtask validation-matrix v1";
const OUTPUT: &str = "docs/generated/validation-matrix.md";

/// Summary of a `validation-matrix` run.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(crate) struct ValidationMatrixReport {
    /// Number of validation-matrix rows produced.
    pub rows: usize,
    /// Number of generated matrix artifacts updated.
    pub artifacts_changed: usize,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum MatrixMode {
    Normal,
    Slow,
}

#[derive(Clone, Debug)]
struct MatrixRow {
    id: String,
    mode: MatrixMode,
    scope: &'static str,
    subject: String,
    command: String,
    purpose: String,
}

/// Runs `validation-matrix [--check] [--repo <path>]`; `args[1]` is the
/// subcommand name.
pub(crate) fn run(args: &[String]) -> Result<(), String> {
    let options = crate::generator_options::parse_repo_tool_args(args, "validation-matrix")?;
    let report = validation_matrix_for_repo(options.check, &options.repo)?;
    if options.check {
        println!("validation-matrix: generated matrix is current");
    } else {
        println!(
            "validation-matrix: {} row(s), {} artifact(s) changed",
            report.rows, report.artifacts_changed
        );
    }
    Ok(())
}

pub(crate) fn validation_matrix_for_repo(
    check: bool,
    repo: &Path,
) -> Result<ValidationMatrixReport, String> {
    let repo = &repo.canonicalize().map_err(display_io)?;
    let scope = crate::owned::enter(repo)?;
    let contract = contract_packages(repo)?;
    let cut = load_or_derive_split_cut(repo, &workspace_package_names(&contract.metadata)?)?;
    let rows = matrix_rows(repo, &contract, &cut)?;
    let content = render_matrix(&rows, &cut);

    let mut report = ValidationMatrixReport {
        rows: rows.len(),
        artifacts_changed: 0,
    };
    let path = repo.join(OUTPUT);
    crate::publication::guard(repo, OUTPUT, &content)?;
    crate::publication::ensure_ordinary_target(repo, &path)?;
    write_or_check(repo, &path, &content, check, &mut report)?;
    scope.finish()?;
    Ok(report)
}

fn matrix_rows(
    repo: &Path,
    contract: &ContractPackages,
    cut: &SplitCut,
) -> Result<Vec<MatrixRow>, String> {
    let mut rows = workspace_rows(&contract.declared);
    rows.extend(package_feature_rows(contract)?);
    rows.extend(group_rows(contract, cut)?);
    rows.extend(slow_rows(repo));
    Ok(rows)
}

/// `cargo check` scoped to the workspace that owns a package.
fn check_command(workspace: Option<&str>) -> String {
    match workspace {
        Some(root) => format!("cargo check --manifest-path {root}/Cargo.toml"),
        None => "cargo check".to_owned(),
    }
}

fn workspace_rows(declared: &[String]) -> Vec<MatrixRow> {
    let mut rows = vec![MatrixRow {
        id: "workspace-check".to_owned(),
        mode: MatrixMode::Normal,
        scope: "workspace",
        subject: "workspace".to_owned(),
        command: "cargo check --workspace".to_owned(),
        purpose: "Every workspace member compiles with its default feature set.".to_owned(),
    }];
    for root in declared {
        rows.push(MatrixRow {
            id: format!("workspace-check-{}", root.replace('/', "-")),
            mode: MatrixMode::Normal,
            scope: "workspace",
            subject: root.clone(),
            command: format!("{} --workspace", check_command(Some(root))),
            purpose: format!(
                "Every member of the `{root}` contract workspace compiles with its default feature set."
            ),
        });
    }
    rows
}

fn package_feature_rows(contract: &ContractPackages) -> Result<Vec<MatrixRow>, String> {
    let mut rows = Vec::new();
    for package in member_packages(&contract.metadata)? {
        let features = package_features(package);
        if features.is_empty() {
            continue;
        }
        let name = package["name"]
            .as_str()
            .ok_or("cargo metadata package missing name")?;
        let check = check_command(contract.workspace_of(package));
        rows.push(MatrixRow {
            id: format!("package-{name}-no-default"),
            mode: MatrixMode::Normal,
            scope: "package-feature",
            subject: format!("{name} no default features"),
            command: format!("{check} -p {name} --no-default-features"),
            purpose: format!("Package `{name}` compiles with default features disabled."),
        });
        rows.push(MatrixRow {
            id: format!("package-{name}-all-features"),
            mode: MatrixMode::Normal,
            scope: "package-feature",
            subject: format!("{name} all features"),
            command: format!("{check} -p {name} --all-features"),
            purpose: format!("Package `{name}` compiles with every declared feature enabled."),
        });
    }
    Ok(rows)
}

fn group_rows(contract: &ContractPackages, cut: &SplitCut) -> Result<Vec<MatrixRow>, String> {
    let packages = member_packages(&contract.metadata)?;
    let names = packages
        .iter()
        .filter_map(|package| package["name"].as_str())
        .collect::<BTreeSet<_>>();
    let mut rows = Vec::new();
    for group in &cut.group_order {
        let group_packages = cut
            .groups
            .get(group)
            .ok_or_else(|| format!("split cut group {group} has no package list"))?;
        let package = representative_package(group, group_packages)
            .ok_or_else(|| format!("split cut group {group} has no package representative"))?;
        if !names.contains(package) {
            return Err(format!(
                "split cut representative {package} for group {group} is not a workspace package"
            ));
        }
        let workspace = packages
            .iter()
            .find(|candidate| candidate["name"].as_str() == Some(package))
            .and_then(|candidate| contract.workspace_of(candidate));
        rows.push(MatrixRow {
            id: format!("group-{group}"),
            mode: MatrixMode::Normal,
            scope: "split-group",
            subject: group.clone(),
            command: format!("{} -p {package}", check_command(workspace)),
            purpose: format!("Representative package `{package}` for repository group `{group}`."),
        });
    }
    Ok(rows)
}

fn representative_package<'a>(group: &str, packages: &'a [String]) -> Option<&'a str> {
    if group == "sdk" {
        return packages
            .iter()
            .find(|package| package.as_str() == "sim-server")
            .or_else(|| packages.first())
            .map(String::as_str);
    }
    packages.first().map(String::as_str)
}

fn slow_rows(repo: &Path) -> Vec<MatrixRow> {
    let mut rows = vec![MatrixRow {
        id: "slow-benches".to_owned(),
        mode: MatrixMode::Slow,
        scope: "slow",
        subject: "benches".to_owned(),
        command: "cargo check --benches --all-features".to_owned(),
        purpose: "Bench targets compile under the full feature closure.".to_owned(),
    }];
    if repo.join("fuzz/Cargo.toml").is_file() {
        rows.push(MatrixRow {
            id: "slow-fuzz-compile".to_owned(),
            mode: MatrixMode::Slow,
            scope: "slow",
            subject: "fuzz compile".to_owned(),
            command: "cargo check --manifest-path fuzz/Cargo.toml".to_owned(),
            purpose: "Fuzz harnesses compile; long-running fuzz campaigns remain operator-run."
                .to_owned(),
        });
    }
    rows
}

fn render_matrix(rows: &[MatrixRow], cut: &SplitCut) -> String {
    let normal_count = rows
        .iter()
        .filter(|row| row.mode == MatrixMode::Normal)
        .count();
    let slow_count = rows.len() - normal_count;
    let mut out =
        format!("# Validation Matrix\n\n{GENERATED_MARKER}\n\nGenerated by `{GENERATOR}`.\n\n");
    out.push_str(&format!(
        "- Normal rows: {normal_count}\n- Slow rows: {slow_count}\n- Split groups: {}\n\n",
        cut.group_order.len()
    ));
    out.push_str("Normal rows are the fast local validation surface for this repository. ");
    out.push_str("Slow rows extend that surface with targets that are useful before release or broad refactors. ");
    out.push_str("Long-running fuzz execution campaigns are intentionally excluded because they need operator-selected durations and corpora.\n\n");
    out.push_str("| ID | Mode | Scope | Subject | Command | Purpose |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- |\n");
    for row in rows {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` | {} |\n",
            row.id,
            row.mode.as_str(),
            row.scope,
            markdown_cell(&row.subject),
            markdown_cell(&row.command),
            markdown_cell(&row.purpose)
        ));
    }
    out
}

impl MatrixMode {
    fn as_str(self) -> &'static str {
        match self {
            MatrixMode::Normal => "normal",
            MatrixMode::Slow => "slow",
        }
    }
}

fn member_packages(metadata: &Value) -> Result<Vec<&Value>, String> {
    let member_ids = metadata["workspace_members"]
        .as_array()
        .ok_or("cargo metadata missing workspace_members")?
        .iter()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    Ok(metadata["packages"]
        .as_array()
        .ok_or("cargo metadata missing packages")?
        .iter()
        .filter(|package| {
            package["id"]
                .as_str()
                .is_some_and(|id| member_ids.contains(id))
        })
        .collect())
}

fn package_features(package: &Value) -> BTreeSet<String> {
    package["features"]
        .as_object()
        .into_iter()
        .flat_map(|features| features.keys())
        .cloned()
        .collect()
}

fn write_or_check(
    repo: &Path,
    path: &Path,
    content: &str,
    check: bool,
    report: &mut ValidationMatrixReport,
) -> Result<(), String> {
    match crate::owned::read_to_string(path) {
        Ok(existing) if existing == content => Ok(()),
        Ok(_) | Err(_) if check => Err(format!(
            "{} is stale; run cargo run -p xtask -- validation-matrix",
            path.display()
        )),
        Ok(_) | Err(_) => {
            crate::publication::write(repo, path, content)?;
            report.artifacts_changed += 1;
            Ok(())
        }
    }
}

fn markdown_cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn display_io(err: io::Error) -> String {
    err.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_fixture::FixtureRepo;

    #[test]
    fn nested_contract_packages_are_checked_through_their_workspace() {
        let repo = FixtureRepo::nested("matrix-nested");

        validation_matrix_for_repo(false, repo.path()).unwrap();
        let matrix = repo.read(OUTPUT);

        for command in [
            "cargo check --workspace",
            "cargo check --manifest-path nested/Cargo.toml --workspace",
            "cargo check --manifest-path nested/Cargo.toml -p tool --no-default-features",
            "cargo check --manifest-path nested/Cargo.toml -p tool --all-features",
            "cargo check -p app",
        ] {
            assert!(
                matrix.contains(&format!("`{command}`")),
                "{command}\n{matrix}"
            );
        }
        assert!(validation_matrix_for_repo(true, repo.path()).is_ok());
    }
}
