//! Single documentation encoder over the build-side Card spine.

use crate::{Card, CardSpine};

/// Documentation output positions.
///
/// Each position maps the same Card spine to one committed documentation lane.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum DocPosition {
    /// `docs/agents/cards.jsonl`.
    AgentCards,
    /// `docs/agents/card-index.json` and `docs/generated/card-index.json`.
    CardIndex,
    /// `docs/humans/README.md`.
    HumanReadme,
    /// `docs/generated/repo-contract.json`.
    RepoContract,
}

/// The documentation encoder for Card-backed generated lanes.
///
/// The encoder projects one Card spine into the concrete lane selected by
/// [`DocPosition`]. Byte-for-byte parity with the committed lane format is a
/// tested invariant.
pub struct DocEncoder;

impl DocEncoder {
    /// Encodes `spine` at `position` into committed lane bytes.
    pub fn encode(&self, spine: &CardSpine, position: DocPosition) -> String {
        match position {
            DocPosition::AgentCards => agent_cards(spine),
            DocPosition::CardIndex => card_index_json(spine),
            DocPosition::HumanReadme => human_readme(spine),
            DocPosition::RepoContract => repo_contract_json(spine),
        }
    }
}

fn agent_cards(spine: &CardSpine) -> String {
    let mut out = String::new();
    for recipe in recipe_paths(spine) {
        out.push_str(&format!(
            "{{\"kind\":\"recipe\",\"path\":\"{}\"}}\n",
            json_escape(&recipe)
        ));
    }
    out
}

fn card_index_json(spine: &CardSpine) -> String {
    let entries = recipe_paths(spine)
        .into_iter()
        .map(|recipe| format!("    \"{}\"", json_escape(&recipe)))
        .collect::<Vec<_>>()
        .join(",\n");
    if entries.is_empty() {
        "{\n  \"schema\": \"sim.card-index.v1\",\n  \"cards\": []\n}\n".to_owned()
    } else {
        format!("{{\n  \"schema\": \"sim.card-index.v1\",\n  \"cards\": [\n{entries}\n  ]\n}}\n")
    }
}

fn human_readme(spine: &CardSpine) -> String {
    let repo = repo_name(spine);
    let recipes = recipe_paths(spine);
    let mut out = format!(
        "# {repo} Human Docs\n\nThis lane contains human-readable guides generated by `xtask simdoc`.\n"
    );
    if recipes.is_empty() {
        out.push_str("\nNo recipes were found in this repository.\n");
    } else {
        out.push_str("\n## Recipes\n\n");
        for recipe in recipes {
            out.push_str(&format!("- `{recipe}`\n"));
        }
    }
    out
}

fn repo_contract_json(spine: &CardSpine) -> String {
    let repo = repo_name(spine);
    let lane_entries = [
        contract_value(spine, "lane:target-doc", "target/doc/"),
        contract_value(spine, "lane:agent-cards", "docs/agents/cards.jsonl"),
        contract_value(spine, "lane:human-docs", "docs/humans/"),
        contract_value(spine, "lane:diagram-src", "docs/diagrams/src/"),
        contract_value(spine, "lane:diagram-generated", "docs/diagrams/generated/"),
    ];
    let contract_entries = [
        contract_value(
            spine,
            "contract:provenance",
            "docs/generated/provenance.json",
        ),
        contract_value(spine, "contract:repo", "docs/generated/repo-contract.json"),
        contract_value(
            spine,
            "contract:rustdoc",
            "docs/generated/rustdoc-index.json",
        ),
        contract_value(
            spine,
            "contract:card-index",
            "docs/generated/card-index.json",
        ),
        contract_value(
            spine,
            "contract:feature-map",
            "docs/generated/feature-map.json",
        ),
    ];

    format!(
        "{{\n  \"schema\": \"sim.repo-contract.v1\",\n  \"repo\": \"{}\",\n  \"lanes\": [\n{}\n  ],\n  \"contracts\": [\n{}\n  ]\n}}\n",
        json_escape(&repo),
        json_array_lines(&lane_entries),
        json_array_lines(&contract_entries)
    )
}

fn recipe_paths(spine: &CardSpine) -> Vec<String> {
    spine
        .cards
        .iter()
        .filter(|card| card.kind == "recipe")
        .filter_map(|card| card.data.get("path").cloned())
        .collect()
}

fn repo_name(spine: &CardSpine) -> String {
    contract_card(spine)
        .and_then(|card| card.data.get("repo"))
        .cloned()
        .unwrap_or_else(|| "REPO_NAME".to_owned())
}

fn contract_value(spine: &CardSpine, key: &str, fallback: &str) -> String {
    contract_card(spine)
        .and_then(|card| card.data.get(key))
        .cloned()
        .unwrap_or_else(|| fallback.to_owned())
}

fn contract_card(spine: &CardSpine) -> Option<&Card> {
    spine.cards.iter().find(|card| card.kind == "repo-contract")
}

fn json_array_lines(entries: &[String]) -> String {
    entries
        .iter()
        .map(|entry| format!("    \"{}\"", json_escape(entry)))
        .collect::<Vec<_>>()
        .join(",\n")
}

fn json_escape(input: &str) -> String {
    input
        .chars()
        .flat_map(|ch| match ch {
            '"' => "\\\"".chars().collect::<Vec<_>>(),
            '\\' => "\\\\".chars().collect::<Vec<_>>(),
            '\n' => "\\n".chars().collect::<Vec<_>>(),
            '\r' => "\\r".chars().collect::<Vec<_>>(),
            '\t' => "\\t".chars().collect::<Vec<_>>(),
            other => vec![other],
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;

    #[test]
    fn docencoder_reproduces_fixture_lanes_byte_for_byte() {
        let spine = fixture_spine();
        let encoder = DocEncoder;

        assert_eq!(
            encoder.encode(&spine, DocPosition::AgentCards),
            concat!(
                "{\"kind\":\"recipe\",\"path\":\"recipes/01-basics/open/recipe.toml\"}\n",
                "{\"kind\":\"recipe\",\"path\":\"recipes/02-advanced/tune/recipe.toml\"}\n"
            )
        );
        assert_eq!(
            encoder.encode(&spine, DocPosition::CardIndex),
            concat!(
                "{\n",
                "  \"schema\": \"sim.card-index.v1\",\n",
                "  \"cards\": [\n",
                "    \"recipes/01-basics/open/recipe.toml\",\n",
                "    \"recipes/02-advanced/tune/recipe.toml\"\n",
                "  ]\n",
                "}\n"
            )
        );
        assert_eq!(
            encoder.encode(&spine, DocPosition::HumanReadme),
            concat!(
                "# sim-fixture Human Docs\n\n",
                "This lane contains human-readable guides generated by `xtask simdoc`.\n",
                "\n",
                "## Recipes\n\n",
                "- `recipes/01-basics/open/recipe.toml`\n",
                "- `recipes/02-advanced/tune/recipe.toml`\n"
            )
        );
        assert_eq!(
            encoder.encode(&spine, DocPosition::RepoContract),
            concat!(
                "{\n",
                "  \"schema\": \"sim.repo-contract.v1\",\n",
                "  \"repo\": \"sim-fixture\",\n",
                "  \"lanes\": [\n",
                "    \"target/doc/\",\n",
                "    \"docs/agents/cards.jsonl\",\n",
                "    \"docs/humans/\",\n",
                "    \"docs/diagrams/src/\",\n",
                "    \"docs/diagrams/generated/\"\n",
                "  ],\n",
                "  \"contracts\": [\n",
                "    \"docs/generated/provenance.json\",\n",
                "    \"docs/generated/repo-contract.json\",\n",
                "    \"docs/generated/rustdoc-index.json\",\n",
                "    \"docs/generated/card-index.json\",\n",
                "    \"docs/generated/feature-map.json\"\n",
                "  ]\n",
                "}\n"
            )
        );
    }

    fn fixture_spine() -> CardSpine {
        CardSpine {
            cards: vec![
                recipe_card("recipes/01-basics/open/recipe.toml"),
                recipe_card("recipes/02-advanced/tune/recipe.toml"),
                repo_contract_card(),
            ],
        }
    }

    fn recipe_card(path: &str) -> Card {
        let mut data = BTreeMap::new();
        data.insert("path".to_owned(), path.to_owned());
        Card {
            id: format!("recipe/sim-fixture/{path}"),
            kind: "recipe".to_owned(),
            data,
        }
    }

    fn repo_contract_card() -> Card {
        let mut data = BTreeMap::new();
        data.insert("repo".to_owned(), "sim-fixture".to_owned());
        data.insert("lane:target-doc".to_owned(), "target/doc/".to_owned());
        data.insert(
            "lane:agent-cards".to_owned(),
            "docs/agents/cards.jsonl".to_owned(),
        );
        data.insert("lane:human-docs".to_owned(), "docs/humans/".to_owned());
        data.insert(
            "lane:diagram-src".to_owned(),
            "docs/diagrams/src/".to_owned(),
        );
        data.insert(
            "lane:diagram-generated".to_owned(),
            "docs/diagrams/generated/".to_owned(),
        );
        data.insert(
            "contract:provenance".to_owned(),
            "docs/generated/provenance.json".to_owned(),
        );
        data.insert(
            "contract:repo".to_owned(),
            "docs/generated/repo-contract.json".to_owned(),
        );
        data.insert(
            "contract:rustdoc".to_owned(),
            "docs/generated/rustdoc-index.json".to_owned(),
        );
        data.insert(
            "contract:card-index".to_owned(),
            "docs/generated/card-index.json".to_owned(),
        );
        data.insert(
            "contract:feature-map".to_owned(),
            "docs/generated/feature-map.json".to_owned(),
        );
        Card {
            id: "repo-contract/sim-fixture".to_owned(),
            kind: "repo-contract".to_owned(),
            data,
        }
    }
}
