//! Feature-page rendering for the generated SIM Index.

use std::collections::BTreeMap;

use sim_index_core::{DiscoveredSpecimen, FeatureRecord, IndexDoc};

use crate::index_source::SourceResolver;

const GENERATED: &str = "<!-- GENERATED BY xtask index render; DO NOT EDIT. -->";

pub(crate) fn feature_index_page(doc: &IndexDoc) -> String {
    let mut out = markdown_page("SIM Index Features");
    if doc.features.is_empty() {
        out.push_str("No feature rows are present.\n");
        return out;
    }
    out.push_str("| Feature | Subject | Specimens |\n| --- | --- | ---: |\n");
    for feature in &doc.features {
        out.push_str(&format!(
            "| [{}]({}) | `{}` | {} |\n",
            inline_code(feature.id.as_str()),
            feature_page_path(feature.id.as_str()),
            feature.subject,
            feature.specimens.len()
        ));
    }
    out
}

pub(crate) fn feature_files(
    doc: &IndexDoc,
    sources: &SourceResolver,
) -> Result<Vec<(String, String)>, String> {
    let specimens = specimens_by_id(doc);
    doc.features
        .iter()
        .map(|feature| {
            Ok((
                feature_page_path(feature.id.as_str()),
                feature_page(feature, &specimens, sources)?,
            ))
        })
        .collect()
}

pub(crate) fn feature_page_path(id: &str) -> String {
    format!("features/{}.md", id.replace('/', "--"))
}

fn feature_page(
    feature: &FeatureRecord,
    specimens: &BTreeMap<String, &DiscoveredSpecimen>,
    sources: &SourceResolver,
) -> Result<String, String> {
    let mut out = markdown_page(&feature.title);
    out.push_str(&format!(
        "- Feature id: `{}`\n- Subject: `{}`\n- Canonical key: `{}`\n\n{}\n",
        feature.id, feature.subject, feature.key, feature.summary
    ));
    if !feature.anchors.is_empty() {
        out.push_str("\n## Anchors\n\n");
        for anchor in &feature.anchors {
            out.push_str(&format!("- `{anchor}`\n"));
        }
    }
    if !feature.surfaces.is_empty() {
        out.push_str("\n## Surfaces\n\n");
        for surface in &feature.surfaces {
            out.push_str(&format!("- `{surface}`\n"));
        }
    }
    if !feature.specimens.is_empty() {
        out.push_str("\n## Specimens\n\n");
        for specimen in &feature.specimens {
            out.push_str(&format!("- `{specimen}`\n"));
        }
    }
    if let Some(specimen) = first_worked_specimen(feature, specimens) {
        render_worked_example(&mut out, specimen, sources)?;
    }
    Ok(out)
}

fn render_worked_example(
    out: &mut String,
    specimen: &DiscoveredSpecimen,
    sources: &SourceResolver,
) -> Result<(), String> {
    out.push_str("\n## Worked Example\n\n");
    out.push_str(&format!(
        "Specimen `{}` is checked by `{}`.\n\n",
        specimen.id,
        specimen.checked_by.as_deref().unwrap_or("validation")
    ));
    match sources.source_for(specimen)? {
        Some(source) => {
            out.push_str(&format!("Source `{}`:\n\n", source.path));
            out.push_str(&format!("```{}\n", source.language));
            out.push_str(source.text.trim_end());
            out.push_str("\n```\n");
        }
        None => {
            out.push_str(&format!("Source path: `{}`.\n", specimen.path));
        }
    }
    Ok(())
}

fn first_worked_specimen<'a>(
    feature: &FeatureRecord,
    specimens: &'a BTreeMap<String, &'a DiscoveredSpecimen>,
) -> Option<&'a DiscoveredSpecimen> {
    feature
        .specimens
        .iter()
        .filter_map(|id| specimens.get(id.as_str()).copied())
        .find(|specimen| specimen.runnable && specimen.checked)
}

fn specimens_by_id(doc: &IndexDoc) -> BTreeMap<String, &DiscoveredSpecimen> {
    doc.specimens
        .iter()
        .map(|specimen| (specimen.id.to_string(), specimen))
        .collect()
}

fn markdown_page(title: &str) -> String {
    format!("# {title}\n\n{GENERATED}\n\n")
}

pub(crate) fn inline_code(value: &str) -> String {
    format!("`{}`", value.replace('`', "\\`"))
}

#[cfg(test)]
mod tests {
    use sim_index_core::{
        CanonicalFeatureKey, DiscoveredSpecimen, FeatureId, FeatureRecord, IndexDoc, SpecimenId,
        SubjectId, SubjectRecord, Visibility,
    };

    use super::*;

    #[test]
    fn feature_pages_embed_checked_specimen_pointer() {
        let files = feature_files(&fixture_doc(), &SourceResolver::empty()).unwrap();
        let page = files
            .iter()
            .find(|(name, _)| name == "features/feature--demo.md")
            .map(|(_, contents)| contents)
            .unwrap();

        assert!(page.contains("## Worked Example"));
        assert!(page.contains("Specimen `recipe/demo/open`"));
        assert!(page.contains("Source path: `recipes/open/recipe.toml`"));
    }

    #[test]
    fn feature_index_links_to_feature_pages() {
        let page = feature_index_page(&fixture_doc());

        assert!(page.contains("[`feature/demo`](features/feature--demo.md)"));
    }

    fn fixture_doc() -> IndexDoc {
        let mut doc = IndexDoc {
            schema: "sim.index".to_owned(),
            generated_by: "test".to_owned(),
            visibility: Visibility::Public,
            subjects: vec![SubjectRecord {
                id: SubjectId::new("crate/demo"),
                kind: "crate".to_owned(),
                title: "demo".to_owned(),
            }],
            anchors: Vec::new(),
            surfaces: Vec::new(),
            specimens: vec![DiscoveredSpecimen {
                id: SpecimenId::new("recipe/demo/open"),
                subject: SubjectId::new("crate/demo"),
                kind: "recipe".to_owned(),
                path: "recipes/open/recipe.toml".to_owned(),
                language: Some("lisp".to_owned()),
                runnable: true,
                checked: true,
                checked_by: Some("cargo test".to_owned()),
                doc_anchor: None,
            }],
            drafts: Vec::new(),
            features: Vec::new(),
            routes: Vec::new(),
            edges: Vec::new(),
        };
        doc.features.push(FeatureRecord {
            id: FeatureId::new("feature/demo"),
            key: CanonicalFeatureKey::new("crate/demo/demo"),
            subject: SubjectId::new("crate/demo"),
            title: "Demo".to_owned(),
            summary: "Routing demo feature.".to_owned(),
            anchors: Vec::new(),
            surfaces: Vec::new(),
            specimens: vec![SpecimenId::new("recipe/demo/open")],
            grammar_contracts: Vec::new(),
            doc_anchor: None,
        });
        doc
    }
}
