//! Render the merged SIM Index graph into public pages and queryable files.

use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
};

use serde_json::{Value, json};
use sim_codec_index::{IndexCodec, IndexForm};
use sim_index_core::{
    DiscoveredSpecimen, DiscoveredSurface, FeatureRecord, IndexDoc, RouteRecord, RouteStep,
    SubjectRecord, check_index_doc,
};
use sim_kernel::EncodePosition;

use crate::{
    index_render_features::{feature_files, feature_index_page, feature_page_path},
    index_render_frameworks::frameworks_page,
    index_rules::route_coverage_gaps,
    index_source::SourceResolver,
};

pub(crate) const GENERATED: &str = "<!-- GENERATED BY xtask index render; DO NOT EDIT. -->";

pub(crate) fn run_render(args: Vec<String>) -> Result<(), String> {
    let options = RenderOptions::parse(&args)?;
    let doc = load_doc(&options.input)?;
    let sources = SourceResolver::from_options(
        options.control_root.as_deref(),
        options.repos_manifest.as_deref(),
    )?;
    let files = expected_files_with_sources(&doc, &sources)?;
    write_or_check_files(&options.out, &files, options.check)?;
    if options.check {
        println!("index render: generated index pages are current");
    } else {
        println!(
            "index render: {} page(s), {} card row(s)",
            files
                .iter()
                .filter(|file| file.name.ends_with(".md"))
                .count(),
            card_count(&doc)
        );
    }
    Ok(())
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct RenderOptions {
    input: PathBuf,
    out: PathBuf,
    check: bool,
    control_root: Option<PathBuf>,
    repos_manifest: Option<PathBuf>,
}

impl RenderOptions {
    fn parse(args: &[String]) -> Result<Self, String> {
        let program = args.first().map(String::as_str).unwrap_or("xtask");
        if !matches!(args.get(1).map(String::as_str), Some("index"))
            || !matches!(args.get(2).map(String::as_str), Some("render"))
        {
            return Err(render_usage(program));
        }
        let mut input = None;
        let mut out = None;
        let mut check = false;
        let mut control_root = None;
        let mut repos_manifest = None;
        let mut index = 3;
        while index < args.len() {
            match args[index].as_str() {
                "--input" => {
                    index += 1;
                    input = Some(PathBuf::from(
                        args.get(index).ok_or("--input requires a path")?,
                    ));
                }
                "--out" => {
                    index += 1;
                    out = Some(PathBuf::from(
                        args.get(index).ok_or("--out requires a path")?,
                    ));
                }
                "--check" => check = true,
                "--control-root" => {
                    index += 1;
                    control_root = Some(PathBuf::from(
                        args.get(index).ok_or("--control-root requires a path")?,
                    ));
                }
                "--repos-manifest" => {
                    index += 1;
                    repos_manifest = Some(PathBuf::from(
                        args.get(index).ok_or("--repos-manifest requires a path")?,
                    ));
                }
                "-h" | "--help" => return Err(render_usage(program)),
                other => {
                    return Err(format!(
                        "unknown index render argument `{other}`; {}",
                        render_usage(program)
                    ));
                }
            }
            index += 1;
        }
        Ok(Self {
            input: input.ok_or_else(|| {
                format!("index render requires --input; {}", render_usage(program))
            })?,
            out: out
                .ok_or_else(|| format!("index render requires --out; {}", render_usage(program)))?,
            check,
            control_root,
            repos_manifest,
        })
    }
}

fn render_usage(program: &str) -> String {
    format!(
        "usage: {program} index render --input <index.sx> --out <dir> [--check] [--control-root <path> --repos-manifest <path>]"
    )
}

pub(crate) fn load_doc(path: &Path) -> Result<IndexDoc, String> {
    let source =
        fs::read_to_string(path).map_err(|err| format!("read {}: {err}", path.display()))?;
    let form = if source.trim_start().starts_with('{') {
        IndexForm::Json
    } else {
        IndexForm::Sx
    };
    let doc = IndexCodec
        .decode(form, &source)
        .map_err(|err| format!("decode {}: {err}", path.display()))?;
    check_index_doc(&doc).map_err(|err| format!("invalid index {}: {err}", path.display()))?;
    Ok(doc)
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct GeneratedFile {
    name: String,
    contents: String,
}

#[cfg(test)]
fn expected_files(doc: &IndexDoc) -> Result<Vec<GeneratedFile>, String> {
    expected_files_with_sources(doc, &SourceResolver::empty())
}

fn expected_files_with_sources(
    doc: &IndexDoc,
    sources: &SourceResolver,
) -> Result<Vec<GeneratedFile>, String> {
    let json = IndexCodec
        .encode(doc, EncodePosition::Data, IndexForm::Json)
        .map_err(|err| format!("encode index.json: {err}"))?;
    let mut files = vec![
        file("index.json", with_newline(json)),
        file("index.cards.jsonl", cards_jsonl(doc)?),
        file("overview.md", overview_page(doc)),
        file("features.md", feature_index_page(doc)),
        file("user.md", user_page(doc)),
        file("code.md", code_page(doc)),
        file("frameworks.md", frameworks_page(doc)),
        file("surfaces.md", surfaces_page(doc)),
        file("languages.md", languages_page(doc)),
        file("packages.md", packages_page(doc)),
        file("specimens.md", specimens_page(doc)),
        file("routes.md", routes_page(doc)),
    ];
    files.extend(
        feature_files(doc, sources)?
            .into_iter()
            .map(|(name, contents)| file(name, contents)),
    );
    Ok(files)
}

fn file(name: impl Into<String>, contents: String) -> GeneratedFile {
    GeneratedFile {
        name: name.into(),
        contents,
    }
}

fn write_or_check_files(out: &Path, files: &[GeneratedFile], check: bool) -> Result<(), String> {
    if check {
        let expected_names = files
            .iter()
            .map(|file| file.name.clone())
            .collect::<BTreeSet<_>>();
        let stale = files
            .iter()
            .filter_map(|file| {
                let path = out.join(&file.name);
                match fs::read_to_string(&path) {
                    Ok(current) if current == file.contents => None,
                    Ok(_) | Err(_) => Some(file.name.as_str()),
                }
            })
            .collect::<Vec<_>>();
        let extra = extra_feature_pages(out, &expected_names)?;
        if stale.is_empty() && extra.is_empty() {
            return Ok(());
        }
        let mut stale = stale.into_iter().map(str::to_owned).collect::<Vec<_>>();
        stale.extend(extra);
        return Err(format!(
            "stale generated index artifacts: {}; run `sh bin/simctl index`",
            stale.join(", ")
        ));
    }

    fs::create_dir_all(out).map_err(|err| format!("create {}: {err}", out.display()))?;
    let feature_dir = out.join("features");
    if feature_dir.exists() {
        fs::remove_dir_all(&feature_dir)
            .map_err(|err| format!("remove {}: {err}", feature_dir.display()))?;
    }
    for file in files {
        let path = out.join(&file.name);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|err| format!("create {}: {err}", parent.display()))?;
        }
        fs::write(&path, &file.contents)
            .map_err(|err| format!("write {}: {err}", path.display()))?;
    }
    Ok(())
}

fn extra_feature_pages(
    out: &Path,
    expected_names: &BTreeSet<String>,
) -> Result<Vec<String>, String> {
    let dir = out.join("features");
    if !dir.exists() {
        return Ok(Vec::new());
    }
    let mut extra = Vec::new();
    collect_extra_feature_pages(out, &dir, expected_names, &mut extra)?;
    extra.sort();
    Ok(extra)
}

fn collect_extra_feature_pages(
    out: &Path,
    dir: &Path,
    expected_names: &BTreeSet<String>,
    extra: &mut Vec<String>,
) -> Result<(), String> {
    for entry in fs::read_dir(dir).map_err(|err| format!("read {}: {err}", dir.display()))? {
        let entry = entry.map_err(|err| format!("read {}: {err}", dir.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_extra_feature_pages(out, &path, expected_names, extra)?;
        } else if path.extension().and_then(|extension| extension.to_str()) == Some("md") {
            let rel = path
                .strip_prefix(out)
                .map_err(|err| format!("relative {}: {err}", path.display()))?
                .to_string_lossy()
                .replace(std::path::MAIN_SEPARATOR, "/");
            if !expected_names.contains(&rel) {
                extra.push(rel);
            }
        }
    }
    Ok(())
}

fn overview_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Overview");
    out.push_str("The SIM Index is the generated constellation graph for public source facts, feature rows, surfaces, specimens, and task routes.\n\n");
    out.push_str("| Row family | Count |\n| --- | ---: |\n");
    for (label, count) in [
        ("Subjects", doc.subjects.len()),
        ("Anchors", doc.anchors.len()),
        ("Surfaces", doc.surfaces.len()),
        ("Specimens", doc.specimens.len()),
        ("Features", doc.features.len()),
        ("Routes", doc.routes.len()),
        ("Edges", doc.edges.len()),
    ] {
        out.push_str(&format!("| {label} | {count} |\n"));
    }
    out.push_str("\n| Page | Focus |\n| --- | --- |\n");
    for (name, focus) in [
        ("user.md", "Feature rows and task-facing descriptions"),
        ("features.md", "Feature pages with worked examples"),
        ("code.md", "Repositories, crates, and doc sets"),
        ("frameworks.md", "Framework-like rows and related surfaces"),
        (
            "surfaces.md",
            "Invoke, read, write, view, and site surfaces",
        ),
        ("languages.md", "Language, grammar, and codec evidence"),
        ("packages.md", "Package subjects and containment edges"),
        ("specimens.md", "Runnable and checked examples"),
        ("routes.md", "Task routes through features and specimens"),
    ] {
        out.push_str(&format!("| `{name}` | {focus} |\n"));
    }
    out
}

fn user_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index User View");
    if doc.features.is_empty() {
        out.push_str("No feature rows are present.\n");
        return out;
    }
    out.push_str("| Feature | Subject | Summary | Specimens |\n| --- | --- | --- | ---: |\n");
    for feature in &doc.features {
        out.push_str(&format!(
            "| [`{}`]({}) | `{}` | {} | {} |\n",
            feature.id,
            feature_page_path(feature.id.as_str()),
            feature.subject,
            cell(&feature.summary),
            feature.specimens.len()
        ));
    }
    out
}

fn code_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Code View");
    out.push_str("| Subject | Kind | Title | Contains |\n| --- | --- | --- | ---: |\n");
    for subject in package_subjects(doc) {
        out.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            subject.id,
            subject.kind,
            cell(&subject.title),
            contains_count(doc, subject.id.as_str())
        ));
    }
    out
}

fn surfaces_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Surfaces");
    out.push_str("| Surface | Kind | Subject |\n| --- | --- | --- |\n");
    for surface in &doc.surfaces {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` |\n",
            surface.id, surface.kind, surface.subject
        ));
    }
    out
}

fn languages_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Languages");
    let mut rows = BTreeSet::new();
    for subject in &doc.subjects {
        if looks_language(&subject.kind) || looks_language(&subject.title) {
            rows.insert((
                "subject".to_owned(),
                subject.id.to_string(),
                subject.title.clone(),
            ));
        }
    }
    for feature in &doc.features {
        for grammar in &feature.grammar_contracts {
            rows.insert((
                "grammar".to_owned(),
                grammar.id.clone(),
                feature.title.clone(),
            ));
        }
    }
    for specimen in &doc.specimens {
        if let Some(language) = &specimen.language {
            rows.insert((
                "specimen".to_owned(),
                language.clone(),
                specimen.path.clone(),
            ));
        }
    }
    if rows.is_empty() {
        out.push_str("No language or grammar rows are present.\n");
        return out;
    }
    out.push_str("| Source | Id | Context |\n| --- | --- | --- |\n");
    for (source, id, context) in rows {
        out.push_str(&format!("| `{source}` | `{id}` | {} |\n", cell(&context)));
    }
    out
}

fn packages_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Packages");
    out.push_str("| Package | Kind | Title |\n| --- | --- | --- |\n");
    for subject in package_subjects(doc) {
        out.push_str(&format!(
            "| `{}` | `{}` | {} |\n",
            subject.id,
            subject.kind,
            cell(&subject.title)
        ));
    }
    out
}

fn specimens_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Specimens");
    if doc.specimens.is_empty() {
        out.push_str("No specimen rows are present.\n");
        return out;
    }
    out.push_str(
        "| Specimen | Subject | Kind | Path | Checked |\n| --- | --- | --- | --- | --- |\n",
    );
    for specimen in &doc.specimens {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` |\n",
            specimen.id, specimen.subject, specimen.kind, specimen.path, specimen.checked
        ));
    }
    out
}

fn routes_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Routes");
    if doc.routes.is_empty() {
        out.push_str("No route rows are present.\n");
        return out;
    }
    for audience in ["user", "code", "framework"] {
        let routes = doc
            .routes
            .iter()
            .filter(|route| route.audiences.iter().any(|item| item == audience))
            .collect::<Vec<_>>();
        if routes.is_empty() {
            continue;
        }
        out.push_str(&format!("## {} routes\n\n", title_case(audience)));
        push_route_table(&mut out, routes);
    }
    let unclassified = doc
        .routes
        .iter()
        .filter(|route| route.audiences.is_empty())
        .collect::<Vec<_>>();
    if !unclassified.is_empty() {
        out.push_str("## Unclassified routes\n\n");
        push_route_table(&mut out, unclassified);
    }
    let gaps = route_coverage_gaps(doc);
    if !gaps.is_empty() {
        out.push_str("## Coverage Gaps\n\n");
        out.push_str("| Category | Id | Reason |\n| --- | --- | --- |\n");
        for gap in gaps {
            out.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                gap.category,
                gap.id,
                cell(&gap.reason)
            ));
        }
    }
    out
}

fn push_route_table(out: &mut String, routes: Vec<&RouteRecord>) {
    out.push_str("| Route | Title | Audiences | Steps |\n| --- | --- | --- | --- |\n");
    for route in routes {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            route.id,
            cell(&route.title),
            cell(&route.audiences.join(", ")),
            cell(
                &route
                    .steps
                    .iter()
                    .map(route_step_label)
                    .collect::<Vec<_>>()
                    .join("<br>")
            )
        ));
    }
    out.push('\n');
}

fn page(title: &str) -> String {
    format!("# {title}\n\n{GENERATED}\n\n")
}

fn package_subjects(doc: &IndexDoc) -> impl Iterator<Item = &SubjectRecord> {
    doc.subjects.iter().filter(|subject| {
        matches!(
            subject.kind.as_str(),
            "repo" | "crate" | "package" | "doc-set"
        )
    })
}

fn contains_count(doc: &IndexDoc, subject: &str) -> usize {
    doc.edges
        .iter()
        .filter(|edge| edge.rel == "contains" && edge.from == subject)
        .count()
}

fn looks_language(value: &str) -> bool {
    let value = value.to_ascii_lowercase();
    value.contains("language")
        || value.contains("grammar")
        || value.contains("codec")
        || value.contains("syntax")
}

fn route_step_label(step: &RouteStep) -> String {
    if step.why().is_empty() {
        format!("`{}`", step.id())
    } else {
        format!("`{}` - {}", step.id(), step.why())
    }
}

fn card_count(doc: &IndexDoc) -> usize {
    doc.subjects.len()
        + doc.surfaces.len()
        + doc.features.len()
        + doc.specimens.len()
        + doc.routes.len()
}

fn cards_jsonl(doc: &IndexDoc) -> Result<String, String> {
    let mut rows = Vec::new();
    for subject in &doc.subjects {
        rows.push(json!({
            "kind": "subject",
            "id": subject.id.as_str(),
            "subject_kind": subject.kind,
            "title": subject.title,
        }));
    }
    for surface in &doc.surfaces {
        rows.push(surface_card(surface));
    }
    for feature in &doc.features {
        rows.push(feature_card(feature));
    }
    for specimen in &doc.specimens {
        rows.push(specimen_card(specimen));
    }
    for route in &doc.routes {
        rows.push(route_card(route));
    }
    rows.sort_by(|left, right| {
        (
            left["kind"].as_str().unwrap_or_default(),
            left["id"].as_str().unwrap_or_default(),
        )
            .cmp(&(
                right["kind"].as_str().unwrap_or_default(),
                right["id"].as_str().unwrap_or_default(),
            ))
    });
    let mut out = String::new();
    for row in rows {
        out.push_str(&serde_json::to_string(&row).map_err(|err| format!("serialize card: {err}"))?);
        out.push('\n');
    }
    Ok(out)
}

fn feature_card(feature: &FeatureRecord) -> Value {
    json!({
        "kind": "feature",
        "id": feature.id.as_str(),
        "canonical_key": feature.key.as_str(),
        "subject": feature.subject.as_str(),
        "title": feature.title,
        "summary": feature.summary,
        "page": feature_page_path(feature.id.as_str()),
        "anchors": feature.anchors.iter().map(ToString::to_string).collect::<Vec<_>>(),
        "surfaces": feature.surfaces.iter().map(ToString::to_string).collect::<Vec<_>>(),
        "specimens": feature.specimens.iter().map(ToString::to_string).collect::<Vec<_>>(),
    })
}

fn surface_card(surface: &DiscoveredSurface) -> Value {
    json!({
        "kind": "surface",
        "id": surface.id.as_str(),
        "subject": surface.subject.as_str(),
        "surface_kind": surface.kind,
    })
}

fn specimen_card(specimen: &DiscoveredSpecimen) -> Value {
    json!({
        "kind": "specimen",
        "id": specimen.id.as_str(),
        "subject": specimen.subject.as_str(),
        "specimen_kind": specimen.kind,
        "path": specimen.path,
        "language": specimen.language,
        "runnable": specimen.runnable,
        "checked": specimen.checked,
        "checked_by": specimen.checked_by,
    })
}

fn route_card(route: &RouteRecord) -> Value {
    json!({
        "kind": "route",
        "id": route.id.as_str(),
        "title": route.title,
        "audiences": route.audiences,
        "steps": route.steps.iter().map(route_step_card).collect::<Vec<_>>(),
    })
}

fn route_step_card(step: &RouteStep) -> Value {
    json!({
        "kind": step.kind(),
        "id": step.id(),
        "why": step.why(),
    })
}

fn cell(value: &str) -> String {
    value.replace(['\n', '\r'], " ").replace('|', "\\|")
}

fn title_case(value: &str) -> String {
    let mut chars = value.chars();
    match chars.next() {
        Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

fn with_newline(mut value: String) -> String {
    if !value.ends_with('\n') {
        value.push('\n');
    }
    value
}

#[cfg(test)]
#[path = "index_render_tests.rs"]
mod tests;
