//! Maintenance commands for SIM Index feature overlay gaps.

use std::{
    fs,
    path::{Path, PathBuf},
};

use sim_codec_index::{IndexCodec, IndexForm};
use sim_index_core::IndexDoc;

use crate::{
    index_fragment::{repo_name, slug_path},
    index_rules::{MissingDraftRow, missing_draft_rows},
};

pub(crate) fn run(args: Vec<String>) -> Result<(), String> {
    let options = DoctorOptions::parse(&args)?;
    let doc = load_fragment(&options.repo)?;
    let rows = missing_draft_rows(&doc);
    let content = render_missing_features(&options.repo, &rows);
    if let Some(parent) = options.out.parent() {
        fs::create_dir_all(parent).map_err(|err| format!("create {}: {err}", parent.display()))?;
    }
    fs::write(&options.out, content)
        .map_err(|err| format!("write {}: {err}", options.out.display()))?;
    println!(
        "index doctor: wrote {} missing draft rows to {}",
        rows.len(),
        options.out.display()
    );
    Ok(())
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct DoctorOptions {
    repo: PathBuf,
    out: PathBuf,
}

impl DoctorOptions {
    fn parse(args: &[String]) -> Result<Self, String> {
        let program = args.first().map(String::as_str).unwrap_or("xtask");
        if args.get(1).map(String::as_str) != Some("index")
            || args.get(2).map(String::as_str) != Some("doctor")
        {
            return Err(usage(program));
        }

        let mut repo = None;
        let mut out = None;
        let mut missing = false;
        let mut index = 3;
        while index < args.len() {
            match args[index].as_str() {
                "--repo" => {
                    index += 1;
                    repo = Some(PathBuf::from(
                        args.get(index).ok_or("--repo requires a path")?.as_str(),
                    ));
                }
                "--missing" => missing = true,
                "--out" => {
                    index += 1;
                    out = Some(PathBuf::from(
                        args.get(index).ok_or("--out requires a path")?.as_str(),
                    ));
                }
                other => {
                    return Err(format!(
                        "unknown index doctor argument `{other}`; {}",
                        usage(program)
                    ));
                }
            }
            index += 1;
        }
        if !missing {
            return Err("index doctor currently requires --missing".to_owned());
        }
        Ok(Self {
            repo: repo.unwrap_or_else(|| PathBuf::from(".")),
            out: out.ok_or("--out requires a path")?,
        })
    }
}

fn usage(program: &str) -> String {
    format!("usage: {program} index doctor --repo <path> --missing --out <path>")
}

fn load_fragment(repo: &Path) -> Result<IndexDoc, String> {
    let path = repo.join("docs/generated/sim-index-fragment.sx");
    let source = fs::read_to_string(&path)
        .map_err(|err| format!("read generated index fragment {}: {err}", path.display()))?;
    IndexCodec
        .decode(IndexForm::Sx, &source)
        .map_err(|err| format!("decode generated index fragment {}: {err}", path.display()))
}

fn render_missing_features(repo: &Path, rows: &[MissingDraftRow]) -> String {
    let repo = slug_path(&repo_name(repo));
    let mut out = String::from(
        "schema = \"sim.features\"\n\n# Generated by index doctor; review and rename before committing.\n",
    );
    for row in rows {
        let feature_id = format!("feature/{repo}/missing/{}/{}", row.kind, slug_path(&row.id));
        out.push_str("\n[[feature]]\n");
        push_toml_string(&mut out, "id", &feature_id);
        push_toml_string(
            &mut out,
            "title",
            &format!("Review {} {}", row.kind, row.id),
        );
        push_toml_string(
            &mut out,
            "summary",
            &format!(
                "Review whether discovered {} belongs in a named feature.",
                row.kind
            ),
        );
        push_toml_string(&mut out, "owner", row.owner.as_str());
        match row.kind {
            "anchor" => push_toml_array(&mut out, "claims_anchors", &[row.id.as_str()]),
            "surface" => push_toml_array(&mut out, "claims_surfaces", &[row.id.as_str()]),
            "specimen" => push_toml_array(&mut out, "claims_specimens", &[row.id.as_str()]),
            _ => {}
        }
    }
    out
}

fn push_toml_string(out: &mut String, key: &str, value: &str) {
    out.push_str(key);
    out.push_str(" = ");
    push_quoted(out, value);
    out.push('\n');
}

fn push_toml_array(out: &mut String, key: &str, values: &[&str]) {
    out.push_str(key);
    out.push_str(" = [");
    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        push_quoted(out, value);
    }
    out.push_str("]\n");
}

fn push_quoted(out: &mut String, value: &str) {
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            other => out.push(other),
        }
    }
    out.push('"');
}

#[cfg(test)]
mod tests {
    use sim_index_core::{
        AnchorId, DiscoveredAnchor, DiscoveredSpecimen, DiscoveredSurface, FeatureId,
        FeatureRecord, SubjectId, SubjectRecord, SurfaceId, Visibility, check_index_doc,
        key::CanonicalFeatureKey,
    };

    use super::*;

    #[test]
    fn missing_rows_skip_claimed_ids_and_render_importable_drafts() {
        let rows = missing_draft_rows(&doc_with_one_claimed_anchor());

        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].kind, "specimen");
        assert_eq!(rows[1].kind, "surface");

        let rendered = render_missing_features(Path::new("/tmp/sim-demo"), &rows);

        assert!(rendered.contains("index doctor"));
        assert!(rendered.contains("claims_specimens"));
        assert!(rendered.contains("claims_surfaces"));
    }

    #[test]
    fn rendered_missing_rows_stay_prose_only() {
        let base = doc_with_one_claimed_anchor();
        let rows = missing_draft_rows(&base);
        let rendered = render_missing_features(Path::new("/tmp/sim-demo"), &rows);
        let overlay = crate::index_author::parse_overlay(&rendered).expect("parse doctor output");
        let mut doc = base;
        doc.features.clear();
        let merged = crate::index_author::merge_authored(doc, overlay).expect("merge doctor rows");

        check_index_doc(&merged).expect("doctor rows are valid overlay rows");
    }

    fn doc_with_one_claimed_anchor() -> IndexDoc {
        IndexDoc {
            schema: "sim.index".to_owned(),
            generated_by: "test".to_owned(),
            visibility: Visibility::Public,
            subjects: vec![SubjectRecord {
                id: SubjectId::new("crate/sim-demo"),
                kind: "crate".to_owned(),
                title: "sim-demo".to_owned(),
            }],
            anchors: vec![DiscoveredAnchor {
                id: AnchorId::new("anchor/cli/repl"),
                subject: SubjectId::new("crate/sim-demo"),
                kind: "cli-verb".to_owned(),
            }],
            surfaces: vec![DiscoveredSurface {
                id: SurfaceId::new("cli/repl"),
                subject: SubjectId::new("crate/sim-demo"),
                kind: "cli".to_owned(),
            }],
            specimens: vec![DiscoveredSpecimen {
                id: sim_index_core::SpecimenId::new("recipe/sim-demo/hello"),
                subject: SubjectId::new("crate/sim-demo"),
                kind: "recipe".to_owned(),
                path: "recipes/hello/recipe.toml".to_owned(),
                language: None,
                runnable: true,
                checked: true,
                checked_by: Some("xtask check-recipes".to_owned()),
                doc_anchor: None,
            }],
            drafts: Vec::new(),
            features: vec![FeatureRecord {
                id: FeatureId::new("feature/sim-demo/repl"),
                key: CanonicalFeatureKey::new("crate/sim-demo::feature/sim-demo/repl"),
                subject: SubjectId::new("crate/sim-demo"),
                title: "REPL".to_owned(),
                summary: "Run a REPL.".to_owned(),
                anchors: vec![AnchorId::new("anchor/cli/repl")],
                surfaces: Vec::new(),
                specimens: Vec::new(),
                grammar_contracts: Vec::new(),
                doc_anchor: None,
            }],
            routes: Vec::new(),
            edges: Vec::new(),
        }
    }
}
