//! Render the merged SIM Index graph into public pages and queryable files.

use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
};

use serde_json::{Value, json};
use sim_codec_index::{IndexCodec, IndexForm};
use sim_index_core::{
    DiscoveredSpecimen, FeatureRecord, IndexDoc, RouteRecord, RouteStep, SubjectRecord,
    check_index_doc,
};
use sim_kernel::EncodePosition;

const GENERATED: &str = "<!-- GENERATED BY xtask index render; DO NOT EDIT. -->";

pub(crate) fn run_render(args: Vec<String>) -> Result<(), String> {
    let options = RenderOptions::parse(&args)?;
    let doc = load_doc(&options.input)?;
    let files = expected_files(&doc)?;
    write_or_check_files(&options.out, &files, options.check)?;
    if options.check {
        println!("index render: generated index pages are current");
    } else {
        println!(
            "index render: {} page(s), {} card row(s)",
            files
                .iter()
                .filter(|file| file.name.ends_with(".md"))
                .count(),
            card_count(&doc)
        );
    }
    Ok(())
}

pub(crate) fn run_find(args: Vec<String>) -> Result<(), String> {
    let options = FindOptions::parse(&args)?;
    let doc = load_doc(&options.input)?;
    let matches = find_rows(&doc, &options.query);
    if options.json {
        let text = serde_json::to_string_pretty(&json!({
            "query": options.query,
            "match_count": matches.len(),
            "matches": matches,
        }))
        .map_err(|err| format!("serialize search results: {err}"))?;
        println!("{text}");
    } else {
        for row in matches {
            println!("{}\t{}\t{}", row["kind"], row["id"], row["title"]);
        }
    }
    Ok(())
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct RenderOptions {
    input: PathBuf,
    out: PathBuf,
    check: bool,
}

impl RenderOptions {
    fn parse(args: &[String]) -> Result<Self, String> {
        let program = args.first().map(String::as_str).unwrap_or("xtask");
        if !matches!(args.get(1).map(String::as_str), Some("index"))
            || !matches!(args.get(2).map(String::as_str), Some("render"))
        {
            return Err(render_usage(program));
        }
        let mut input = None;
        let mut out = None;
        let mut check = false;
        let mut index = 3;
        while index < args.len() {
            match args[index].as_str() {
                "--input" => {
                    index += 1;
                    input = Some(PathBuf::from(
                        args.get(index).ok_or("--input requires a path")?,
                    ));
                }
                "--out" => {
                    index += 1;
                    out = Some(PathBuf::from(
                        args.get(index).ok_or("--out requires a path")?,
                    ));
                }
                "--check" => check = true,
                "-h" | "--help" => return Err(render_usage(program)),
                other => {
                    return Err(format!(
                        "unknown index render argument `{other}`; {}",
                        render_usage(program)
                    ));
                }
            }
            index += 1;
        }
        Ok(Self {
            input: input.ok_or_else(|| {
                format!("index render requires --input; {}", render_usage(program))
            })?,
            out: out
                .ok_or_else(|| format!("index render requires --out; {}", render_usage(program)))?,
            check,
        })
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct FindOptions {
    input: PathBuf,
    query: String,
    json: bool,
}

impl FindOptions {
    fn parse(args: &[String]) -> Result<Self, String> {
        let program = args.first().map(String::as_str).unwrap_or("xtask");
        if !matches!(args.get(1).map(String::as_str), Some("index"))
            || !matches!(args.get(2).map(String::as_str), Some("find"))
        {
            return Err(find_usage(program));
        }
        let mut input = None;
        let mut json = false;
        let mut query = Vec::new();
        let mut index = 3;
        while index < args.len() {
            match args[index].as_str() {
                "--input" => {
                    index += 1;
                    input = Some(PathBuf::from(
                        args.get(index).ok_or("--input requires a path")?,
                    ));
                }
                "--query" => {
                    index += 1;
                    query.push(args.get(index).ok_or("--query requires text")?.to_owned());
                }
                "--json" => json = true,
                "-h" | "--help" => return Err(find_usage(program)),
                other if other.starts_with('-') => {
                    return Err(format!(
                        "unknown index find argument `{other}`; {}",
                        find_usage(program)
                    ));
                }
                other => query.push(other.to_owned()),
            }
            index += 1;
        }
        let query = query.join(" ");
        if query.trim().is_empty() {
            return Err(format!(
                "index find requires a query; {}",
                find_usage(program)
            ));
        }
        Ok(Self {
            input: input
                .ok_or_else(|| format!("index find requires --input; {}", find_usage(program)))?,
            query,
            json,
        })
    }
}

fn render_usage(program: &str) -> String {
    format!("usage: {program} index render --input <index.sx> --out <dir> [--check]")
}

fn find_usage(program: &str) -> String {
    format!("usage: {program} index find --input <index.sx> [--json] <query>")
}

pub(crate) fn load_doc(path: &Path) -> Result<IndexDoc, String> {
    let source =
        fs::read_to_string(path).map_err(|err| format!("read {}: {err}", path.display()))?;
    let form = if source.trim_start().starts_with('{') {
        IndexForm::Json
    } else {
        IndexForm::Sx
    };
    let doc = IndexCodec
        .decode(form, &source)
        .map_err(|err| format!("decode {}: {err}", path.display()))?;
    check_index_doc(&doc).map_err(|err| format!("invalid index {}: {err}", path.display()))?;
    Ok(doc)
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct GeneratedFile {
    name: &'static str,
    contents: String,
}

fn expected_files(doc: &IndexDoc) -> Result<Vec<GeneratedFile>, String> {
    let json = IndexCodec
        .encode(doc, EncodePosition::Data, IndexForm::Json)
        .map_err(|err| format!("encode index.json: {err}"))?;
    Ok(vec![
        file("index.json", with_newline(json)),
        file("index.cards.jsonl", cards_jsonl(doc)?),
        file("overview.md", overview_page(doc)),
        file("user.md", user_page(doc)),
        file("code.md", code_page(doc)),
        file("frameworks.md", frameworks_page(doc)),
        file("surfaces.md", surfaces_page(doc)),
        file("languages.md", languages_page(doc)),
        file("packages.md", packages_page(doc)),
        file("specimens.md", specimens_page(doc)),
        file("routes.md", routes_page(doc)),
    ])
}

fn file(name: &'static str, contents: String) -> GeneratedFile {
    GeneratedFile { name, contents }
}

fn write_or_check_files(out: &Path, files: &[GeneratedFile], check: bool) -> Result<(), String> {
    if check {
        let stale = files
            .iter()
            .filter_map(|file| {
                let path = out.join(file.name);
                match fs::read_to_string(&path) {
                    Ok(current) if current == file.contents => None,
                    Ok(_) | Err(_) => Some(file.name),
                }
            })
            .collect::<Vec<_>>();
        if stale.is_empty() {
            return Ok(());
        }
        return Err(format!(
            "stale generated index artifacts: {}; run `sh bin/simctl index`",
            stale.join(", ")
        ));
    }

    fs::create_dir_all(out).map_err(|err| format!("create {}: {err}", out.display()))?;
    for file in files {
        let path = out.join(file.name);
        fs::write(&path, &file.contents)
            .map_err(|err| format!("write {}: {err}", path.display()))?;
    }
    Ok(())
}

fn overview_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Overview");
    out.push_str("The SIM Index is the generated constellation graph for public source facts, feature rows, surfaces, specimens, and task routes.\n\n");
    out.push_str("| Row family | Count |\n| --- | ---: |\n");
    for (label, count) in [
        ("Subjects", doc.subjects.len()),
        ("Anchors", doc.anchors.len()),
        ("Surfaces", doc.surfaces.len()),
        ("Specimens", doc.specimens.len()),
        ("Features", doc.features.len()),
        ("Routes", doc.routes.len()),
        ("Edges", doc.edges.len()),
    ] {
        out.push_str(&format!("| {label} | {count} |\n"));
    }
    out.push_str("\n| Page | Focus |\n| --- | --- |\n");
    for (name, focus) in [
        ("user.md", "Feature rows and task-facing descriptions"),
        ("code.md", "Repositories, crates, and doc sets"),
        ("frameworks.md", "Framework-like rows and related surfaces"),
        (
            "surfaces.md",
            "Invoke, read, write, view, and site surfaces",
        ),
        ("languages.md", "Language, grammar, and codec evidence"),
        ("packages.md", "Package subjects and containment edges"),
        ("specimens.md", "Runnable and checked examples"),
        ("routes.md", "Task routes through features and specimens"),
    ] {
        out.push_str(&format!("| `{name}` | {focus} |\n"));
    }
    out
}

fn user_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index User View");
    if doc.features.is_empty() {
        out.push_str("No feature rows are present.\n");
        return out;
    }
    out.push_str("| Feature | Subject | Summary | Specimens |\n| --- | --- | --- | ---: |\n");
    for feature in &doc.features {
        out.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            feature.id,
            feature.subject,
            cell(&feature.summary),
            feature.specimens.len()
        ));
    }
    out
}

fn code_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Code View");
    out.push_str("| Subject | Kind | Title | Contains |\n| --- | --- | --- | ---: |\n");
    for subject in package_subjects(doc) {
        out.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            subject.id,
            subject.kind,
            cell(&subject.title),
            contains_count(doc, subject.id.as_str())
        ));
    }
    out
}

fn frameworks_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Frameworks");
    let rows = doc
        .subjects
        .iter()
        .filter(|subject| looks_framework(&subject.kind) || looks_framework(&subject.title))
        .collect::<Vec<_>>();
    if rows.is_empty() {
        out.push_str("No framework-specific subjects are present.\n");
        return out;
    }
    out.push_str("| Subject | Kind | Title |\n| --- | --- | --- |\n");
    for subject in rows {
        out.push_str(&format!(
            "| `{}` | `{}` | {} |\n",
            subject.id,
            subject.kind,
            cell(&subject.title)
        ));
    }
    out
}

fn surfaces_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Surfaces");
    out.push_str("| Surface | Kind | Subject |\n| --- | --- | --- |\n");
    for surface in &doc.surfaces {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` |\n",
            surface.id, surface.kind, surface.subject
        ));
    }
    out
}

fn languages_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Languages");
    let mut rows = BTreeSet::new();
    for subject in &doc.subjects {
        if looks_language(&subject.kind) || looks_language(&subject.title) {
            rows.insert((
                "subject".to_owned(),
                subject.id.to_string(),
                subject.title.clone(),
            ));
        }
    }
    for feature in &doc.features {
        for grammar in &feature.grammar_contracts {
            rows.insert((
                "grammar".to_owned(),
                grammar.id.clone(),
                feature.title.clone(),
            ));
        }
    }
    for specimen in &doc.specimens {
        if let Some(language) = &specimen.language {
            rows.insert((
                "specimen".to_owned(),
                language.clone(),
                specimen.path.clone(),
            ));
        }
    }
    if rows.is_empty() {
        out.push_str("No language or grammar rows are present.\n");
        return out;
    }
    out.push_str("| Source | Id | Context |\n| --- | --- | --- |\n");
    for (source, id, context) in rows {
        out.push_str(&format!("| `{source}` | `{id}` | {} |\n", cell(&context)));
    }
    out
}

fn packages_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Packages");
    out.push_str("| Package | Kind | Title |\n| --- | --- | --- |\n");
    for subject in package_subjects(doc) {
        out.push_str(&format!(
            "| `{}` | `{}` | {} |\n",
            subject.id,
            subject.kind,
            cell(&subject.title)
        ));
    }
    out
}

fn specimens_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Specimens");
    if doc.specimens.is_empty() {
        out.push_str("No specimen rows are present.\n");
        return out;
    }
    out.push_str(
        "| Specimen | Subject | Kind | Path | Checked |\n| --- | --- | --- | --- | --- |\n",
    );
    for specimen in &doc.specimens {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` |\n",
            specimen.id, specimen.subject, specimen.kind, specimen.path, specimen.checked
        ));
    }
    out
}

fn routes_page(doc: &IndexDoc) -> String {
    let mut out = page("SIM Index Routes");
    if doc.routes.is_empty() {
        out.push_str("No route rows are present.\n");
        return out;
    }
    out.push_str("| Route | Title | Steps |\n| --- | --- | --- |\n");
    for route in &doc.routes {
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            route.id,
            cell(&route.title),
            route
                .steps
                .iter()
                .map(route_step_label)
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    out
}

fn page(title: &str) -> String {
    format!("# {title}\n\n{GENERATED}\n\n")
}

fn package_subjects(doc: &IndexDoc) -> impl Iterator<Item = &SubjectRecord> {
    doc.subjects.iter().filter(|subject| {
        matches!(
            subject.kind.as_str(),
            "repo" | "crate" | "package" | "doc-set"
        )
    })
}

fn contains_count(doc: &IndexDoc, subject: &str) -> usize {
    doc.edges
        .iter()
        .filter(|edge| edge.rel == "contains" && edge.from == subject)
        .count()
}

fn looks_framework(value: &str) -> bool {
    let value = value.to_ascii_lowercase();
    value.contains("framework") || value.contains("runtime-lib") || value.contains("library")
}

fn looks_language(value: &str) -> bool {
    let value = value.to_ascii_lowercase();
    value.contains("language")
        || value.contains("grammar")
        || value.contains("codec")
        || value.contains("syntax")
}

fn route_step_label(step: &RouteStep) -> String {
    match step {
        RouteStep::Feature(id) => format!("`{id}`"),
        RouteStep::Specimen(id) => format!("`{id}`"),
    }
}

fn card_count(doc: &IndexDoc) -> usize {
    doc.subjects.len() + doc.features.len() + doc.specimens.len() + doc.routes.len()
}

fn cards_jsonl(doc: &IndexDoc) -> Result<String, String> {
    let mut rows = Vec::new();
    for subject in &doc.subjects {
        rows.push(json!({
            "kind": "subject",
            "id": subject.id.as_str(),
            "subject_kind": subject.kind,
            "title": subject.title,
        }));
    }
    for feature in &doc.features {
        rows.push(feature_card(feature));
    }
    for specimen in &doc.specimens {
        rows.push(specimen_card(specimen));
    }
    for route in &doc.routes {
        rows.push(route_card(route));
    }
    rows.sort_by(|left, right| {
        (
            left["kind"].as_str().unwrap_or_default(),
            left["id"].as_str().unwrap_or_default(),
        )
            .cmp(&(
                right["kind"].as_str().unwrap_or_default(),
                right["id"].as_str().unwrap_or_default(),
            ))
    });
    let mut out = String::new();
    for row in rows {
        out.push_str(&serde_json::to_string(&row).map_err(|err| format!("serialize card: {err}"))?);
        out.push('\n');
    }
    Ok(out)
}

fn feature_card(feature: &FeatureRecord) -> Value {
    json!({
        "kind": "feature",
        "id": feature.id.as_str(),
        "canonical_key": feature.key.as_str(),
        "subject": feature.subject.as_str(),
        "title": feature.title,
        "summary": feature.summary,
        "anchors": feature.anchors.iter().map(ToString::to_string).collect::<Vec<_>>(),
        "surfaces": feature.surfaces.iter().map(ToString::to_string).collect::<Vec<_>>(),
        "specimens": feature.specimens.iter().map(ToString::to_string).collect::<Vec<_>>(),
    })
}

fn specimen_card(specimen: &DiscoveredSpecimen) -> Value {
    json!({
        "kind": "specimen",
        "id": specimen.id.as_str(),
        "subject": specimen.subject.as_str(),
        "specimen_kind": specimen.kind,
        "path": specimen.path,
        "language": specimen.language,
        "runnable": specimen.runnable,
        "checked": specimen.checked,
        "checked_by": specimen.checked_by,
    })
}

fn route_card(route: &RouteRecord) -> Value {
    json!({
        "kind": "route",
        "id": route.id.as_str(),
        "title": route.title,
        "steps": route.steps.iter().map(route_step_id).collect::<Vec<_>>(),
    })
}

fn route_step_id(step: &RouteStep) -> String {
    match step {
        RouteStep::Feature(id) => id.to_string(),
        RouteStep::Specimen(id) => id.to_string(),
    }
}

fn find_rows(doc: &IndexDoc, query: &str) -> Vec<Value> {
    let needle = query.to_ascii_lowercase();
    let mut rows = Vec::new();
    for subject in &doc.subjects {
        if matches_query(
            &needle,
            &[subject.id.as_str(), &subject.kind, &subject.title],
        ) {
            rows.push(json!({
                "kind": "subject",
                "id": subject.id.as_str(),
                "title": subject.title,
                "summary": subject.kind,
            }));
        }
    }
    for feature in &doc.features {
        if matches_query(
            &needle,
            &[
                feature.id.as_str(),
                feature.key.as_str(),
                feature.subject.as_str(),
                &feature.title,
                &feature.summary,
            ],
        ) {
            rows.push(json!({
                "kind": "feature",
                "id": feature.id.as_str(),
                "title": feature.title,
                "summary": feature.summary,
            }));
        }
    }
    for specimen in &doc.specimens {
        if matches_query(
            &needle,
            &[
                specimen.id.as_str(),
                specimen.subject.as_str(),
                &specimen.kind,
                &specimen.path,
            ],
        ) {
            rows.push(json!({
                "kind": "specimen",
                "id": specimen.id.as_str(),
                "title": specimen.path,
                "summary": specimen.kind,
            }));
        }
    }
    for route in &doc.routes {
        if matches_query(&needle, &[route.id.as_str(), &route.title]) {
            rows.push(json!({
                "kind": "route",
                "id": route.id.as_str(),
                "title": route.title,
                "summary": route.steps.len().to_string(),
            }));
        }
    }
    rows.sort_by(|left, right| {
        (
            left["kind"].as_str().unwrap_or_default(),
            left["id"].as_str().unwrap_or_default(),
        )
            .cmp(&(
                right["kind"].as_str().unwrap_or_default(),
                right["id"].as_str().unwrap_or_default(),
            ))
    });
    rows
}

fn matches_query(needle: &str, fields: &[&str]) -> bool {
    fields
        .iter()
        .any(|field| field.to_ascii_lowercase().contains(needle))
}

fn cell(value: &str) -> String {
    value.replace(['\n', '\r'], " ").replace('|', "\\|")
}

fn with_newline(mut value: String) -> String {
    if !value.ends_with('\n') {
        value.push('\n');
    }
    value
}

#[cfg(test)]
#[path = "index_render_tests.rs"]
mod tests;
