//! The repo-contract task: scan packages and generate or check the per-repo contract files.

use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs, io,
    io::Write,
    path::{Path, PathBuf},
    process::Command,
};

use serde_json::{Value, json};
use sim_codec_index::{IndexCodec, IndexForm};
use sim_cookbook::fnv1a64_hex;
use sim_index_vault_core::VaultProjection;

use crate::{
    generator_options::find_repo_root,
    index_fragment,
    repo_contract_cut::SplitCut,
    repo_contract_render::{ArtifactInputs, artifacts},
    repo_contract_scan::{
        card_index, citizen_classes, input_files, non_citizen_exemptions, recipe_books,
    },
};

#[path = "repo_contract/package_projection.rs"]
mod package_projection;
use package_projection::*;

pub(crate) const GENERATED_MARKER: &str = "<!-- GENERATED BY xtask repo-contract; DO NOT EDIT. -->";
pub(crate) const GENERATOR: &str = "xtask repo-contract v1";

/// Summary of a `repo-contract` run.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct RepoContractReport {
    /// Number of workspace packages described.
    pub packages: usize,
    /// Number of generated contract artifacts updated.
    pub artifacts_changed: usize,
}

#[derive(Debug)]
pub(crate) struct RepoContractOptions {
    pub(crate) repo: PathBuf,
    pub(crate) check: bool,
    pub(crate) emission: Option<EmissionOptions>,
}

#[derive(Debug)]
pub(crate) struct EmissionOptions {
    pub(crate) names: Vec<String>,
    pub(crate) out_dir: PathBuf,
}

const CONTRACT_ARTIFACT_NAMES: [&str; 11] = [
    "card-index.json",
    "card-index.md",
    "feature-map.json",
    "feature-map.md",
    "provenance.json",
    "repo-contract.json",
    "repo-contract.md",
    "rustdoc-index.json",
    "rustdoc-index.md",
    "sim-index-fragment.claims.sx",
    "sim-index-fragment.sx",
];

pub(crate) fn parse_options(args: &[String]) -> Result<RepoContractOptions, String> {
    let usage = "usage: xtask repo-contract [--check] [--repo <path>] [--emit <artifact>... --out-dir <path>]";
    let mut repo = None;
    let mut check = false;
    let mut names = Vec::new();
    let mut out_dir = None;
    let mut index = 2;
    while index < args.len() {
        match args[index].as_str() {
            "--check" => check = true,
            "--repo" | "--emit" | "--out-dir" => {
                let flag = args[index].as_str();
                index += 1;
                let value = args
                    .get(index)
                    .ok_or_else(|| format!("{flag} requires a value\n{usage}"))?;
                match flag {
                    "--repo" => repo = Some(PathBuf::from(value)),
                    "--emit" => names.push(value.clone()),
                    _ => out_dir = Some(PathBuf::from(value)),
                }
            }
            "-h" | "--help" => return Err(usage.to_owned()),
            other => return Err(format!("unknown repo-contract argument `{other}`\n{usage}")),
        }
        index += 1;
    }
    if check && (!names.is_empty() || out_dir.is_some()) {
        return Err(format!(
            "--check and --emit are mutually exclusive\n{usage}"
        ));
    }
    if names.is_empty() && out_dir.is_some() {
        return Err(format!("--out-dir requires --emit\n{usage}"));
    }
    let emission = if names.is_empty() {
        None
    } else {
        let out_dir = out_dir.ok_or_else(|| format!("--emit requires --out-dir\n{usage}"))?;
        let mut unique = BTreeSet::new();
        for name in &names {
            if !unique.insert(name.clone()) {
                return Err(format!("duplicate repo-contract artifact `{name}`"));
            }
            if !CONTRACT_ARTIFACT_NAMES.contains(&name.as_str()) {
                return Err(format!("unknown repo-contract artifact `{name}`"));
            }
        }
        Some(EmissionOptions { names, out_dir })
    };
    let start = match repo {
        Some(path) => path.canonicalize().map_err(display_io)?,
        None => env::current_dir().map_err(display_io)?,
    };
    Ok(RepoContractOptions {
        repo: find_repo_root(&start)?,
        check,
        emission,
    })
}

#[derive(Debug, Clone)]
pub(crate) struct PackageContract {
    pub(crate) name: String,
    pub(crate) crate_name: String,
    pub(crate) manifest: String,
    pub(crate) root: String,
    pub(crate) group: String,
    pub(crate) publish: String,
    pub(crate) description: String,
    pub(crate) target_kinds: Vec<String>,
    pub(crate) targets: Vec<Value>,
    pub(crate) dependencies: Vec<Value>,
    pub(crate) source_dependencies: Vec<SourceDependency>,
    pub(crate) features: Vec<Value>,
    pub(crate) rustdoc_summary: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct SourceDependency {
    pub(crate) package: String,
    pub(crate) crate_name: String,
    pub(crate) kind: String,
}

/// Generates the per-repo contract files for the current repository; with
/// `check` true it instead verifies they are current and fails when they are
/// stale. Returns the run summary.
pub fn repo_contract(check: bool) -> Result<RepoContractReport, String> {
    let repo = find_repo_root(&std::env::current_dir().map_err(display_io)?)?;
    repo_contract_for_repo(check, &repo)
}

pub(crate) fn repo_contract_for_repo(
    check: bool,
    repo: &Path,
) -> Result<RepoContractReport, String> {
    let repo = repo.canonicalize().map_err(display_io)?;
    let artifacts = contract_artifacts(&repo)?;
    let package_count = artifacts.package_count;
    let generated_dir = repo.join("docs/generated");
    if !check {
        fs::create_dir_all(&generated_dir).map_err(display_io)?;
    }

    let mut report = RepoContractReport {
        packages: package_count,
        artifacts_changed: 0,
    };
    for (name, content) in artifacts.files {
        if name == "sim-index-fragment.claims.sx" {
            continue;
        }
        write_or_check(&generated_dir.join(name), &content, check, &mut report)?;
    }
    Ok(report)
}

pub(crate) struct ContractArtifacts {
    pub(crate) package_count: usize,
    pub(crate) files: BTreeMap<&'static str, String>,
}

pub(crate) fn contract_artifacts(repo: &Path) -> Result<ContractArtifacts, String> {
    let repo = repo.canonicalize().map_err(display_io)?;
    let repo = repo.as_path();
    let metadata = cargo_metadata(repo)?;
    let workspace_names = workspace_package_names(&metadata)?;
    let cut = crate::repo_contract_cut::load_or_derive_split_cut(repo, &workspace_names)?;
    let packages = workspace_packages(repo, &metadata, &cut)?;
    validate_cut(&packages, &cut)?;

    let package_groups = packages
        .iter()
        .map(|package| (package.name.clone(), package.group.clone()))
        .collect::<BTreeMap<_, _>>();
    let citizens = citizen_classes(repo);
    let exemptions = non_citizen_exemptions(repo);
    let recipes = recipe_books(repo, &package_groups);
    let cards = card_index(repo, &package_groups);
    let provenance = provenance(repo)?;
    let index_fragment = index_fragment::artifact(repo, &packages, &cards)?;
    let mut files = artifacts(ArtifactInputs {
        packages: &packages,
        cut: &cut,
        citizens: &citizens,
        exemptions: &exemptions,
        recipes: &recipes,
        cards: &cards,
        provenance: &provenance,
        index_fragment: &index_fragment,
    })?;
    files.insert(
        "sim-index-fragment.claims.sx",
        fragment_certificate_artifact(&index_fragment)?,
    );

    Ok(ContractArtifacts {
        package_count: packages.len(),
        files,
    })
}

fn fragment_certificate_artifact(fragment: &str) -> Result<String, String> {
    let doc = IndexCodec
        .decode_fragment(IndexForm::Sx, fragment)
        .map_err(|err| format!("decode generated index fragment for claims: {err}"))?;
    let projection = VaultProjection::project_fragment(&doc)
        .map_err(|err| format!("certify generated index fragment: {err}"))?;
    let certificate = projection.certificate();
    let claims = certificate.local_claims();
    if !claims.is_closed() {
        return Err("generated fragment claim certificate did not close".to_owned());
    }
    let mut out = format!(
        "(fragment-certificate [schema {:?}] [generated-by {:?}] [visibility {:?}] [row-count {}] [claims (\n",
        certificate.metadata().schema,
        certificate.metadata().generated_by,
        certificate.metadata().visibility,
        claims.primary().len()
    );
    for (row, site) in claims.primary() {
        out.push_str(&format!(
            "  (primary [row {:?}] [note {:?}] [section {:?}])\n",
            row.diagnostic_key(),
            site.note.as_str(),
            site.section
        ));
    }
    out.push_str(")])\n");
    Ok(out)
}

pub(crate) fn emit_contract_artifacts(
    repo: &Path,
    names: &[String],
    out_dir: &Path,
) -> Result<RepoContractReport, String> {
    validate_preopened_directory(out_dir)?;
    let out_dir = out_dir.canonicalize().map_err(display_io)?;
    let artifacts = contract_artifacts(repo)?;
    for name in names {
        let content = artifacts
            .files
            .get(name.as_str())
            .ok_or_else(|| format!("unknown repo-contract artifact `{name}`"))?;
        atomic_write(&out_dir, name, content.as_bytes())?;
    }
    Ok(RepoContractReport {
        packages: artifacts.package_count,
        artifacts_changed: names.len(),
    })
}

fn validate_preopened_directory(path: &Path) -> Result<(), String> {
    let metadata = fs::symlink_metadata(path).map_err(display_io)?;
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Err(format!(
            "output directory must be a preopened real directory: {}",
            path.display()
        ));
    }
    Ok(())
}

fn atomic_write(dir: &Path, name: &str, bytes: &[u8]) -> Result<(), String> {
    let target = dir.join(name);
    if let Ok(metadata) = fs::symlink_metadata(&target)
        && (metadata.file_type().is_symlink() || !metadata.is_file())
    {
        return Err(format!(
            "refusing non-file output target: {}",
            target.display()
        ));
    }
    let stage = dir.join(format!(".{name}.sim-stage-{}", std::process::id()));
    let mut file = fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&stage)
        .map_err(|err| format!("create atomic output stage {}: {err}", stage.display()))?;
    let result = (|| {
        file.write_all(bytes).map_err(display_io)?;
        file.sync_all().map_err(display_io)?;
        fs::rename(&stage, &target).map_err(display_io)
    })();
    if result.is_err() {
        let _ = fs::remove_file(&stage);
    }
    result
}

fn cargo_metadata(repo: &Path) -> Result<Value, String> {
    let output = Command::new("cargo")
        .args([
            "metadata",
            "--format-version",
            "1",
            "--all-features",
            "--no-deps",
        ])
        .current_dir(repo)
        .output()
        .map_err(display_io)?;
    if !output.status.success() {
        return Err(format!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    serde_json::from_slice(&output.stdout).map_err(|err| format!("parse cargo metadata: {err}"))
}

fn workspace_packages(
    repo: &Path,
    metadata: &Value,
    cut: &SplitCut,
) -> Result<Vec<PackageContract>, String> {
    let member_ids = metadata["workspace_members"]
        .as_array()
        .ok_or("cargo metadata missing workspace_members")?
        .iter()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    let workspace_names = metadata["packages"]
        .as_array()
        .ok_or("cargo metadata missing packages")?
        .iter()
        .filter_map(|package| {
            let id = package["id"].as_str()?;
            member_ids
                .contains(id)
                .then(|| package["name"].as_str())
                .flatten()
        })
        .collect::<BTreeSet<_>>();

    let mut packages = Vec::new();
    for package in metadata["packages"].as_array().unwrap_or(&Vec::new()) {
        let Some(id) = package["id"].as_str() else {
            continue;
        };
        if !member_ids.contains(id) {
            continue;
        }
        let name = package["name"]
            .as_str()
            .ok_or("cargo metadata package missing name")?
            .to_owned();
        let manifest = PathBuf::from(
            package["manifest_path"]
                .as_str()
                .ok_or("cargo metadata package missing manifest_path")?,
        );
        let root = manifest
            .parent()
            .ok_or_else(|| format!("manifest has no parent: {}", manifest.display()))?;
        let group = cut
            .package_groups
            .get(&name)
            .ok_or_else(|| format!("{name} is missing from the repo contract cut"))?
            .clone();
        packages.push(PackageContract {
            crate_name: preferred_crate_name(package).unwrap_or(&name).to_owned(),
            target_kinds: target_kinds(package),
            targets: targets(repo, package)?,
            dependencies: dependencies(package, &workspace_names),
            source_dependencies: source_dependencies(package),
            features: features(package, &workspace_names),
            rustdoc_summary: docs_summary(package).unwrap_or_else(|| description(package)),
            publish: publish(package),
            description: description(package),
            manifest: rel_path(repo, &manifest)?,
            root: rel_path(repo, root)?,
            group,
            name,
        });
    }
    packages.sort_by(|left, right| left.name.cmp(&right.name));
    Ok(packages)
}

fn source_dependencies(package: &Value) -> Vec<SourceDependency> {
    let mut dependencies = package["dependencies"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|dependency| {
            let package = dependency["name"].as_str()?;
            let kind = dependency["kind"].as_str().unwrap_or("normal");
            (kind == "normal").then(|| SourceDependency {
                package: package.to_owned(),
                crate_name: dependency["rename"]
                    .as_str()
                    .unwrap_or(package)
                    .replace('-', "_"),
                kind: kind.to_owned(),
            })
        })
        .collect::<Vec<_>>();
    dependencies.sort_by(|left, right| {
        left.package
            .cmp(&right.package)
            .then(left.crate_name.cmp(&right.crate_name))
    });
    dependencies.dedup();
    dependencies
}

fn workspace_package_names(metadata: &Value) -> Result<BTreeSet<String>, String> {
    let member_ids = metadata["workspace_members"]
        .as_array()
        .ok_or("cargo metadata missing workspace_members")?
        .iter()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    Ok(metadata["packages"]
        .as_array()
        .ok_or("cargo metadata missing packages")?
        .iter()
        .filter_map(|package| {
            let id = package["id"].as_str()?;
            member_ids
                .contains(id)
                .then(|| package["name"].as_str())
                .flatten()
                .map(str::to_owned)
        })
        .collect())
}

fn validate_cut(packages: &[PackageContract], cut: &SplitCut) -> Result<(), String> {
    let workspace = packages
        .iter()
        .map(|package| package.name.as_str())
        .collect::<BTreeSet<_>>();
    for package in cut.package_groups.keys() {
        if !workspace.contains(package.as_str()) {
            return Err(format!(
                "repo contract cut references non-workspace package {package}"
            ));
        }
    }
    Ok(())
}

fn provenance(repo: &Path) -> Result<Value, String> {
    let preserved = preserved_provenance(repo);
    let inputs = input_files(repo);
    let input_paths = inputs
        .iter()
        .map(|path| rel_path(repo, path))
        .collect::<Result<Vec<_>, _>>()?;
    let workspace_hash = stable_hash(repo, &inputs);
    let source_commit = preserved_source_commit(&preserved, &workspace_hash)
        .or_else(|| git_output(repo, &["rev-parse", "HEAD"]))
        .ok_or_else(|| "git rev-parse HEAD did not return a commit".to_owned())?;
    let source_remote = public_origin(repo)?;
    Ok(json!({
        "schema": "sim.provenance.v1",
        "repo": repo_name(repo),
        "source_commit": source_commit,
        "source_remote": source_remote,
        "generated_by": "cargo run -p xtask -- simdoc",
        "api_docs": "target/doc/",
        "generator": GENERATOR,
        "generation_timestamp": preserved
            .get("generation_timestamp")
            .and_then(Value::as_str)
            .map(str::to_owned)
            .or_else(|| git_output(repo, &["show", "-s", "--format=%cI", "HEAD"]))
            .unwrap_or_else(|| "unknown".to_owned()),
        "git_commit": source_commit,
        "workspace_hash": workspace_hash,
        "workspace_hash_algorithm": "fnv1a64",
        "workspace_hash_input_count": input_paths.len(),
        "workspace_hash_inputs": input_paths,
        "validation_commands": [
            "cargo fmt --all --check",
            "cargo test",
            "cargo clippy --all-targets -- -D warnings",
            "cargo doc --no-deps",
            "cargo run -p xtask -- simdoc --check",
            "cargo run -p xtask -- check-file-sizes",
            "cargo run -p xtask -- repo-contract --check --repo .",
            "cargo run -p xtask -- validation-matrix --check --repo .",
            "cargo run -p xtask -- crate-catalog --check --repo ."
        ],
    }))
}

fn preserved_source_commit(preserved: &Value, workspace_hash: &str) -> Option<String> {
    let preserved_hash = preserved.get("workspace_hash").and_then(Value::as_str)?;
    if preserved_hash != workspace_hash {
        return None;
    }
    preserved
        .get("source_commit")
        .or_else(|| preserved.get("git_commit"))
        .and_then(Value::as_str)
        .filter(|commit| !commit.is_empty())
        .map(str::to_owned)
}

fn repo_name(repo: &Path) -> String {
    repo.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("REPO_NAME")
        .to_owned()
}

fn public_origin(repo: &Path) -> Result<String, String> {
    let origin = git_output(repo, &["config", "--get", "remote.origin.url"])
        .ok_or_else(|| "git remote origin url is not configured".to_owned())?;
    sanitize_origin_url(&origin)
}

fn sanitize_origin_url(origin: &str) -> Result<String, String> {
    let ssh_github_prefix = concat!("git", "@", "github.com:");
    let mut url = if let Some(rest) = origin.strip_prefix(ssh_github_prefix) {
        format!("https://github.com/{rest}")
    } else if let Some(rest) = origin.strip_prefix("http://github.com/") {
        format!("https://github.com/{rest}")
    } else {
        origin.to_owned()
    };
    if let Some(rest) = url.strip_suffix(".git") {
        url = rest.to_owned();
    }
    if url.starts_with("https://github.com/") && !url.contains('\\') {
        Ok(url)
    } else {
        Err(format!(
            "remote origin is not a public GitHub URL: {origin}"
        ))
    }
}

fn preserved_provenance(repo: &Path) -> Value {
    let path = repo.join("docs/generated/provenance.json");
    fs::read_to_string(path)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
        .unwrap_or_else(|| json!({}))
}

fn write_or_check(
    path: &Path,
    expected: &str,
    check: bool,
    report: &mut RepoContractReport,
) -> Result<(), String> {
    let current = fs::read_to_string(path).unwrap_or_default();
    if current == expected {
        return Ok(());
    }
    if check {
        return Err(format!(
            "{} is stale; run `cargo run -p xtask -- repo-contract`",
            path.display()
        ));
    }
    fs::write(path, expected).map_err(display_io)?;
    report.artifacts_changed += 1;
    Ok(())
}

#[cfg(test)]
#[path = "repo_contract_tests.rs"]
mod tests;
