//! The repo-contract task: scan packages and generate or check the per-repo contract files.

use std::{
    collections::{BTreeMap, BTreeSet},
    fs, io,
    path::{Path, PathBuf},
    process::Command,
};

use serde_json::{Value, json};
use sim_cookbook::fnv1a64_hex;

use crate::{
    generator_options::find_repo_root,
    index_fragment,
    repo_contract_cut::SplitCut,
    repo_contract_render::{ArtifactInputs, artifacts},
    repo_contract_scan::{
        card_index, citizen_classes, input_files, non_citizen_exemptions, recipe_books,
    },
};

pub(crate) const GENERATED_MARKER: &str = "<!-- GENERATED BY xtask repo-contract; DO NOT EDIT. -->";
pub(crate) const GENERATOR: &str = "xtask repo-contract v1";

/// Summary of a `repo-contract` run.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct RepoContractReport {
    /// Number of workspace packages described.
    pub packages: usize,
    /// Number of generated contract artifacts updated.
    pub artifacts_changed: usize,
}

#[derive(Debug, Clone)]
pub(crate) struct PackageContract {
    pub(crate) name: String,
    pub(crate) crate_name: String,
    pub(crate) manifest: String,
    pub(crate) root: String,
    pub(crate) group: String,
    pub(crate) publish: String,
    pub(crate) description: String,
    pub(crate) target_kinds: Vec<String>,
    pub(crate) targets: Vec<Value>,
    pub(crate) dependencies: Vec<Value>,
    pub(crate) features: Vec<Value>,
    pub(crate) rustdoc_summary: String,
}

/// Generates the per-repo contract files for the current repository; with
/// `check` true it instead verifies they are current and fails when they are
/// stale. Returns the run summary.
pub fn repo_contract(check: bool) -> Result<RepoContractReport, String> {
    let repo = find_repo_root(&std::env::current_dir().map_err(display_io)?)?;
    repo_contract_for_repo(check, &repo)
}

pub(crate) fn repo_contract_for_repo(
    check: bool,
    repo: &Path,
) -> Result<RepoContractReport, String> {
    let artifacts = contract_artifacts(repo)?;
    let package_count = artifacts.package_count;
    let generated_dir = repo.join("docs/generated");
    if !check {
        fs::create_dir_all(&generated_dir).map_err(display_io)?;
    }

    let mut report = RepoContractReport {
        packages: package_count,
        artifacts_changed: 0,
    };
    for (name, content) in artifacts.files {
        write_or_check(&generated_dir.join(name), &content, check, &mut report)?;
    }
    Ok(report)
}

pub(crate) struct ContractArtifacts {
    pub(crate) package_count: usize,
    pub(crate) files: BTreeMap<&'static str, String>,
}

pub(crate) fn contract_artifacts(repo: &Path) -> Result<ContractArtifacts, String> {
    let metadata = cargo_metadata(repo)?;
    let workspace_names = workspace_package_names(&metadata)?;
    let cut = crate::repo_contract_cut::load_or_derive_split_cut(repo, &workspace_names)?;
    let packages = workspace_packages(repo, &metadata, &cut)?;
    validate_cut(&packages, &cut)?;

    let package_groups = packages
        .iter()
        .map(|package| (package.name.clone(), package.group.clone()))
        .collect::<BTreeMap<_, _>>();
    let citizens = citizen_classes(repo);
    let exemptions = non_citizen_exemptions(repo);
    let recipes = recipe_books(repo, &package_groups);
    let cards = card_index(repo, &package_groups);
    let provenance = provenance(repo)?;
    let index_fragment = index_fragment::artifact(repo, &packages, &cards)?;
    let files = artifacts(ArtifactInputs {
        packages: &packages,
        cut: &cut,
        citizens: &citizens,
        exemptions: &exemptions,
        recipes: &recipes,
        cards: &cards,
        provenance: &provenance,
        index_fragment: &index_fragment,
    })?;

    Ok(ContractArtifacts {
        package_count: packages.len(),
        files,
    })
}

fn cargo_metadata(repo: &Path) -> Result<Value, String> {
    let output = Command::new("cargo")
        .args([
            "metadata",
            "--format-version",
            "1",
            "--all-features",
            "--no-deps",
        ])
        .current_dir(repo)
        .output()
        .map_err(display_io)?;
    if !output.status.success() {
        return Err(format!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    serde_json::from_slice(&output.stdout).map_err(|err| format!("parse cargo metadata: {err}"))
}

fn workspace_packages(
    repo: &Path,
    metadata: &Value,
    cut: &SplitCut,
) -> Result<Vec<PackageContract>, String> {
    let member_ids = metadata["workspace_members"]
        .as_array()
        .ok_or("cargo metadata missing workspace_members")?
        .iter()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    let workspace_names = metadata["packages"]
        .as_array()
        .ok_or("cargo metadata missing packages")?
        .iter()
        .filter_map(|package| {
            let id = package["id"].as_str()?;
            member_ids
                .contains(id)
                .then(|| package["name"].as_str())
                .flatten()
        })
        .collect::<BTreeSet<_>>();

    let mut packages = Vec::new();
    for package in metadata["packages"].as_array().unwrap_or(&Vec::new()) {
        let Some(id) = package["id"].as_str() else {
            continue;
        };
        if !member_ids.contains(id) {
            continue;
        }
        let name = package["name"]
            .as_str()
            .ok_or("cargo metadata package missing name")?
            .to_owned();
        let manifest = PathBuf::from(
            package["manifest_path"]
                .as_str()
                .ok_or("cargo metadata package missing manifest_path")?,
        );
        let root = manifest
            .parent()
            .ok_or_else(|| format!("manifest has no parent: {}", manifest.display()))?;
        let group = cut
            .package_groups
            .get(&name)
            .ok_or_else(|| format!("{name} is missing from the repo contract cut"))?
            .clone();
        packages.push(PackageContract {
            crate_name: preferred_crate_name(package).unwrap_or(&name).to_owned(),
            target_kinds: target_kinds(package),
            targets: targets(repo, package)?,
            dependencies: dependencies(package, &workspace_names),
            features: features(package, &workspace_names),
            rustdoc_summary: docs_summary(package).unwrap_or_else(|| description(package)),
            publish: publish(package),
            description: description(package),
            manifest: rel_path(repo, &manifest)?,
            root: rel_path(repo, root)?,
            group,
            name,
        });
    }
    packages.sort_by(|left, right| left.name.cmp(&right.name));
    Ok(packages)
}

fn workspace_package_names(metadata: &Value) -> Result<BTreeSet<String>, String> {
    let member_ids = metadata["workspace_members"]
        .as_array()
        .ok_or("cargo metadata missing workspace_members")?
        .iter()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    Ok(metadata["packages"]
        .as_array()
        .ok_or("cargo metadata missing packages")?
        .iter()
        .filter_map(|package| {
            let id = package["id"].as_str()?;
            member_ids
                .contains(id)
                .then(|| package["name"].as_str())
                .flatten()
                .map(str::to_owned)
        })
        .collect())
}

fn validate_cut(packages: &[PackageContract], cut: &SplitCut) -> Result<(), String> {
    let workspace = packages
        .iter()
        .map(|package| package.name.as_str())
        .collect::<BTreeSet<_>>();
    for package in cut.package_groups.keys() {
        if !workspace.contains(package.as_str()) {
            return Err(format!(
                "repo contract cut references non-workspace package {package}"
            ));
        }
    }
    Ok(())
}

fn provenance(repo: &Path) -> Result<Value, String> {
    let preserved = preserved_provenance(repo);
    let inputs = input_files(repo);
    let input_paths = inputs
        .iter()
        .map(|path| rel_path(repo, path))
        .collect::<Result<Vec<_>, _>>()?;
    let workspace_hash = stable_hash(repo, &inputs);
    let source_commit = preserved_source_commit(&preserved, &workspace_hash)
        .or_else(|| git_output(repo, &["rev-parse", "HEAD"]))
        .ok_or_else(|| "git rev-parse HEAD did not return a commit".to_owned())?;
    let source_remote = public_origin(repo)?;
    Ok(json!({
        "schema": "sim.provenance.v1",
        "repo": repo_name(repo),
        "source_commit": source_commit,
        "source_remote": source_remote,
        "generated_by": "cargo run -p xtask -- simdoc",
        "api_docs": "target/doc/",
        "generator": GENERATOR,
        "generation_timestamp": preserved
            .get("generation_timestamp")
            .and_then(Value::as_str)
            .map(str::to_owned)
            .or_else(|| git_output(repo, &["show", "-s", "--format=%cI", "HEAD"]))
            .unwrap_or_else(|| "unknown".to_owned()),
        "git_commit": source_commit,
        "workspace_hash": workspace_hash,
        "workspace_hash_algorithm": "fnv1a64",
        "workspace_hash_input_count": input_paths.len(),
        "workspace_hash_inputs": input_paths,
        "validation_commands": [
            "cargo fmt --all --check",
            "cargo test",
            "cargo clippy --all-targets -- -D warnings",
            "cargo doc --no-deps",
            "cargo run -p xtask -- simdoc --check",
            "cargo run -p xtask -- check-file-sizes",
            "cargo run -p xtask -- repo-contract --check --repo .",
            "cargo run -p xtask -- validation-matrix --check --repo .",
            "cargo run -p xtask -- crate-catalog --check --repo ."
        ],
    }))
}

fn preserved_source_commit(preserved: &Value, workspace_hash: &str) -> Option<String> {
    let preserved_hash = preserved.get("workspace_hash").and_then(Value::as_str)?;
    if preserved_hash != workspace_hash {
        return None;
    }
    preserved
        .get("source_commit")
        .or_else(|| preserved.get("git_commit"))
        .and_then(Value::as_str)
        .filter(|commit| !commit.is_empty())
        .map(str::to_owned)
}

fn repo_name(repo: &Path) -> String {
    repo.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("REPO_NAME")
        .to_owned()
}

fn public_origin(repo: &Path) -> Result<String, String> {
    let origin = git_output(repo, &["config", "--get", "remote.origin.url"])
        .ok_or_else(|| "git remote origin url is not configured".to_owned())?;
    sanitize_origin_url(&origin)
}

fn sanitize_origin_url(origin: &str) -> Result<String, String> {
    let ssh_github_prefix = concat!("git", "@", "github.com:");
    let mut url = if let Some(rest) = origin.strip_prefix(ssh_github_prefix) {
        format!("https://github.com/{rest}")
    } else if let Some(rest) = origin.strip_prefix("http://github.com/") {
        format!("https://github.com/{rest}")
    } else {
        origin.to_owned()
    };
    if let Some(rest) = url.strip_suffix(".git") {
        url = rest.to_owned();
    }
    if url.starts_with("https://github.com/") && !url.contains('\\') {
        Ok(url)
    } else {
        Err(format!(
            "remote origin is not a public GitHub URL: {origin}"
        ))
    }
}

fn preserved_provenance(repo: &Path) -> Value {
    let path = repo.join("docs/generated/provenance.json");
    fs::read_to_string(path)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
        .unwrap_or_else(|| json!({}))
}

fn write_or_check(
    path: &Path,
    expected: &str,
    check: bool,
    report: &mut RepoContractReport,
) -> Result<(), String> {
    let current = fs::read_to_string(path).unwrap_or_default();
    if current == expected {
        return Ok(());
    }
    if check {
        return Err(format!(
            "{} is stale; run `cargo run -p xtask -- repo-contract`",
            path.display()
        ));
    }
    fs::write(path, expected).map_err(display_io)?;
    report.artifacts_changed += 1;
    Ok(())
}

fn targets(repo: &Path, package: &Value) -> Result<Vec<Value>, String> {
    let mut out = Vec::new();
    for target in package["targets"].as_array().into_iter().flatten() {
        out.push(json!({
            "name": target["name"].as_str().unwrap_or_default(),
            "kind": string_array(&target["kind"]),
            "crate_types": string_array(&target["crate_types"]),
            "src": rel_path(repo, &PathBuf::from(target["src_path"].as_str().unwrap_or_default()))?,
        }));
    }
    Ok(out)
}

fn dependencies(package: &Value, workspace_names: &BTreeSet<&str>) -> Vec<Value> {
    let mut out = Vec::new();
    for dep in package["dependencies"].as_array().into_iter().flatten() {
        let Some(name) = dep["name"].as_str() else {
            continue;
        };
        if dep["source"].is_null() && workspace_names.contains(name) {
            out.push(json!({
                "package": name,
                "kind": dep["kind"].as_str().unwrap_or("normal"),
                "optional": dep["optional"].as_bool().unwrap_or(false),
                "rename": dep["rename"].as_str(),
                "target": dep["target"].as_str(),
            }));
        }
    }
    out.sort_by(|left, right| {
        left["kind"]
            .as_str()
            .cmp(&right["kind"].as_str())
            .then(left["package"].as_str().cmp(&right["package"].as_str()))
    });
    out
}

fn features(package: &Value, workspace_names: &BTreeSet<&str>) -> Vec<Value> {
    let mut out = Vec::new();
    let Some(features) = package["features"].as_object() else {
        return out;
    };
    for (name, edges) in features {
        let raw_edges = string_array(edges);
        let workspace_edges = raw_edges
            .iter()
            .filter_map(|edge| workspace_feature_edge(edge, workspace_names))
            .collect::<Vec<_>>();
        out.push(json!({
            "name": name,
            "edges": raw_edges,
            "workspace_edges": workspace_edges,
        }));
    }
    out
}

fn workspace_feature_edge(edge: &str, workspace_names: &BTreeSet<&str>) -> Option<Value> {
    let without_dep = edge.strip_prefix("dep:").unwrap_or(edge);
    let (package, feature) = without_dep
        .split_once('/')
        .map_or((without_dep, None), |(package, feature)| {
            (package, Some(feature))
        });
    workspace_names.contains(package).then(|| {
        json!({
            "package": package,
            "feature": feature,
        })
    })
}

fn target_kinds(package: &Value) -> Vec<String> {
    package["targets"]
        .as_array()
        .into_iter()
        .flatten()
        .flat_map(|target| string_array(&target["kind"]))
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect()
}

fn preferred_crate_name(package: &Value) -> Option<&str> {
    package["targets"]
        .as_array()?
        .iter()
        .find(|target| {
            string_array(&target["kind"])
                .iter()
                .any(|kind| kind == "lib")
        })
        .or_else(|| package["targets"].as_array()?.first())?["name"]
        .as_str()
}

fn docs_summary(package: &Value) -> Option<String> {
    let target = package["targets"].as_array()?.iter().find(|target| {
        string_array(&target["kind"])
            .iter()
            .any(|kind| kind == "lib" || kind == "bin")
    })?;
    let text = fs::read_to_string(target["src_path"].as_str()?).ok()?;
    let docs = crate_docs(&text);
    let summary = clean_summary(docs.split("\n\n").find(|part| !part.trim().is_empty())?);
    (!summary.is_empty()).then_some(summary)
}

fn crate_docs(text: &str) -> String {
    let mut docs = Vec::new();
    for line in text.lines() {
        let trimmed = line.trim_start();
        if let Some(doc) = trimmed.strip_prefix("//!") {
            docs.push(doc.trim_start().to_owned());
        } else if !trimmed.starts_with("#!") && !trimmed.is_empty() && !docs.is_empty() {
            break;
        }
    }
    docs.join("\n")
}

fn description(package: &Value) -> String {
    package["description"]
        .as_str()
        .map(clean_summary)
        .filter(|summary| !summary.is_empty())
        .unwrap_or_else(|| {
            format!(
                "SIM workspace package for {}.",
                package["name"]
                    .as_str()
                    .unwrap_or("unknown")
                    .replace('-', " ")
            )
        })
}

fn clean_summary(input: &str) -> String {
    input
        .lines()
        .map(str::trim)
        .filter(|line| !line.starts_with('#'))
        .collect::<Vec<_>>()
        .join(" ")
        .replace(['`', '[', ']'], "")
        .chars()
        .map(|ch| if ch.is_ascii() { ch } else { ' ' })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

fn publish(package: &Value) -> String {
    match &package["publish"] {
        Value::Array(registries) if registries.is_empty() => "false",
        Value::Array(_) => "restricted",
        Value::Null => "true",
        _ => "unknown",
    }
    .to_owned()
}

fn string_array(value: &Value) -> Vec<String> {
    value
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .map(str::to_owned)
        .collect()
}

fn rel_path(repo: &Path, path: &Path) -> Result<String, String> {
    Ok(path
        .strip_prefix(repo)
        .unwrap_or(path)
        .to_string_lossy()
        .replace(std::path::MAIN_SEPARATOR, "/"))
}

fn display_io(err: io::Error) -> String {
    err.to_string()
}

fn git_output(repo: &Path, args: &[&str]) -> Option<String> {
    let output = Command::new("git")
        .args(args)
        .current_dir(repo)
        .output()
        .ok()?;
    output
        .status
        .success()
        .then(|| String::from_utf8_lossy(&output.stdout).trim().to_owned())
        .filter(|text| !text.is_empty())
}

fn stable_hash(repo: &Path, paths: &[PathBuf]) -> String {
    let mut bytes = Vec::new();
    for path in paths {
        let rel = rel_path(repo, path).unwrap_or_else(|_| path.to_string_lossy().into_owned());
        bytes.extend_from_slice(rel.as_bytes());
        bytes.push(0);
        if let Ok(file_bytes) = fs::read(path) {
            bytes.extend_from_slice(&file_bytes);
        }
        bytes.push(0);
    }
    fnv1a64_hex(&bytes)
}

#[cfg(test)]
#[path = "repo_contract_tests.rs"]
mod tests;
