//! Rendering of generated contract artifacts for the repo-contract task.

use std::collections::BTreeMap;

use serde_json::{Value, json};

use crate::{
    repo_contract::{GENERATED_MARKER, GENERATOR, PackageContract},
    repo_contract_cut::SplitCut,
};

pub(crate) struct ArtifactInputs<'a> {
    pub(crate) packages: &'a [PackageContract],
    pub(crate) cut: &'a SplitCut,
    pub(crate) citizens: &'a [Value],
    pub(crate) exemptions: &'a [Value],
    pub(crate) recipes: &'a [Value],
    pub(crate) cards: &'a [Value],
    pub(crate) provenance: &'a Value,
    pub(crate) index_fragment: &'a str,
}

pub(crate) fn artifacts(
    input: ArtifactInputs<'_>,
) -> Result<BTreeMap<&'static str, String>, String> {
    let mut map = BTreeMap::new();
    map.insert(
        "repo-contract.json",
        pretty(json!({
            "generator": GENERATOR,
            "package_count": input.packages.len(),
            "group_count": input.cut.groups.len(),
            "card_count": input.cards.len(),
            "citizen_count": input.citizens.len(),
            "non_citizen_exemption_count": input.exemptions.len(),
            "recipe_book_count": input.recipes.len(),
            "groups": input.cut.groups,
            "group_order": input.cut.group_order,
            "packages": input.packages.iter().map(package_json).collect::<Vec<_>>(),
            "cards": input.cards,
            "citizens": input.citizens,
            "non_citizen_exemptions": input.exemptions,
            "recipes": input.recipes,
            "provenance": input.provenance,
        }))?,
    );
    map.insert(
        "repo-contract.md",
        repo_contract_markdown(
            input.packages,
            input.cut,
            input.citizens,
            input.exemptions,
            input.recipes,
            input.cards,
        ),
    );
    map.insert("provenance.json", pretty(input.provenance.clone())?);
    map.insert(
        "rustdoc-index.json",
        pretty(json!({
            "generator": GENERATOR,
            "packages": input.packages.iter().map(rustdoc_json).collect::<Vec<_>>(),
        }))?,
    );
    map.insert("rustdoc-index.md", rustdoc_markdown(input.packages));
    map.insert(
        "card-index.json",
        pretty(json!({
            "generator": GENERATOR,
            "card_count": input.cards.len(),
            "cards": input.cards,
        }))?,
    );
    map.insert("card-index.md", card_markdown(input.cards));
    map.insert(
        "feature-map.json",
        pretty(json!({
            "generator": GENERATOR,
            "packages": input.packages.iter().map(feature_json).collect::<Vec<_>>(),
        }))?,
    );
    map.insert("feature-map.md", feature_markdown(input.packages));
    map.insert("sim-index-fragment.sx", input.index_fragment.to_owned());
    Ok(map)
}

fn package_json(package: &PackageContract) -> Value {
    json!({
        "name": package.name,
        "crate_name": package.crate_name,
        "manifest": package.manifest,
        "root": package.root,
        "group": package.group,
        "publish": package.publish,
        "description": package.description,
        "target_kinds": package.target_kinds,
        "targets": package.targets,
        "dependencies": package.dependencies,
        "features": package.features,
        "rustdoc_summary": package.rustdoc_summary,
    })
}

fn rustdoc_json(package: &PackageContract) -> Value {
    json!({
        "package": package.name,
        "crate_name": package.crate_name,
        "group": package.group,
        "summary": package.rustdoc_summary,
        "manifest": package.manifest,
    })
}

fn feature_json(package: &PackageContract) -> Value {
    json!({
        "package": package.name,
        "group": package.group,
        "features": package.features,
    })
}

fn repo_contract_markdown(
    packages: &[PackageContract],
    cut: &SplitCut,
    citizens: &[Value],
    exemptions: &[Value],
    recipes: &[Value],
    cards: &[Value],
) -> String {
    let mut out =
        format!("# Repository Contract\n\n{GENERATED_MARKER}\n\nGenerated by `{GENERATOR}`.\n\n");
    out.push_str(&format!(
        "- Packages: {}\n- Groups: {}\n- Cards: {}\n- Citizens: {}\n- Non-citizen exemptions: {}\n- Recipe books: {}\n\n",
        packages.len(), cut.groups.len(), cards.len(), citizens.len(), exemptions.len(), recipes.len()
    ));
    out.push_str("| Group | Packages |\n| --- | ---: |\n");
    for group in &cut.group_order {
        out.push_str(&format!(
            "| `{group}` | {} |\n",
            cut.groups.get(group).map_or(0, Vec::len)
        ));
    }
    out.push_str("\n| Package | Group | Publish | Targets | Description |\n| --- | --- | --- | --- | --- |\n");
    for package in packages {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | {} |\n",
            package.name,
            package.group,
            package.publish,
            package.target_kinds.join(", "),
            markdown_cell(&package.description)
        ));
    }
    out
}

fn rustdoc_markdown(packages: &[PackageContract]) -> String {
    let mut out = format!(
        "# Rustdoc Index\n\n{GENERATED_MARKER}\n\n| Package | Group | Summary |\n| --- | --- | --- |\n"
    );
    for package in packages {
        out.push_str(&format!(
            "| `{}` | `{}` | {} |\n",
            package.name,
            package.group,
            markdown_cell(&package.rustdoc_summary)
        ));
    }
    out
}

fn card_markdown(cards: &[Value]) -> String {
    let mut out = format!(
        "# Card Index\n\n{GENERATED_MARKER}\n\n| Card | Kind | Owner | Summary |\n| --- | --- | --- | --- |\n"
    );
    for card in cards {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} |\n",
            card["id"].as_str().unwrap_or_default(),
            card["kind"].as_str().unwrap_or_default(),
            card["owner"].as_str().unwrap_or_default(),
            markdown_cell(card["summary"].as_str().unwrap_or_default())
        ));
    }
    out
}

fn feature_markdown(packages: &[PackageContract]) -> String {
    let mut out = format!(
        "# Feature Map\n\n{GENERATED_MARKER}\n\n| Package | Group | Features | Workspace feature edges |\n| --- | --- | ---: | ---: |\n"
    );
    for package in packages {
        let edge_count = package
            .features
            .iter()
            .map(|feature| feature["workspace_edges"].as_array().map_or(0, Vec::len))
            .sum::<usize>();
        out.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            package.name,
            package.group,
            package.features.len(),
            edge_count
        ));
    }
    out
}

fn pretty(value: Value) -> Result<String, String> {
    let mut out =
        serde_json::to_string_pretty(&value).map_err(|err| format!("serialize json: {err}"))?;
    out.push('\n');
    Ok(out)
}

fn markdown_cell(text: &str) -> String {
    text.replace('|', "\\|")
}
