//! Generated human-doc projection from a repo's SIM Index fragment.

use std::{
    collections::BTreeMap,
    fs,
    path::{Component, Path},
};

use sim_codec_index::{IndexCodec, IndexForm};
use sim_index_core::{DiscoveredSpecimen, FeatureRecord, IndexDoc, SubjectRecord, check_index_doc};

const GENERATED: &str = "<!-- GENERATED BY xtask simdoc; DO NOT EDIT. -->";

pub(crate) fn decode_fragment(source: &str) -> Result<IndexDoc, String> {
    let doc = IndexCodec
        .decode(IndexForm::Sx, source)
        .map_err(|err| format!("decode docs/generated/sim-index-fragment.sx: {err}"))?;
    check_index_doc(&doc)
        .map_err(|err| format!("invalid docs/generated/sim-index-fragment.sx: {err}"))?;
    Ok(doc)
}

pub(crate) fn render_human_readme(
    root: &Path,
    repo: &str,
    recipes: &[String],
    doc: &IndexDoc,
) -> Result<String, String> {
    let mut out = format!(
        "# {repo} Human Docs\n\n{GENERATED}\n\nThis lane contains human-readable guides generated by `xtask simdoc`.\n"
    );
    render_index_backlinks(&mut out, repo, doc);
    render_feature_rows(&mut out, doc);
    render_surface_rows(&mut out, doc);
    render_recipe_rows(&mut out, recipes);
    render_worked_examples(&mut out, root, doc)?;
    Ok(with_single_terminal_newline(out))
}

fn render_index_backlinks(out: &mut String, repo: &str, doc: &IndexDoc) {
    out.push_str("\n## Index Backlinks\n\n");
    out.push_str(
        "This generated lane consumes `docs/generated/sim-index-fragment.sx`. Global index consumers merge that fragment into `docs/index/overview.md`, `docs/index/features.md`, and the package maps.\n\n",
    );
    out.push_str("| Index row | Kind | Title |\n| --- | --- | --- |\n");
    for id in [format!("repo/{repo}"), format!("doc-set/{repo}/generated")] {
        match subject(doc, &id) {
            Some(subject) => out.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                subject.id,
                subject.kind,
                cell(&subject.title)
            )),
            None => out.push_str(&format!("| `{id}` | `missing` |  |\n")),
        }
    }
}

fn render_feature_rows(out: &mut String, doc: &IndexDoc) {
    out.push_str("\n## Feature Rows\n\n");
    if doc.features.is_empty() {
        out.push_str("No feature rows are present in this repository fragment.\n");
        return;
    }
    out.push_str("| Feature | Subject | Specimens | Summary |\n| --- | --- | ---: | --- |\n");
    for feature in &doc.features {
        out.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            feature.id,
            feature.subject,
            feature.specimens.len(),
            cell(&feature.summary)
        ));
    }
}

fn render_surface_rows(out: &mut String, doc: &IndexDoc) {
    out.push_str("\n## Surfaces\n\n");
    if doc.surfaces.is_empty() {
        out.push_str("No surface rows are present in this repository fragment.\n");
        return;
    }
    out.push_str("| Surface | Kind | Subject |\n| --- | --- | --- |\n");
    for surface in &doc.surfaces {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` |\n",
            surface.id, surface.kind, surface.subject
        ));
    }
}

fn render_recipe_rows(out: &mut String, recipes: &[String]) {
    if recipes.is_empty() {
        out.push_str("\nNo recipes were found in this repository.\n");
        return;
    }
    out.push_str("\n## Recipes\n\n");
    for recipe in recipes {
        out.push_str(&format!("- `{recipe}`\n"));
    }
}

fn render_worked_examples(out: &mut String, root: &Path, doc: &IndexDoc) -> Result<(), String> {
    let specimens = specimens_by_id(doc);
    let mut any = false;
    for feature in &doc.features {
        let worked = feature
            .specimens
            .iter()
            .filter_map(|id| specimens.get(id.as_str()).copied())
            .filter(|specimen| specimen.runnable && specimen.checked)
            .collect::<Vec<_>>();
        if worked.is_empty() {
            continue;
        }
        if !any {
            out.push_str("\n## Worked Examples\n\n");
            any = true;
        }
        out.push_str(&format!("### `{}`\n\n", feature.id));
        for specimen in worked {
            render_specimen_source(out, root, feature, specimen)?;
        }
    }
    if !any {
        out.push_str("\n## Worked Examples\n\nNo checked runnable feature specimens are present in this repository fragment.\n");
    }
    Ok(())
}

fn render_specimen_source(
    out: &mut String,
    root: &Path,
    feature: &FeatureRecord,
    specimen: &DiscoveredSpecimen,
) -> Result<(), String> {
    reject_unsafe_relative_path(&specimen.path)?;
    let path = root.join(&specimen.path);
    let text = fs::read_to_string(&path).map_err(|err| {
        format!(
            "read worked example {} for feature {}: {err}",
            path.display(),
            feature.id
        )
    })?;
    out.push_str(&format!(
        "Specimen `{}` is checked by `{}`.\n\n",
        specimen.id,
        specimen.checked_by.as_deref().unwrap_or("validation")
    ));
    out.push_str(&format!("Source `{}`:\n\n", specimen.path));
    out.push_str(&format!(
        "```{}\n",
        language_hint(&specimen.path, specimen.language.as_deref())
    ));
    out.push_str(text.trim_end());
    out.push_str("\n```\n\n");
    Ok(())
}

fn specimens_by_id(doc: &IndexDoc) -> BTreeMap<String, &DiscoveredSpecimen> {
    doc.specimens
        .iter()
        .map(|specimen| (specimen.id.to_string(), specimen))
        .collect()
}

fn subject<'a>(doc: &'a IndexDoc, id: &str) -> Option<&'a SubjectRecord> {
    doc.subjects
        .iter()
        .find(|subject| subject.id.as_str() == id)
}

fn reject_unsafe_relative_path(path: &str) -> Result<(), String> {
    let path = Path::new(path);
    if path.is_absolute()
        || path
            .components()
            .any(|component| matches!(component, Component::ParentDir | Component::RootDir))
    {
        return Err(format!("unsafe specimen path {}", path.display()));
    }
    Ok(())
}

fn language_hint(path: &str, declared: Option<&str>) -> String {
    match Path::new(path)
        .extension()
        .and_then(|extension| extension.to_str())
    {
        Some("rs") => "rust".to_owned(),
        Some("toml") => "toml".to_owned(),
        Some("md") => "markdown".to_owned(),
        Some("siml") => "lisp".to_owned(),
        _ => declared.unwrap_or("text").to_owned(),
    }
}

fn cell(value: &str) -> String {
    value.replace(['\n', '\r'], " ").replace('|', "\\|")
}

fn with_single_terminal_newline(mut value: String) -> String {
    let trimmed = value.trim_end().len();
    value.truncate(trimmed);
    value.push('\n');
    value
}

#[cfg(test)]
mod tests {
    use std::{
        env, fs,
        time::{SystemTime, UNIX_EPOCH},
    };

    use sim_index_core::{
        CanonicalFeatureKey, DiscoveredSpecimen, FeatureId, FeatureRecord, IndexDoc, SpecimenId,
        SubjectId, SubjectRecord, Visibility,
    };

    use super::*;

    #[test]
    fn human_readme_links_index_rows_and_embeds_specimen_source() {
        let root = temp_root("sim-tooling-simdoc-index");
        fs::create_dir_all(root.join("recipes/open")).unwrap();
        fs::write(root.join("recipes/open/recipe.toml"), "title = \"Open\"\n").unwrap();
        let doc = fixture_doc();

        let page = render_human_readme(
            &root,
            "sim-demo",
            &["recipes/open/recipe.toml".to_owned()],
            &doc,
        )
        .unwrap();

        assert!(page.contains("docs/generated/sim-index-fragment.sx"));
        assert!(page.contains("`repo/sim-demo`"));
        assert!(page.contains("## Worked Examples"));
        assert!(page.contains("```toml\ntitle = \"Open\"\n```"));
        assert!(!page.ends_with("\n\n"));

        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn sx_fragment_decodes_to_index_doc() {
        let sx = "(expr:map [anchors ()] [drafts ()] [edges ()] [features ()] [generated-by \"test\"] [routes ()] [schema \"sim.index\"] [specimens ()] [subjects ((expr:map [id \"repo/sim-demo\"] [kind \"repo\"] [title \"sim-demo\"]))] [surfaces ()] [visibility \"public\"])";

        let doc = decode_fragment(sx).unwrap();

        assert_eq!(doc.subjects[0].id.as_str(), "repo/sim-demo");
    }

    fn fixture_doc() -> IndexDoc {
        let mut doc = IndexDoc {
            schema: "sim.index".to_owned(),
            generated_by: "test".to_owned(),
            visibility: Visibility::Public,
            subjects: vec![
                SubjectRecord {
                    id: SubjectId::new("repo/sim-demo"),
                    kind: "repo".to_owned(),
                    title: "sim-demo".to_owned(),
                },
                SubjectRecord {
                    id: SubjectId::new("doc-set/sim-demo/generated"),
                    kind: "doc-set".to_owned(),
                    title: "sim-demo generated docs".to_owned(),
                },
            ],
            anchors: Vec::new(),
            surfaces: Vec::new(),
            specimens: vec![DiscoveredSpecimen {
                id: SpecimenId::new("recipe/sim-demo/open"),
                subject: SubjectId::new("repo/sim-demo"),
                kind: "recipe".to_owned(),
                path: "recipes/open/recipe.toml".to_owned(),
                language: None,
                runnable: true,
                checked: true,
                checked_by: Some("scripts/check-recipes.sh".to_owned()),
                doc_anchor: None,
            }],
            drafts: Vec::new(),
            features: Vec::new(),
            routes: Vec::new(),
            edges: Vec::new(),
        };
        doc.features.push(FeatureRecord {
            id: FeatureId::new("feature/open"),
            key: CanonicalFeatureKey::new("repo/sim-demo/open"),
            subject: SubjectId::new("repo/sim-demo"),
            title: "Open".to_owned(),
            summary: "Opens the demo recipe.".to_owned(),
            anchors: Vec::new(),
            surfaces: Vec::new(),
            specimens: vec![SpecimenId::new("recipe/sim-demo/open")],
            grammar_contracts: Vec::new(),
            doc_anchor: None,
        });
        doc
    }

    fn temp_root(name: &str) -> std::path::PathBuf {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = env::temp_dir().join(format!("{name}-{}-{stamp}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).unwrap();
        root
    }
}
