//! The validation-matrix task: generate or check the validation matrix.

use std::{
    collections::BTreeSet,
    fs, io,
    path::{Path, PathBuf},
    process::Command,
};

use serde_json::Value;

use crate::repo_contract_cut::{CONTRACT_CUT_PATH, SplitCut, parse_split_cut};

const GENERATED_MARKER: &str = "<!-- GENERATED BY xtask validation-matrix; DO NOT EDIT. -->";
const GENERATOR: &str = "xtask validation-matrix v1";
const OUTPUT: &str = "docs/generated/validation-matrix.md";

/// Summary of a `validation-matrix` run.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ValidationMatrixReport {
    /// Number of validation-matrix rows produced.
    pub rows: usize,
    /// Number of generated matrix artifacts updated.
    pub artifacts_changed: usize,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum MatrixMode {
    Normal,
    Slow,
}

#[derive(Clone, Debug)]
struct MatrixRow {
    id: String,
    mode: MatrixMode,
    scope: &'static str,
    subject: String,
    command: String,
    purpose: String,
}

/// Generates the validation matrix for the current repository; with `check`
/// true it instead verifies the matrix is current and fails when it is stale.
/// Returns the run summary.
pub fn validation_matrix(check: bool) -> Result<ValidationMatrixReport, String> {
    let repo = find_repo_root(&std::env::current_dir().map_err(display_io)?)?;
    let metadata = cargo_metadata(&repo)?;
    let cut_text = fs::read_to_string(repo.join(CONTRACT_CUT_PATH)).map_err(display_io)?;
    let cut = parse_split_cut(&cut_text)?;
    let rows = matrix_rows(&metadata, &cut)?;
    let content = render_matrix(&rows, &cut);

    let mut report = ValidationMatrixReport {
        rows: rows.len(),
        artifacts_changed: 0,
    };
    let path = repo.join(OUTPUT);
    if !check && let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(display_io)?;
    }
    write_or_check(&path, &content, check, &mut report)?;
    Ok(report)
}

fn matrix_rows(metadata: &Value, cut: &SplitCut) -> Result<Vec<MatrixRow>, String> {
    let packages = workspace_package_names(metadata)?;
    let root_features = root_feature_names(metadata)?;
    let mut rows = root_rows(&root_features)?;
    rows.extend(group_rows(cut, &packages)?);
    rows.extend(slow_rows());
    Ok(rows)
}

fn root_rows(root_features: &BTreeSet<String>) -> Result<Vec<MatrixRow>, String> {
    let mut rows = vec![
        MatrixRow {
            id: "root-default".to_owned(),
            mode: MatrixMode::Normal,
            scope: "root",
            subject: "default features".to_owned(),
            command: "cargo check -p sim".to_owned(),
            purpose: "Default root build: core, codec-lisp, and numbers-f64.".to_owned(),
        },
        MatrixRow {
            id: "root-no-default".to_owned(),
            mode: MatrixMode::Normal,
            scope: "root",
            subject: "no default features".to_owned(),
            command: "cargo check -p sim --no-default-features".to_owned(),
            purpose: "Minimal root build with no optional package selected.".to_owned(),
        },
        MatrixRow {
            id: "root-all-features".to_owned(),
            mode: MatrixMode::Normal,
            scope: "root",
            subject: "all features".to_owned(),
            command: "cargo check -p sim --all-features".to_owned(),
            purpose: "Full root feature closure remains coherent.".to_owned(),
        },
    ];

    let feature_rows = [
        (
            "root-codecs",
            "codec-*",
            &[
                "codec-lisp",
                "codec-json",
                "codec-binary",
                "codec-binary-base64",
                "codec-chat",
                "codec-mcp",
                "codec-algol",
            ][..],
            "Every root codec family compiles without default features.",
        ),
        (
            "root-standard",
            "standard",
            &["standard"][..],
            "Standard organs and language profiles compile as one family.",
        ),
        (
            "root-skill",
            "skill",
            &["skill"][..],
            "Skill runtime surface compiles without agent or MCP extras.",
        ),
        (
            "root-mcp",
            "mcp",
            &["mcp"][..],
            "MCP runtime surface compiles as a standalone family.",
        ),
        (
            "root-openai-server",
            "openai-server",
            &["openai-server"][..],
            "OpenAI-compatible gateway compiles from the root feature.",
        ),
        (
            "root-stream",
            "stream",
            &[
                "stream-prelude",
                "stream-file",
                "stream-fabric",
                "stream-bridge",
                "stream-host",
            ][..],
            "Portable stream core, file, fabric, bridge, and host surfaces compile together.",
        ),
        (
            "root-rank",
            "rank",
            &["rank"][..],
            "Rank feature family compiles from the root facade.",
        ),
        (
            "root-topology",
            "topology",
            &["topology"][..],
            "Topology feature family compiles from the root facade.",
        ),
        (
            "root-audio-graph",
            "audio-graph-*",
            &["audio-graph-core", "audio-graph-live"][..],
            "Audio graph core and live graph features compile together.",
        ),
        (
            "root-plugin",
            "plugin-*",
            &["plugin-core", "plugin-clap", "plugin-lv2", "plugin-vst3"][..],
            "Portable plugin descriptor/export surfaces compile together.",
        ),
        (
            "root-daw-session",
            "daw-session",
            &["daw-session"][..],
            "DAW session facade compiles from the root feature.",
        ),
        (
            "root-numbers",
            "numbers-*",
            &["numbers-prelude"][..],
            "Numbers prelude compiles the full numeric family closure.",
        ),
        (
            "root-femm",
            "femm",
            &["femm-prelude"][..],
            "FEMM prelude compiles the FEMM family closure.",
        ),
        (
            "root-pitch",
            "pitch",
            &["pitch"][..],
            "Pitch family compiles from the root facade.",
        ),
        (
            "root-midi",
            "midi",
            &["midi"][..],
            "MIDI family compiles from the root facade.",
        ),
        (
            "root-music",
            "music",
            &["music"][..],
            "Music family compiles from the root facade.",
        ),
        (
            "root-sound",
            "sound",
            &["sound"][..],
            "Sound family compiles from the root facade.",
        ),
        (
            "root-web",
            "web",
            &["web-full"][..],
            "Browser/view family compiles through the full web facade.",
        ),
        (
            "root-server",
            "server",
            &["server"][..],
            "Server runtime compiles from the root feature.",
        ),
        (
            "root-agent",
            "agent",
            &["agent"][..],
            "Agent runtime compiles from the root feature.",
        ),
    ];

    for (id, subject, features, purpose) in feature_rows {
        validate_features(root_features, features)?;
        rows.push(MatrixRow {
            id: id.to_owned(),
            mode: MatrixMode::Normal,
            scope: "root-feature",
            subject: subject.to_owned(),
            command: format!(
                "cargo check -p sim --no-default-features --features {}",
                features.join(",")
            ),
            purpose: purpose.to_owned(),
        });
    }
    Ok(rows)
}

fn group_rows(cut: &SplitCut, packages: &BTreeSet<String>) -> Result<Vec<MatrixRow>, String> {
    let mut rows = Vec::new();
    for group in &cut.group_order {
        let group_packages = cut
            .groups
            .get(group)
            .ok_or_else(|| format!("split cut group {group} has no package list"))?;
        let package = representative_package(group, group_packages)
            .ok_or_else(|| format!("split cut group {group} has no package representative"))?;
        if !packages.contains(package) {
            return Err(format!(
                "split cut representative {package} for group {group} is not a workspace package"
            ));
        }
        rows.push(MatrixRow {
            id: format!("group-{group}"),
            mode: MatrixMode::Normal,
            scope: "split-group",
            subject: group.clone(),
            command: format!("cargo check -p {package}"),
            purpose: format!("Representative package `{package}` for repository group `{group}`."),
        });
    }
    Ok(rows)
}

fn representative_package<'a>(group: &str, packages: &'a [String]) -> Option<&'a str> {
    if group == "sdk" {
        return packages
            .iter()
            .find(|package| package.as_str() == "sim-server")
            .or_else(|| packages.first())
            .map(String::as_str);
    }
    packages.first().map(String::as_str)
}

fn slow_rows() -> Vec<MatrixRow> {
    vec![
        MatrixRow {
            id: "slow-benches".to_owned(),
            mode: MatrixMode::Slow,
            scope: "slow",
            subject: "benches".to_owned(),
            command: "cargo check --benches --all-features".to_owned(),
            purpose: "Bench targets compile under the full feature closure.".to_owned(),
        },
        MatrixRow {
            id: "slow-fuzz-compile".to_owned(),
            mode: MatrixMode::Slow,
            scope: "slow",
            subject: "fuzz compile".to_owned(),
            command: "cargo check --manifest-path fuzz/Cargo.toml".to_owned(),
            purpose: "Fuzz harnesses compile; long-running fuzz campaigns remain operator-run."
                .to_owned(),
        },
    ]
}

fn render_matrix(rows: &[MatrixRow], cut: &SplitCut) -> String {
    let normal_count = rows
        .iter()
        .filter(|row| row.mode == MatrixMode::Normal)
        .count();
    let slow_count = rows.len() - normal_count;
    let mut out =
        format!("# Validation Matrix\n\n{GENERATED_MARKER}\n\nGenerated by `{GENERATOR}`.\n\n");
    out.push_str(&format!(
        "- Normal rows: {normal_count}\n- Slow rows: {slow_count}\n- Split groups: {}\n\n",
        cut.group_order.len()
    ));
    out.push_str("Normal mode is run by `./scripts/check-feature-matrix.sh` and is wired into `./scripts/validate.sh`. ");
    out.push_str("Slow mode is run by `./scripts/check-feature-matrix.sh --slow`; it extends normal mode with bench compilation and fuzz-harness compilation. ");
    out.push_str("Fuzz execution campaigns are intentionally excluded because they need operator-selected durations and corpora.\n\n");
    out.push_str("| ID | Mode | Scope | Subject | Command | Purpose |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- |\n");
    for row in rows {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` | {} |\n",
            row.id,
            row.mode.as_str(),
            row.scope,
            markdown_cell(&row.subject),
            markdown_cell(&row.command),
            markdown_cell(&row.purpose)
        ));
    }
    out
}

impl MatrixMode {
    fn as_str(self) -> &'static str {
        match self {
            MatrixMode::Normal => "normal",
            MatrixMode::Slow => "slow",
        }
    }
}

fn validate_features(root_features: &BTreeSet<String>, features: &[&str]) -> Result<(), String> {
    let missing = features
        .iter()
        .filter(|feature| !root_features.contains(**feature))
        .copied()
        .collect::<Vec<_>>();
    if missing.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "validation matrix references missing root feature(s): {}",
            missing.join(", ")
        ))
    }
}

fn workspace_package_names(metadata: &Value) -> Result<BTreeSet<String>, String> {
    let member_ids = metadata["workspace_members"]
        .as_array()
        .ok_or("cargo metadata missing workspace_members")?
        .iter()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    Ok(metadata["packages"]
        .as_array()
        .ok_or("cargo metadata missing packages")?
        .iter()
        .filter_map(|package| {
            let id = package["id"].as_str()?;
            member_ids
                .contains(id)
                .then(|| package["name"].as_str())
                .flatten()
                .map(str::to_owned)
        })
        .collect())
}

fn root_feature_names(metadata: &Value) -> Result<BTreeSet<String>, String> {
    let member_ids = metadata["workspace_members"]
        .as_array()
        .ok_or("cargo metadata missing workspace_members")?
        .iter()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    let package = metadata["packages"]
        .as_array()
        .ok_or("cargo metadata missing packages")?
        .iter()
        .find(|package| {
            package["name"].as_str() == Some("sim")
                && package["id"]
                    .as_str()
                    .is_some_and(|id| member_ids.contains(id))
        })
        .ok_or("cargo metadata missing root sim package")?;
    Ok(package["features"]
        .as_object()
        .ok_or("root sim package missing features")?
        .keys()
        .cloned()
        .collect())
}

fn cargo_metadata(repo: &Path) -> Result<Value, String> {
    let output = Command::new("cargo")
        .args([
            "metadata",
            "--format-version",
            "1",
            "--all-features",
            "--no-deps",
        ])
        .current_dir(repo)
        .output()
        .map_err(display_io)?;
    if !output.status.success() {
        return Err(format!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    serde_json::from_slice(&output.stdout).map_err(|err| format!("parse cargo metadata: {err}"))
}

fn write_or_check(
    path: &Path,
    content: &str,
    check: bool,
    report: &mut ValidationMatrixReport,
) -> Result<(), String> {
    match fs::read_to_string(path) {
        Ok(existing) if existing == content => Ok(()),
        Ok(_) | Err(_) if check => Err(format!(
            "{} is stale; run cargo run -p xtask -- validation-matrix",
            path.display()
        )),
        Ok(_) | Err(_) => {
            fs::write(path, content).map_err(display_io)?;
            report.artifacts_changed += 1;
            Ok(())
        }
    }
}

fn find_repo_root(start: &Path) -> Result<PathBuf, String> {
    let mut current = start;
    loop {
        if current.join("Cargo.toml").is_file() && current.join("AGENTS.md").is_file() {
            return Ok(current.to_path_buf());
        }
        current = current
            .parent()
            .ok_or_else(|| format!("could not find repo root from {}", start.display()))?;
    }
}

fn markdown_cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn display_io(err: io::Error) -> String {
    err.to_string()
}
