//! The validation-matrix task: generate or check the validation matrix.

use std::{collections::BTreeSet, fs, io, path::Path, process::Command};

use serde_json::Value;

use crate::{
    generator_options::find_repo_root,
    repo_contract_cut::{SplitCut, load_or_derive_split_cut},
};

const GENERATED_MARKER: &str = "<!-- GENERATED BY xtask validation-matrix; DO NOT EDIT. -->";
const GENERATOR: &str = "xtask validation-matrix v1";
const OUTPUT: &str = "docs/generated/validation-matrix.md";

/// Summary of a `validation-matrix` run.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ValidationMatrixReport {
    /// Number of validation-matrix rows produced.
    pub rows: usize,
    /// Number of generated matrix artifacts updated.
    pub artifacts_changed: usize,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum MatrixMode {
    Normal,
    Slow,
}

#[derive(Clone, Debug)]
struct MatrixRow {
    id: String,
    mode: MatrixMode,
    scope: &'static str,
    subject: String,
    command: String,
    purpose: String,
}

/// Generates the validation matrix for the current repository; with `check`
/// true it instead verifies the matrix is current and fails when it is stale.
/// Returns the run summary.
pub fn validation_matrix(check: bool) -> Result<ValidationMatrixReport, String> {
    let repo = find_repo_root(&std::env::current_dir().map_err(display_io)?)?;
    validation_matrix_for_repo(check, &repo)
}

pub(crate) fn validation_matrix_for_repo(
    check: bool,
    repo: &Path,
) -> Result<ValidationMatrixReport, String> {
    let metadata = cargo_metadata(repo)?;
    let packages = workspace_package_names(&metadata)?;
    let cut = load_or_derive_split_cut(repo, &packages)?;
    let rows = matrix_rows(repo, &metadata, &cut)?;
    let content = render_matrix(&rows, &cut);

    let mut report = ValidationMatrixReport {
        rows: rows.len(),
        artifacts_changed: 0,
    };
    let path = repo.join(OUTPUT);
    if !check && let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(display_io)?;
    }
    write_or_check(&path, &content, check, &mut report)?;
    Ok(report)
}

fn matrix_rows(repo: &Path, metadata: &Value, cut: &SplitCut) -> Result<Vec<MatrixRow>, String> {
    let packages = workspace_package_names(metadata)?;
    let mut rows = workspace_rows();
    rows.extend(package_feature_rows(metadata)?);
    rows.extend(group_rows(cut, &packages)?);
    rows.extend(slow_rows(repo));
    Ok(rows)
}

fn workspace_rows() -> Vec<MatrixRow> {
    vec![MatrixRow {
        id: "workspace-check".to_owned(),
        mode: MatrixMode::Normal,
        scope: "workspace",
        subject: "workspace".to_owned(),
        command: "cargo check --workspace".to_owned(),
        purpose: "Every workspace member compiles with its default feature set.".to_owned(),
    }]
}

fn package_feature_rows(metadata: &Value) -> Result<Vec<MatrixRow>, String> {
    let mut rows = Vec::new();
    for package in workspace_packages(metadata)? {
        let features = package_features(package);
        if features.is_empty() {
            continue;
        }
        let name = package["name"]
            .as_str()
            .ok_or("cargo metadata package missing name")?;
        rows.push(MatrixRow {
            id: format!("package-{name}-no-default"),
            mode: MatrixMode::Normal,
            scope: "package-feature",
            subject: format!("{name} no default features"),
            command: format!("cargo check -p {name} --no-default-features"),
            purpose: format!("Package `{name}` compiles with default features disabled."),
        });
        rows.push(MatrixRow {
            id: format!("package-{name}-all-features"),
            mode: MatrixMode::Normal,
            scope: "package-feature",
            subject: format!("{name} all features"),
            command: format!("cargo check -p {name} --all-features"),
            purpose: format!("Package `{name}` compiles with every declared feature enabled."),
        });
    }
    Ok(rows)
}

fn group_rows(cut: &SplitCut, packages: &BTreeSet<String>) -> Result<Vec<MatrixRow>, String> {
    let mut rows = Vec::new();
    for group in &cut.group_order {
        let group_packages = cut
            .groups
            .get(group)
            .ok_or_else(|| format!("split cut group {group} has no package list"))?;
        let package = representative_package(group, group_packages)
            .ok_or_else(|| format!("split cut group {group} has no package representative"))?;
        if !packages.contains(package) {
            return Err(format!(
                "split cut representative {package} for group {group} is not a workspace package"
            ));
        }
        rows.push(MatrixRow {
            id: format!("group-{group}"),
            mode: MatrixMode::Normal,
            scope: "split-group",
            subject: group.clone(),
            command: format!("cargo check -p {package}"),
            purpose: format!("Representative package `{package}` for repository group `{group}`."),
        });
    }
    Ok(rows)
}

fn representative_package<'a>(group: &str, packages: &'a [String]) -> Option<&'a str> {
    if group == "sdk" {
        return packages
            .iter()
            .find(|package| package.as_str() == "sim-server")
            .or_else(|| packages.first())
            .map(String::as_str);
    }
    packages.first().map(String::as_str)
}

fn slow_rows(repo: &Path) -> Vec<MatrixRow> {
    let mut rows = vec![MatrixRow {
        id: "slow-benches".to_owned(),
        mode: MatrixMode::Slow,
        scope: "slow",
        subject: "benches".to_owned(),
        command: "cargo check --benches --all-features".to_owned(),
        purpose: "Bench targets compile under the full feature closure.".to_owned(),
    }];
    if repo.join("fuzz/Cargo.toml").is_file() {
        rows.push(MatrixRow {
            id: "slow-fuzz-compile".to_owned(),
            mode: MatrixMode::Slow,
            scope: "slow",
            subject: "fuzz compile".to_owned(),
            command: "cargo check --manifest-path fuzz/Cargo.toml".to_owned(),
            purpose: "Fuzz harnesses compile; long-running fuzz campaigns remain operator-run."
                .to_owned(),
        });
    }
    rows
}

fn render_matrix(rows: &[MatrixRow], cut: &SplitCut) -> String {
    let normal_count = rows
        .iter()
        .filter(|row| row.mode == MatrixMode::Normal)
        .count();
    let slow_count = rows.len() - normal_count;
    let mut out =
        format!("# Validation Matrix\n\n{GENERATED_MARKER}\n\nGenerated by `{GENERATOR}`.\n\n");
    out.push_str(&format!(
        "- Normal rows: {normal_count}\n- Slow rows: {slow_count}\n- Split groups: {}\n\n",
        cut.group_order.len()
    ));
    out.push_str("Normal rows are the fast local validation surface for this repository. ");
    out.push_str("Slow rows extend that surface with targets that are useful before release or broad refactors. ");
    out.push_str("Long-running fuzz execution campaigns are intentionally excluded because they need operator-selected durations and corpora.\n\n");
    out.push_str("| ID | Mode | Scope | Subject | Command | Purpose |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- |\n");
    for row in rows {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` | {} |\n",
            row.id,
            row.mode.as_str(),
            row.scope,
            markdown_cell(&row.subject),
            markdown_cell(&row.command),
            markdown_cell(&row.purpose)
        ));
    }
    out
}

impl MatrixMode {
    fn as_str(self) -> &'static str {
        match self {
            MatrixMode::Normal => "normal",
            MatrixMode::Slow => "slow",
        }
    }
}

fn workspace_package_names(metadata: &Value) -> Result<BTreeSet<String>, String> {
    Ok(workspace_packages(metadata)?
        .into_iter()
        .filter_map(|package| package["name"].as_str().map(str::to_owned))
        .collect())
}

fn workspace_packages(metadata: &Value) -> Result<Vec<&Value>, String> {
    let member_ids = metadata["workspace_members"]
        .as_array()
        .ok_or("cargo metadata missing workspace_members")?
        .iter()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    Ok(metadata["packages"]
        .as_array()
        .ok_or("cargo metadata missing packages")?
        .iter()
        .filter(|package| {
            package["id"]
                .as_str()
                .is_some_and(|id| member_ids.contains(id))
        })
        .collect())
}

fn package_features(package: &Value) -> BTreeSet<String> {
    package["features"]
        .as_object()
        .into_iter()
        .flat_map(|features| features.keys())
        .cloned()
        .collect()
}

fn cargo_metadata(repo: &Path) -> Result<Value, String> {
    let output = Command::new("cargo")
        .args([
            "metadata",
            "--format-version",
            "1",
            "--all-features",
            "--no-deps",
        ])
        .current_dir(repo)
        .output()
        .map_err(display_io)?;
    if !output.status.success() {
        return Err(format!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    serde_json::from_slice(&output.stdout).map_err(|err| format!("parse cargo metadata: {err}"))
}

fn write_or_check(
    path: &Path,
    content: &str,
    check: bool,
    report: &mut ValidationMatrixReport,
) -> Result<(), String> {
    match fs::read_to_string(path) {
        Ok(existing) if existing == content => Ok(()),
        Ok(_) | Err(_) if check => Err(format!(
            "{} is stale; run cargo run -p xtask -- validation-matrix",
            path.display()
        )),
        Ok(_) | Err(_) => {
            fs::write(path, content).map_err(display_io)?;
            report.artifacts_changed += 1;
            Ok(())
        }
    }
}

fn markdown_cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn display_io(err: io::Error) -> String {
    err.to_string()
}
